### ISSUE TITLE
Proxy download() for elements without href attribute doesn't work (in some cases)

### ISSUE THREAD

**Issue by vinogradoff** [selenide/selenide#1024]
Reproduction

File is downloaded (you can see it), but the test fails with exception below

download.html

```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <button id="assa12" onClick="javascript:c()">Click to download</button>
<script>
function c(){
  var file = "data:application/octet-stream,"
             + encodeURIComponent("<!DOCTYPE html>"
             + "<html><body>"
             + "<div>abc</div>"
             + "</body></html>");
  var saveFile = window.open(file, "_self");
}
</script>
</body>
</html>
```

test

```java
Configuration.proxyEnabled=true;
Configuration.fileDownload=FileDownloadMode.PROXY;
open("file:///./download.html");
File file=$("button").download();
```

Logs 

```
java.io.FileNotFoundException: Failed to download file {button} in 4000 ms.Intercepted 1 responses.
  https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard -> 200 "OK" {Server=ESF, Alt-Svc=quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, Access-Control-Allow-Origin=https://www.google.com, X-Content-Type-Options=nosniff, Pragma=no-cache, Date=Wed, 04 Dec 2019 10:42:02 GMT, Strict-Transport-Security=max-age=31536000, Cache-Control=no-cache, no-store, max-age=0, must-revalidate, Access-Control-Allow-Credentials=true, Content-Security-Policy=script-src 'nonce-S2Pp5ilpO9FxIzxhmLHCHg' 'self' 'unsafe-eval' https://apis.google.com https://ssl.gstatic.com https://www.google.com https://www.gstatic.com https://www.google-analytics.com;report-uri /_/IdentityListAccountsHttp/cspreport, Expires=Mon, 01 Jan 1990 00:00:00 GMT, X-XSS-Protection=0, Content-Length=19, Content-Type=application/json; charset=utf-8} application/json; charset=utf-8  (19 bytes)
	at com.codeborne.selenide.impl.DownloadFileWithProxyServer.firstDownloadedFile(DownloadFileWithProxyServer.java:95)
	at com.codeborne.selenide.impl.DownloadFileWithProxyServer.clickAndInterceptFileByProxyServer(DownloadFileWithProxyServer.java:50)
	at com.codeborne.selenide.impl.DownloadFileWithProxyServer.download(DownloadFileWithProxyServer.java:34)
	at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:52)
	at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:19)

```

**Comment by asolntsev** [comment]
@vinogradoff Yes, it happens when the file is generated on the browser side. Then proxy cannot get it. 
This issue just cannot be solved. What are you suggesting?
