### ISSUE TITLE
Which JDK/JRE and JUnit version needed for selenide?

### ISSUE THREAD

**Issue by ghulam-alekuzei** [selenide/selenide#1027]
## The problem
I configured/imported selenide.jar into my selenium project and using JDK 13.1 with Junit 4, but when I run a test, its failing on open() function giving java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory.
The test is running fine, if I don't use selenide functions.

## Details
I have a feeling that selenide need some specific versions of JDK and Junit, though I tried other version, but getting other errors then like unsupported version etc.

## Tell us about your environment
* **Selenide Version**: 5.5.1
* **Chrome Version**: 79.0.3945.79
* **Selenium Version**: 3.141.59
* **OS Version**: Windows 10 64 bit

@vinogradoff 
Hey Alexei. It's Ghulam here, we used to work in Cisco together. Do you have any idea about this issue, as I know you are an experienced Tester of selenide since many years.

**Comment by ghulam-alekuzei** [comment]
Update: I have added slf4j-api-1.7.25 and slf4j-simple-1.7.25 to project libraries, now I don't get java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory error, but java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy. 
I don't understand I'm not using the code related to these classes at all and still getting no class found errors.

**Comment by ghulam-alekuzei** [comment]
The complete error is:
`java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy

	at com.codeborne.selenide.SelenideDriver.<clinit>(SelenideDriver.java:30)
	at com.codeborne.selenide.WebDriverRunner.<clinit>(WebDriverRunner.java:19)
	at com.codeborne.selenide.Selenide.open(Selenide.java:40)
	at testClass.my_Test(testClass.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.ClassNotFoundException: org.apache.http.ssl.TrustStrategy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 26 more`

**Comment by asolntsev** [comment]
@ghulam-alekuzei Selenide works on any JDK or JRE of version 1.8 and higher. Selenide works with any testing framework, be it Junit 4, JUnit 5, TestNG or whatever else.

What you are missing is Selenide's own dependencies. You have to add all of them. Are you using Maven or Gradle?

**Comment by ghulam-alekuzei** [comment]
I'm using Maven. What are all the dependencies?

**Comment by asolntsev** [comment]
You know it. Just add com.codeborne:Selenide dependency, and Maven will
fetch all its dependencies transitively.
