### ISSUE TITLE
Cannot launch Safari browser with Selenide 5.5.0 and higher

### ISSUE THREAD

**Issue by tarasmytlovych** [selenide/selenide#1053]
## The problem
Cannot launch Safari browser with version 5.5.0 and higher
java.lang.IllegalArgumentException: java.lang.ClassNotFoundException: safari 

## Code To Reproduce Issue 
-Dselenide.browser=safari

## Trace
java.lang.IllegalArgumentException: java.lang.ClassNotFoundException: safari

	at com.codeborne.selenide.webdriver.AbstractDriverFactory.createInstanceOf(AbstractDriverFactory.java:48)
	at com.codeborne.selenide.webdriver.DefaultDriverFactory.create(DefaultDriverFactory.java:16)
	at com.codeborne.selenide.webdriver.WebDriverFactory.lambda$createWebDriver$2(WebDriverFactory.java:52)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:52)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:39)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:117)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:111)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:89)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:47)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:150)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:65)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:28)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:66)
	at com.codeborne.selenide.Selenide.open(Selenide.java:41)

**Comment by BorisOsipov** [comment]
@tarasmytlovych yes we removed safari build in support in 5.5.0

Now you have to use WebDriverProvider to work with safari.
See [WebDriverProvider example](https://github.com/selenide/selenide/wiki/How-Selenide-creates-WebDriver#how-to-run-selenide-with-custom-profile)
