### ISSUE TITLE
interface com.codeborne.selenide.SelenideElement is not visible from class loader

### ISSUE THREAD

**Issue by JBrVJxsc** [selenide/selenide#1085]
## The problem
Getting the following exception while using Selenide:

**interface com.codeborne.selenide.SelenideElement is not visible from class loader**
at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
at java.lang.reflect.WeakCache.get(WeakCache.java:127)
at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
at com.codeborne.selenide.impl.ElementFinder.wrap(ElementFinder.java:41)
at com.codeborne.selenide.impl.ElementFinder.wrap(ElementFinder.java:36)
at com.codeborne.selenide.SelenideDriver.find(SelenideDriver.java:209)
at com.codeborne.selenide.SelenideDriver.find(SelenideDriver.java:189)
at com.codeborne.selenide.SelenideDriver.$(SelenideDriver.java:185)
## Details

- I have a fat jar A which contains a wrapper class of SelenideElement and all dependencies;
- I have a jar B which contains a test class **FoobarTest** which has a `run` method which calls `.$()`;
- I have a jar C which has a class called Runner which has a `execute` method which will use reflection to initialize **FoobarTest** and call its `run` method (which then calls `.$()`);

## Tell us about your environment
* **Selenide Version**: 5.2.4
* **Chrome\Firefox\IE Version**: 
* **Browser Driver Version**: 
* **Selenium Version**: 
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
1. In my Java app, create a class loader (CL for short), which loads all 3 jars into it;
2. Then, create an instance of Runner class using CL's newInstance method;
3. Then, use reflection to call Runner's `execute` method (use reflection here is because the app doesn't have the definition of Runner class);
4. The runner is able to find **FoobarTest** (because both of them are in the same classloader CL) and call its `run` methods, however, when the code runs to the line where calls `.$()`, it will raise the exception.

**Comment by JBrVJxsc** [comment]
reading this article, https://stackoverflow.com/questions/1771679/difference-between-threads-context-class-loader-and-normal-classloader

it looks like it might be related to this piece of code:

    return (T) Proxy.newProxyInstance(
        **currentThread().getContextClassLoader(),**
        new Class<?>[]{clazz},
        new SelenideElementProxy(new ElementFinder(driver, parent, criteria, index)));

**Comment by JBrVJxsc** [comment]
nvm, i figured, setting the thread's context classloader to Runner's classload before calling the test class's run method.
