### ISSUE TITLE
TextReport is not visible (if no slf4j implementation is found in classpath)

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1114]
## The problem
Selenide depends only on `slf4j-api.jar` and doesn't provide any of `slf4j` implementations. 
Users who are not aware of slf4j specifics just don't see any Selenide logs and don't even know about the problem.

## Details
Actually users do see these errors in logs:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

But users don't realise it's somehow connected to Selenide's TextReport. 

## Solution
I suggest that Selenide should fail if there is not slf4j implementations found in classpath. Giving a clear error message like 

```java
java.lang.IllegalStateException: SLF4J is not configured. You will not see any Selenide logs. Please add slf4j-simple.jar, slf4j-log4j12.jar or logback-classic.jar to your classpath.

	at com.codeborne.selenide.Selenide.open(Selenide.java:66)
	at integration.BasicAuthTest.canPassBasicAuth_via_proxy(BasicAuthTest.java:22)
``` 

## Tell us about your environment
* **Selenide Version**:  5.10.0

**Comment by asolntsev** [comment]
Done in https://github.com/selenide/selenide/pull/1115
