### ISSUE TITLE
java.lang.IllegalStateException: java.lang.IllegalStateException: No webdriver is bound to current thread: x. You need to call open(url) first. when using Java8 stream().parallel()

### ISSUE THREAD

**Issue by Firefds** [selenide/selenide#1126]
## The problem
When using page objects in with Java 8 .stream.parallel(), Selenide throws java.lang.IllegalStateException: java.lang.IllegalStateException: No webdriver is bound to current thread: x. You need to call open(url) first. 
## Details
Running the same test without the .parallel() work perfectly.
Running the test with parallel and without Selenide also works.

```
java.lang.IllegalStateException: java.lang.IllegalStateException: No webdriver is bound to current thread: 19. You need to call open(url) first.

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.shauli.desginpatterns.command.HomePageTest.homePageTest(HomePageTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.IllegalStateException: No webdriver is bound to current thread: 19. You need to call open(url) first.
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getWebDriver(WebDriverThreadLocalContainer.java:104)
	at com.codeborne.selenide.WebDriverRunner.getWebDriver(WebDriverRunner.java:73)
	at com.codeborne.selenide.impl.StaticDriver.getWebDriver(StaticDriver.java:37)
	at com.codeborne.selenide.impl.ElementFinder.getSearchContext(ElementFinder.java:86)
	at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:74)
	at com.codeborne.selenide.commands.IsDisplayed.execute(IsDisplayed.java:15)
	at com.codeborne.selenide.commands.IsDisplayed.execute(IsDisplayed.java:11)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:148)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:99)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
	at com.sun.proxy.$Proxy4.isDisplayed(Unknown Source)
	at com.shauli.desginpatterns.command.DismissalAlertValidator.validate(DismissalAlertValidator.java:15)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
## Tell us about your environment
* **Selenide Version**: 5.10.0
* **Chrome\Firefox\IE Version**: Chrome 81.0.4044.113
* **Browser Driver Version**: Chrome 80.0.3987.106 (Download Automatically by Selenide)
* **Selenium Version**: 3.141.59
* **OS Version**: Windows 10

### ElementValidator
```java
public abstract class ElementValidator {
    public abstract boolean validate();
}
```
### DismissalAlertValidator
```java
import com.codeborne.selenide.SelenideElement;

public class DismissalAlertValidator extends ElementValidator {

    private final SelenideElement dismissalAlert;

    public DismissalAlertValidator(SelenideElement dismissalAlert) {
        this.dismissalAlert = dismissalAlert;
    }

    @Override
    public boolean validate() {
        boolean appearanceState = this.dismissalAlert.isDisplayed();
        this.dismissalAlert.$("button.close").click();
        boolean disappearanceState = this.dismissalAlert.isDisplayed();
        return appearanceState && !disappearanceState;
    }
}
```
### HomePage
```java
import com.codeborne.selenide.SelenideElement;

import java.util.Arrays;
import java.util.List;

import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.open;

public class HomePage {

private SelenideElement dismissInfoAlert() {
        return $("div.container-fluid div.row:nth-child(3) div.card-body div.row div:nth-child(2) div.alert-info");
    }

    private SelenideElement dismissSuccessAlert() {
        return $("div.container-fluid div.row:nth-child(3) div.card-body div.row div:nth-child(2) div.alert-success");
    }

    private SelenideElement dismissWarningAlert() {
        return $("div.container-fluid div.row:nth-child(3) div.card-body div.row div:nth-child(2) div.alert-warning");
    }

    private SelenideElement dismissDangerAlert() {
        return $("div.container-fluid div.row:nth-child(3) div.card-body div.row div:nth-child(2) div.alert-danger");
    }

    public static void goTo() {
        open("https://www.wrappixel.com/demos/admin-templates/admin-pro/main/ui-notification.html");
    }

    public List<ElementValidator> getElementValidators() {

        return Arrays.asList(
                new DismissalAlertValidator(dismissInfoAlert()),
                new DismissalAlertValidator(dismissSuccessAlert()),
                new DismissalAlertValidator(dismissWarningAlert()),
                new DismissalAlertValidator(dismissDangerAlert())
        );
    }
}
```
### HomePageTest
```java
import org.testng.Assert;
import org.testng.annotations.Test;

import static com.codeborne.selenide.Selenide.page;

public class HomePageTest {

    @Test
    public void homePageTest() {
        HomePage.goTo();
        HomePage homePage = page(HomePage.class);
        homePage.getElementValidators()
                .stream()
                .parallel()
                .map(ElementValidator::validate)
                .forEach(Assert::assertTrue);
    }
}
```

**Comment by rosolko** [comment]
Selenium doesn't support `stream().parallel()` selenide, respectively, too

**Comment by asolntsev** [comment]
Yes, Selenium WebDriver is not thread-safe. You cannot use the same
webdriver in multiple threads.

Just remove ".parallel()":

this.homePage.getElementValidators()
                .stream()
                .map(ElementValidator::validate)
                .forEach(Assert::assertTrue);


NB! I think this code is over-engineered. I recommend to simplify it. You
don't really need list of validators and iteration. Just call this code
directly, one by one.

Andrei Solntsev


вс, 19 апр. 2020 г. в 10:14, Aliaksandr Rasolka <notifications@github.com>:

**Comment by Firefds** [comment]
@asolntsev When using this code without Selenide, the parallel works perfectly.

I know it's a bit over-egineered. I'm learning about design patterns and this was one of the excersies.
The course itself doesn't use Selenide, but I'm implementing it with it.
