### ISSUE TITLE
Concurrent modification since selenide 5.12.0

### ISSUE THREAD

**Issue by cocorossello** [selenide/selenide#1170]
## The problem
Occasional random ConcurrentModificationException since we upgraded to 5.12.0
It never happend in older releases

## Details
```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1226)
	at com.codeborne.selenide.webdriver.WebDriverFactory.findFactory(WebDriverFactory.java:80)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:65)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:53)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:45)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:126)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:120)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:89)

```

## Tell us about your environment
v5.12.0

## Code To Reproduce Issue [ Good To Have ]
Can't provide that. I'm testing with 60 parallel browser, problem appears sometimes

**Comment by cocorossello** [comment]
Awesome, thanks
