### ISSUE TITLE
CdpClient error with EdgeDriver on Windows

### ISSUE THREAD

**Issue by kapoe-net** [selenide/selenide#1235]
## The problem
On Windows, error when call CdpClient.setDownloadsFolder() because it doesn't escape the file separator.

## Details

```

java.lang.RuntimeException: Failed to set downloads folder to C:\dev\sources\middleware\build\downloads

	at com.codeborne.selenide.webdriver.CdpClient.setDownloadsFolder(CdpClient.java:38)
	at com.codeborne.selenide.webdriver.CdpClient.setDownloadsFolder(CdpClient.java:28)
	at com.codeborne.selenide.webdriver.EdgeDriverFactory.create(EdgeDriverFactory.java:46)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:76)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:54)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:50)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:136)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:128)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:89)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:61)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:180)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:70)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:76)
	at com.codeborne.selenide.Selenide.open(Selenide.java:48)
	...
Caused by: java.io.IOException: Failed to send CDP command {  "cmd": "Page.setDownloadBehavior",
  "params": {
    "behavior": "allow", 
    "downloadPath": "C:\dev\sources\middleware\build\downloads"
  }
}: status=400, error=Bad Request
	at com.codeborne.selenide.webdriver.CdpClient.post(CdpClient.java:79)
	at com.codeborne.selenide.webdriver.CdpClient.setDownloadsFolder(CdpClient.java:34)
	at com.codeborne.selenide.webdriver.CdpClient.setDownloadsFolder(CdpClient.java:28)
	at com.codeborne.selenide.webdriver.EdgeDriverFactory.create(EdgeDriverFactory.java:46)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:76)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:54)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:50)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:136)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:128)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:89)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:61)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:180)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:70)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:76)
	at com.codeborne.selenide.Selenide.open(Selenide.java:48)
        ...
```

Solution : 

```
@ParametersAreNonnullByDefault
public class CdpClient {
     ...

    String escapeForJson(String text) {
        if(File.separator.equals("\\")) {
           text = text.replace("\\", "\\\\"); 
        }
        return REGEX_ENCODE_FOR_JSON.matcher(text).replaceAll(quoteReplacement("\\\""));
    }
```

## Tell us about your environment
* **Selenide Version**: 3.13.0
* **MS Edge Version**: 84.0.522.40
* **Browser Driver Version**: 84.0.522.40
* **OS Version**: Windows 10

**Comment by asolntsev** [comment]
Wow. Thank you. Will release a patch soon.

**Comment by asolntsev** [comment]
@kapoe-net I just release Selenide 5.13.1.
Thank you for reporting the issue!
