### ISSUE TITLE
displayed:false on visible checkboxes

### ISSUE THREAD

**Issue by pgarbocz** [selenide/selenide#1251]
## Details
I've encountered a similar problem on checkboxes like other people here: https://github.com/selenide/selenide/issues/201.
I use the following selector: 
`return $$(".list-group-item")
                .filterBy(text(permissionName)).first()
                .$("input");`

It returns proper element, but allegedly it is not visible, although I can see it and I am able to click it.

Here's the exception
`Element should be visible {input}
Element: '<input _ngcontent-bxy-c99 class="custom-control-input" type="checkbox" value="on" displayed:false></input>'
Actual value: visible:false
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:72)
	at com.codeborne.selenide.commands.Should.execute(Should.java:24)
	at com.codeborne.selenide.commands.Should.execute(Should.java:10)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:150)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:100)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:66)
	at com.sun.proxy.$Proxy27.shouldBe(Unknown Source)
	at pages.administration.Policies.addPolicy(Policies.java:77)
	at tests.Management.PoliciesTests.addAndEditPolicy(PoliciesTests.java:68)`

And here's the HTML element:
`<div _ngcontent-huo-c52="" class="list-group-item"><div _ngcontent-huo-c99="" class="justify-content-start g-row d-grid"><div _ngcontent-huo-c99="" class="col-w-12"><label _ngcontent-huo-c99="" class="custom-control custom-checkbox"><input _ngcontent-huo-c99="" type="checkbox" class="custom-control-input"><span _ngcontent-huo-c99="" class="custom-control-indicator"></span><span _ngcontent-huo-c99="" class="custom-control-label permission-label">something</span></label></div></div><!----></div>`

## Tell us about your environment
* **Selenide Version**: 5.12
* **Chrome**: 84.0.4147.125
* **Browser Driver Version**: 84.0.4147.30
* **Selenium Version**: 3.141.59
* **OS Version**: Windows 10

**Comment by asolntsev** [comment]
@pgarbocz How can I reproduce the issue? 
Provided html is not enough. I believe these elements also have some styles. I guess they have `opacity: 0` or something similar.

**Comment by pgarbocz** [comment]
@asolntsev Yes, you're right, opacity is set to 0.
