### ISSUE TITLE
Selenide tests often fail on TravisCI with error "Chrome failed to start"

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1279]
## The problem
We are running tests on Travis CI. Sometimes our tests fail because of `WebDriverException: unknown error: Chrome failed to start: exited abnormally`.

We don't know why it happens. Probably a simple workaround could be to re-try opening a browser? Say, 2 or 3 times. 

## Stack trace

```java
integration.CollectionBecauseTest > canExplainWhyConditionIsExpected_textsSizeMismatch() FAILED
    org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally.
      (chrome not reachable)
      (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'travis-job-fa21862f-5799-4264-9e23-9855a1751fab', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1077-gcp', java.version: '11.0.2'
    Driver info: driver.version: SelenideDriver
    selenide.url: https://127.0.0.1:24022/page_with_selects_without_jquery.html?browser=chrome&timeout=10
    selenide.baseUrl: https://127.0.0.1:24022
    remote stacktrace: #0 0x560d9b42ea39 <unknown>
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
        at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:54)
        at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:82)
        at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:59)
        at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:67)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:153)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:139)
        at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:97)
        at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:62)
        at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:188)
        at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:70)
        at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
        at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:84)
        at com.codeborne.selenide.Selenide.open(Selenide.java:49)
        at integration.IntegrationTest.openFile(IntegrationTest.java:75)
        at integration.CollectionBecauseTest.openTestPage(CollectionBecauseTest.java:21)
```

**Comment by SeleniumTestAB** [comment]
Could be that the crash occured because of lack of resources? Chrome does take a chunk of them

**Comment by asolntsev** [comment]
@SeleniumTestAB Yes, probably. But how can we solve this problem?

**Comment by SeleniumTestAB** [comment]
@asolntsev i would suggest couple of things:
1) adding resources
2) try to open less browser instances during tests
3) make sure that chrome process was killed with webdriver before opening new browser (this would be more of test trick than selenide inner mechanism)

I am not well versed how Travis was setup and how much it takes as resources but those three options could help. Especially 2nd and 3rd one (because they are free)

**Comment by asolntsev** [comment]
@SeleniumTestAB yes, I will start with 3rd iption.
it seems that Selenide opens multiple browsers during it's tests, and closes them only in the end of tests. I will investigate it.

**Comment by asolntsev** [comment]
@SeleniumTestAB yes, I will start with 3rd iption.
it seems that Selenide opens multiple browsers during it's tests, and closes them only in the end of tests. I will investigate it.

**Comment by asolntsev** [comment]
fixed by commit https://github.com/selenide/selenide/commit/16cef4752f2166c1b0f313c874356aea7d0760fc
