### ISSUE TITLE
Receiving java.lang.NoSuchMethodError when running for Firefox

### ISSUE THREAD

**Issue by alekseiaksenov** [selenide/selenide#1295]
## The problem
I'm trying to set up Selenide 5.15 with Java 11 and TestNG. When I run a test with browser = chrome or edge, it runs smoothly. If I change browser property to firefox, I get that:
```
org.openqa.selenium.firefox.FirefoxDriver.<init>(Lorg/openqa/selenium/firefox/GeckoDriverService;Lorg/openqa/selenium/firefox/FirefoxOptions;)V
java.lang.NoSuchMethodError: org.openqa.selenium.firefox.FirefoxDriver.<init>(Lorg/openqa/selenium/firefox/GeckoDriverService;Lorg/openqa/selenium/firefox/FirefoxOptions;)V
	at com.codeborne.selenide.webdriver.FirefoxDriverFactory.create(FirefoxDriverFactory.java:45)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:95)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:60)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:67)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:153)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:139)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:97)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:62)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:188)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:70)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:84)
	at com.codeborne.selenide.Selenide.open(Selenide.java:49)
	at ru.x73.ui.MainTest.test(MainTest.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	...
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## Details
I have a very simple setup. Here's my build.gradle:
```
plugins {
    id 'java'
}

group 'selenidetest'
version '1.0-SNAPSHOT'
sourceCompatibility = 11

repositories {
    mavenCentral()
}

dependencies {
    compile group: 'org.testng', name: 'testng', version: '7.3.0'
    compile group: 'com.codeborne', name: 'selenide', version: '5.15.1'
    compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.0.0-alpha-1'
}

test {
    useTestNG()
}
```

Here's my test class:
```
public class MainTest {
    @BeforeSuite
    private void before() {
        Configuration.browser = FIREFOX;
        Configuration.startMaximized = true;
    }

    @Test
    public void test() {
        open("https://google.com");
    }
}
```

## Tell us about your environment
* **Selenide Version**: 5.15.1
* **Java Version**: 11
* **TestNG Version**: 7.3.0
* **Firefox**: 82.0.2
* **Browser Driver Version**: provided by Selenide 5.15.1
* **Selenium Version**: '4.0.0-alpha-1
* **OS Version**: Windows 10 Pro 1909

## Code To Reproduce Issue [ Good To Have ]
See above

**Comment by BorisOsipov** [comment]
>compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.0.0-alpha-1'

It is alpha version with breaking changes. It will not work with Selenide 5. If you want to use selenium 4 alpha's you can get Selenide [alpha version with selenium 4 support](https://github.com/selenide/selenide/pull/1099) from jitpack

1. add repository
```
repositories {
    maven { url 'https://jitpack.io' }
}
```
2. add dependency
```
dependencies {
    implementation 'com.github.selenide:selenide:upgrade-to-selenium4-alpha5-SNAPSHOT'
}
```
But it is alpha and you use it at one's own risk.

if you don't need selenium 4 just remove it from dependencies.

**Comment by alekseiaksenov** [comment]
@BorisOsipov thank you for the quick response.
Yes, I tried to downgrade to selenium 3, but I also got another error: `java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;`

I fixed that one out by **stating 29th guava in build.gradle explicitly**:
compile group: 'com.google.guava', name: 'guava', version: '29.0-jre'
