### ISSUE TITLE
Hover failing

### ISSUE THREAD

**Issue by Tonicku** [selenide/selenide#1311]
hi the hover functionality not working 

Browser                : Opera
Operating System: Windows 10

Dependency in use
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>5.15.1</version>
        </dependency>

If i understand well, the hover should simulate the mouse being over. But, unfortunately, it doesn't

`        SelenideElement selectedMainNavItem = NAVIGATION_BAR.$x(".//ul[contains(@class, 'navbar-nav')]/li[a[@id='dropdown-" + subMenu.getMenuTitle().replace(" ", "-") + "']]");
        selectedMainNavItem.hover();
        SelenideElement selectedSubMainNavItem = selectedMainNavItem.$x("./ul/li/a[@href='/resumes/']"); //.should(Condition.text(subMenu.getTitle()));
        selectedSubMainNavItem.click();`

Log
`Element should be visible or transparent: visible or have css value opacity=0 {By.xpath: ./ul/li/a[@href='/resumes/']}
Element: '<a class="ng-binding" href="/resumes/" ng-bind-html="::child.display" tabindex="0" target type displayed:false></a>'
Actual value: visible:false, 1

at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:94)
	at com.codeborne.selenide.impl.WebElementSource.findAndAssertElementIsInteractable(WebElementSource.java:112)
	at com.codeborne.selenide.commands.Click.execute(Click.java:22)
	at com.codeborne.selenide.commands.Click.execute(Click.java:15)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:153)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:104)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:70)
	at com.sun.proxy.$Proxy50.click(Unknown Source)
	at .........................NavigationPage.selectSubmenuFromNavigationBar(NavigationPage.java:57)
	at..........................ResumeStep.navigateToResumesPage(ResumeStep.java:13)
	at .........................ResumeTest.resumeNameTest(ResumeTest.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:238)
	at mgs.qa.base.test.TestBase.run(TestBase.java:142)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:252)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:595)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)`

**Comment by Tonicku** [comment]
typo.... thanks
