### ISSUE TITLE
Test hangs if chrome browser opens inaccessible url

### ISSUE THREAD

**Issue by BorisOsipov** [selenide/selenide#1352]
## The problem
```
    @Test
    public void openPage() {
        Selenide.open("http://www.test.test/");
        assertEquals(WebDriverRunner.getWebDriver().getCurrentUrl(), "http://www.test.test/");
    }
```
The test above hangs on `WebDriverRunner.getWebDriver().getCurrentUrl()`

Cause:
```
public class ChromeDriverFactory
...
  @CheckReturnValue
  @Nonnull
  protected String[] excludeSwitches(Capabilities capabilities) {
    return hasExtensions(capabilities) ?
      new String[]{"enable-automation"} :
      new String[]{"enable-automation", "load-extension"};
  }
...
```
When user use it is own `ChromeDriverFactoryImpl` with empty `excludeSwitches` test passed.
Issue appears on Selenide 5.9+

**Comment by asolntsev** [comment]
@BorisOsipov I cannot reproduce the problem. :(  

For me, it fails quickly on `open("http://www.test.test/")`:

```
unknown error: net::ERR_NAME_NOT_RESOLVED
...
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:84)
	at com.codeborne.selenide.Selenide.open(Selenide.java:49)
```

**Comment by BorisOsipov** [comment]
The same. That's strange. Seems fixed in new chromedriver versions.
