### ISSUE TITLE
Broken .setValue(null) in #1138

### ISSUE THREAD

**Issue by dzem** [selenide/selenide#1356]
## The problem
In selenide 5.17.0 `.setValue(null)` is fail with NPE.

## Details
Reason is call arguments.ofType(Duration.class); with arguments contains array with null value
`java.lang.NullPointerException
	at com.codeborne.selenide.impl.Arguments.ofType(Arguments.java:38)
	at com.codeborne.selenide.impl.SelenideElementProxy.getTimeoutMs(SelenideElementProxy.java:169)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:75)`

## Tell us about your environment
* **Selenide Version**: 5.17.0
* **Chrome\Firefox\IE Version**:  87.0.4280.88
* **OS Version**: Win

## Code To Reproduce Issue
`$().setValue(null);`

**Comment by asolntsev** [comment]
Fixed in https://github.com/selenide/selenide/pull/1357
