### ISSUE TITLE
Using ClickOptions on IE raises an JavascriptException "Object doesn't support this action" .

### ISSUE THREAD

**Issue by tmshft** [selenide/selenide#1406]
Hi . 
ClickOptions feature is so useful and I love it.
But JavascriptException raised on IE.

## The problem

I tried to click button tag by using `ClickOptions.usingJavaScript()` on IE11.

Then JavascriptException has raised.

If I use `#usingDefaultMethod` , the test is passed(we can  click element)

## environment

* **Selenide Version**: 5.18.0
* **Chrome\Firefox\IE Version**: IE11
* **Browser Driver Version**: IEDriverServer 3.150
* **Selenium Version**: 3.141.59
* **OS Version**: Windows10

## Code To Reproduce Issue [ Good To Have ]

source 

```
$("#mylocator").click(ClickOptions.usingJavaScript());
```

html source of target button.

```html
<button class="somthing" tabindex="0" type="submit" id="RacineSubmit" name="Submit"><span class="something">login</span></button>
```

log 

```log
2021-02-15 xx:28:59,793 [Test worker] [INFO]:com.codeborne.selenide.drivercommands.CreateDriverCommand#createDriver:Create webdriver in current thread 14: InternetExplorerDriver -> InternetExplorerDriver: internet explorer on WINDOWS (xxxxxx)

JavascriptException: Error from JavaScript: Object doesn't support this action
Screenshot: path
Page source: path
Timeout: 10 s.
Caused by: JavascriptException: Error from JavaScript: Object doesn't support this action
	at com.codeborne.selenide.ex.UIAssertionError.wrapToUIAssertionError(UIAssertionError.java:83)
	at com.codeborne.selenide.ex.UIAssertionError.wrapThrowable(UIAssertionError.java:74)
	at com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java:68)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:90)
	at com.sun.proxy.$Proxy45.click(Unknown Source)
	at mypackage.WebTestUtils.login(WebTestUtils.java:93)
```

**Comment by arunahk** [comment]
Is anyone checking on this?

**Comment by asolntsev** [comment]
@arunahk I am going to find some windows laptop and debug this issue. But it takes some time. It would be great if you do it sooner.

**Comment by BorisOsipov** [comment]
@asolntsev I played with click via js script and it is issue desribed in https://stackoverflow.com/questions/27176983/dispatchevent-in-chrome-but-not-in-ie11

I tested script below worked for me for IE11 and latest chrome.

```
var $el = document.querySelector("#lolkek")
var rect = $el.getBoundingClientRect();
var Xoffset = 0
var Yoffset = 0
var event

if (typeof (Event) === 'function') {
    event = new MouseEvent('click', {
        'view': window,
        'bubbles': true,
        'cancelable': true,
        'clientX': rect.left + rect.width / 2 + Xoffset,
        'clientY': rect.top + rect.height / 2 + Yoffset
    });
} else {
    event = document.createEvent('MouseEvent');
    event.initEvent('click', true, true);
    event.type = 'click'
    event.view = window;
    event.clientX = rect.left + rect.width / 2 + Xoffset
    event.clientY = rect.top + rect.height / 2 + Yoffset
}

$el.dispatchEvent(event);
```

**Comment by asolntsev** [comment]
@BorisOsipov Thank you, I have create PR with this JS.

**Comment by tmshft** [comment]
thank you so much @asolntsev , @BorisOsipov
