### ISSUE TITLE
Caused by: TimeoutException: Expected condition failed after 5.14.0 update

### ISSUE THREAD

**Issue by spatiumstas** [selenide/selenide#1420]
## The problem
Caused by: TimeoutException: Expected condition failed: waiting for frame to be available: 2 (tried for 15 second(s) with 200 milliseconds interval)
	at com.codeborne.selenide.SelenideTargetLocator.frameNotFoundError(SelenideTargetLocator.java:303)
	at com.codeborne.selenide.SelenideTargetLocator.frame(SelenideTargetLocator.java:51)

## Details
Judging by the changes, only this code was affected 
at com.codeborne.selenide.SelenideTargetLocator.frame(SelenideTargetLocator.java:51)

![image](https://user-images.githubusercontent.com/79056064/109342868-8e628b00-787d-11eb-86d1-38901da38f35.png)

## Tell us about your environment
* **Selenide Version**: 5.19.0
* **Chrome\Firefox\IE Version**:  88 Chrome
* **Browser Driver Version**: 4.3.1
* **Selenium Version**: 3.141.59

**Comment by asolntsev** [comment]
@spatiumstas As I see, nothing was changed here, only code reformatting. 
Could you describe your problem more precisely? 
1. code to reproduce the problem
2. Full error message with stacktrace

**Comment by spatiumstas** [comment]
@asolntsev  

Caused by: TimeoutException: Expected condition failed: waiting for frame to be available: 2 (tried for 15 second(s) with 200 milliseconds interval)
	at com.codeborne.selenide.SelenideTargetLocator.frameNotFoundError(SelenideTargetLocator.java:303)
	at com.codeborne.selenide.SelenideTargetLocator.frame(SelenideTargetLocator.java:51)
	at utilities.codeFeatures.GeneralFunctions.selectActiveFrame(GeneralFunctions.java:264)


```
public void selectActiveFrame(SelenideDriver selenideDriver, int frameIndex) {

    try {
      selenideDriver.switchTo().frame(frameIndex); //java:264
      ALLURE_LOGGER.info("Navigated to frame with index: " + frameIndex);
    } catch (NoSuchFrameException ex) {
      ALLURE_LOGGER.info(
          "Unable to locate frame with index: " + frameIndex + Arrays.toString(ex.getStackTrace()));
    } catch (Exception ex) {
      ALLURE_LOGGER.info(
          "Unable to navigate to frame with index: "
              + frameIndex
              + Arrays.toString(ex.getStackTrace()));
    }
  }

```

**Comment by asolntsev** [comment]
@spatiumstas No, please FULL error message with FULL stack trace. Your stacktrace about starts with "Caused by:" which means that it's already truncated. And please use https://gist.github.com/ for this.

**Comment by asolntsev** [comment]
Feel free to reopen the issue in case of new information.
