### ISSUE TITLE
"DevToolsActivePort file doesn’t exist" issue with Gradle 

### ISSUE THREAD

**Issue by SergiiTrybushnyi** [selenide/selenide#1462]
Hello guys, I've came across the issue while re-writing our tests. 
 
The issue is: my tests work with Maven, but not with Gradle.

I created simple Maven project with one test:

`Selenide.open("https://ukr.net);
System.out.println("lol");`

After that I ran it on our Jenkins, received:

`Running DebugTest
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@3419866c
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
_________________________________
Starting ChromeDriver 79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}) on port 7665
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
May 05, 2021 11:52:40 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
lol
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.111 sec
Results :
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
_________________________________________
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.347 s
[INFO] Finished at: 2021-05-05T11:52:46+00:00
[INFO] Final Memory: 17M/178M
[INFO] ------------------------------------------------------------------------
Archiving artifacts
Collecting metadata...
Metadata collection done.
Finished: SUCCESS`

After I went to project folder and made
`gradle init`

Created all the needed files for running project with gradle, launched it with gradle --info test and received:

`Gradle suite > Gradle test > DebugTest > test FAILED
    org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally
      (unknown error: DevToolsActivePort file doesn't exist)
      (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'jenkins-main-0', ip: '10.194.1.28', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1050-aws', java.version: '1.8.0_201'
    Driver info: driver.version: SelenideDriver
    selenide.url: https://ukr.net
    selenide.baseUrl: http://localhost:8080
    remote stacktrace: #0 0x558ae9d14479 <unknown>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
        at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:55)
        at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:110)
        at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:71)
        at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:68)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:153)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:139)
        at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:105)
        at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
        at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:191)
        at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:68)
        at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:139)
        at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:66)
        at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:30)
        at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:86)
        at com.codeborne.selenide.Selenide.open(Selenide.java:49)
        at DebugTest.test(DebugTest.java:15)`

I am using Selenide 5.20.4. Please advise, what can be wrong? 

Thank you

**Comment by BorisOsipov** [comment]
@SergiiTrybushnyi Add `Configuration.headless = true` for headless chrome execution or use `Xvfb`

**Comment by SergiiTrybushnyi** [comment]
> @SergiiTrybushnyi Add `Configuration.headless = true` for headless chrome execution or use `Xvfb`

Thanks a lot, xvfb helped. Didn't see this solution across the internet. Hopefully it will help someone else in the future
