### ISSUE TITLE
Add support of iframe elements inside Shadow DOM

### ISSUE THREAD

**Issue by antongrinenko** [selenide/selenide#1466]
I have an iframe inside the shadow dom. When I try to click the button inside iframe I get an error:

`WebDriverException: unknown error: no element reference returned by script
        at com.codeborne.selenide.ex.UIAssertionError.wrapToUIAssertionError(UIAssertionError.java:83)
	at com.codeborne.selenide.ex.UIAssertionError.wrapThrowable(UIAssertionError.java:74)
	at com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java:68)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:95)
	at com.sun.proxy.$Proxy9.click(Unknown Source)
`

Here is the code to reproduce the issue:
https://github.com/antongrinenko/selenide-shadow-dom-iframe

**Comment by BorisOsipov** [comment]
@antongrinenko thanks for reporting this. Would you mind proposing a PR? :)

**Comment by antongrinenko** [comment]
Thanks a lot! That solves my problem )))
