### ISSUE TITLE
Avoid spam in logs when webdriver is already closed

### ISSUE THREAD

**Issue by cbxp** [selenide/selenide#1467]
In the end of tests, Selenide tries to close the webdriver, but it's already closed at that moment. 

It would be great to avoid such spam in logs:

```
2021-05-12 09:43:00.645  INFO 598695 --- [s killer thread] c.c.s.i.UnusedWebdriversCleanupThread    : Thread 23 is dead. Let's close webdriver ChromeDriver: chrome on LINUX (d2c98615b0b96338b83997dae4456942)
Exception in thread "Webdrivers killer thread" 2021-05-12 09:43:00.654  INFO 598695 --- [       Thread-6] c.c.s.drivercommands.CloseDriverCommand  : Closed webdriver 66 in 67 ms
org.openqa.selenium.WebDriverException: The driver server has unexpectedly died!
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'xp42', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.8.0-50-generic', java.version: '16.0.1'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:452)
	at com.codeborne.selenide.impl.UnusedWebdriversCleanupThread.closeWebDriver(UnusedWebdriversCleanupThread.java:63)
	at com.codeborne.selenide.impl.UnusedWebdriversCleanupThread.closeUnusedWebdrivers(UnusedWebdriversCleanupThread.java:50)
	at com.codeborne.selenide.impl.UnusedWebdriversCleanupThread.run(UnusedWebdriversCleanupThread.java:35)
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:17948
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	... 6 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:669)
```

## Tell us about your environment
* **Selenide Version**: 5.20.4
* **Chrome\Firefox\IE Version**:  Chrome
* **Browser Driver Version**: 90
* **Selenium Version**:  3.14
* **OS Version**:  Ubuntu 20.04

**Comment by cbxp** [comment]
Another error in logs:

```
2021-05-18 14:03:42.083  INFO 1006951 --- [       Thread-6] c.c.s.drivercommands.CloseDriverCommand  : Closed webdriver 66 in 67 ms
Exception in thread "Webdrivers killer thread" org.openqa.selenium.WebDriverException: The driver server has unexpectedly died!
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
Driver info: driver.version: RemoteWebDriver
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:89)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
        at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:452)
        at com.codeborne.selenide.impl.UnusedWebdriversCleanupThread.closeWebDriver(UnusedWebdriversCleanupThread.java:63)
        at com.codeborne.selenide.impl.UnusedWebdriversCleanupThread.closeUnusedWebdrivers(UnusedWebdriversCleanupThread.java:50)
        at com.codeborne.selenide.impl.UnusedWebdriversCleanupThread.run(UnusedWebdriversCleanupThread.java:35)
```
