### ISSUE TITLE
java.lang.NullPointerException during creating of webdriver instance

### ISSUE THREAD

**Issue by ilya-corp** [selenide/selenide#1471]
Hello!

My project using Chrome latest driver for accessing to web pages and chromedriver 83 for controlling of Electron application. Both types of apps are used in the test.
I received following error during creating of webdriver instances in my multithread Cucumber test project under TestNG control.

```java
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.setWebDriver(WebDriverThreadLocalContainer.java:85)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.setWebDriver(WebDriverThreadLocalContainer.java:64)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.setWebDriver(WebDriverThreadLocalContainer.java:59)
	at com.codeborne.selenide.WebDriverRunner.setWebDriver(WebDriverRunner.java:67)
	at ru.XXXXXXX.tools.BrowserTools.openElectronApp(BrowserTools.java:41)
	at ru.cleversite.cucumber.glue.desk.Desk_Common_Steps.operatorOpeningDeskInTheNewBrowserOrApp(Desk_Common_Steps.java:168)
	at ✽.оператор открывает новый пульт (далее "Пульт")(file:///C:/xxxxxxxxxxxxxxx/src/main/resources/features/Desk/Operator%20actions/Hotkeys%20New.feature:27)
```

The probable related error from another thread:

```
java.lang.IllegalStateException: No webdriver is bound to current thread: 22. You need to call open(url) first.

	at com.codeborne.selenide.drivercommands.LazyDriver.getWebDriver(LazyDriver.java:88)
	at com.codeborne.selenide.SelenideDriver.getWebDriver(SelenideDriver.java:186)
	at ru.XXXXXXX.DriverFactory.createWebDriver(DriverFactory.java:35)
	at ru.XXXXXXX.tools.BrowserTools.openUrlInTheNewBrowser(BrowserTools.java:31)
	at ru.XXXXXXX.cucumber.glue.Common_Steps.openCustomPageInTheNewBrowser(Common_Steps.java:110)
	at ✽.посетитель открывает страницу "${адрес основного сайта}" в новом браузере (далее "Площадка")(file:///C:/XXXXXXX/src/main/resources/features/Desk/Operator%20actions/Hotkeys%20New.feature:183)
```

## Tell us about your environment
* **Selenide Version**: latest 5.20.1
* **Chrome\Firefox\IE Version**: Chrome 90 for opening webpages
* **Browser Driver Version**: embedded for web pages and Chrome 83 for Electron app
* **Selenium Version**: 
* **OS Version**: Win10

## Code To Reproduce Issue [ Good To Have ]

```java
public WebDriver createAppDriver() throws InterruptedException {
        WebDriver appDriver = null;
        try {
            while (!tryLock()) {
                Thread.sleep(10);
            }

            String previousChromeBinaryPath = System.getProperty("webdriver.chrome.driver");
            ChromeOptions chromeOptions = new ChromeOptions();
            chromeOptions.setBinary(System.getProperty("user.home") + "\\AppData\\Local\\Programs\\XXXXXXXX\\XXXXXXX.exe");
            System.setProperty("webdriver.chrome.driver", "drivers/chromedriver/win32/83/chromedriver.exe");
            appDriver = new ChromeDriver(chromeOptions);

            // Восстанавливаем исходные настройки
            if (previousChromeBinaryPath != null) {
                System.setProperty("webdriver.chrome.driver", previousChromeBinaryPath);
            } else {
                System.setProperty("webdriver.chrome.driver", "");
            }
        }
        catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
        finally {
            unLock();
            return appDriver;
        }
    }

    private synchronized boolean tryLock() {
        if (!Settings.isWebDriverManagerBusy) {      
            Settings.isWebDriverManagerBusy = true;  
            return true;            
        }
        else {                      
            return false;         
        }
    }

    private synchronized void unLock() {
        Settings.isWebDriverManagerBusy = false;
    }

// This is a field of Settings class
public static volatile boolean isWebDriverManagerBusy = false;    // volatile disables caching for threads
```

XXXXXXX - name of the project.

This problem may not be reproduced at every test run. I have caught it only once. Yesterday I performed 5-6 iterations of my tests without error and today error appeared at second pass and was not reproduced at 3th and 4th pass.

**Comment by asolntsev** [comment]
@ilya-corp This NPE can only happen if WebDriver is null:

```java
WebDriverRunner.setWebDriver(null);
```

**Comment by ilya-corp** [comment]
Sure, looks like problem related to unexpected null as argument of setWebDriver() method.
Ticket may be closed.
