### ISSUE TITLE
5.25.0-selenium-4.0.0-rc-2 not working with browserup-proxy-core (dependency issues)

### ISSUE THREAD

**Issue by thomas-eaa** [selenide/selenide#1593]
## The problem
Using `selenide 5.25.0-selenium-4.0.0-rc-2` does not work in combination with `browserup-proxy-core 2.1.2` because of dependency conflicts (`selenium-api`, `netty`).

## Details
`selenide 5.25.0-selenium-4.0.0-rc-2` requires `selenium-api 4.0.0-rc2`, whereas `browserup-proxy-core  2.1.2` (latest version) requires `selenium-api 3.141.59`. Even after exclusion of the older dependency, issues with conflicting versions of `netty` dependencies appear and cannot be resolved:

`Caused by: java.lang.NoSuchMethodError: 'java.lang.String io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim(java.lang.String, java.lang.String)'
	at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:123)
	at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:36)
	at org.asynchttpclient.netty.request.NettyRequestFactory.newNettyRequest(NettyRequestFactory.java:114)
	at org.asynchttpclient.netty.request.NettyRequestSender.newNettyRequestAndResponseFuture(NettyRequestSender.java:204)
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:136)
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:114)
	at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:259)
	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:228)
	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:249)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:57)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:119)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	... 87 more
`

## Tell us about your environment
* **Selenide Version**: 4.0.0-rc2
* **Chrome\Firefox\IE Version**: 94 
* **Browser Driver Version**:  94
* **Selenium Version**: 4.0.0
* **OS Version**: Windows 10

## Code To Reproduce Issue [ Good To Have ]
Use `selenide 5.25.0-selenium-4.0.0-rc-2` in combination with `browserup-proxy-core  2.1.2`

**Comment by asolntsev** [comment]
solved by https://github.com/selenide/selenide/pull/1612
