### ISSUE TITLE
6.1.0 Regression with `switchTo().defaultContent()`

### ISSUE THREAD

**Issue by dacloutier-logmein** [selenide/selenide#1643]
## The problem
 Starting version 6.1.0, trying to use the `switchTo().defaultContent()` will break due to an Null Pointer Exception
 
 Reverting to a 5.25.0 or 6.0.3 works just fine.

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**:  6.1.0
* **Chrome\Firefox\IE Version**:  doesn't matter, tried all 3 browser's latest version 
* **Browser Driver Version**: 
* **Selenium Version**:  4.1.0
* **OS Version**:  mac os 10.16

Sample stack Trace:
```
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DEV-LAPTOP', ip: 'fe80:0:0:0:465:1366:370e:afb9%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.8'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [ec540f3b48cad6480e2361b24b5b008dd7bb3ede92c911c321b3c8a7eef02d61, switchToFrame {id=null}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 96.0.4664.45, chrome: {chromedriverVersion: 96.0.4664.45 (76e4c1bb2ab46..., userDataDir: /tmp/.com.google.Chrome.Dd4VcM}, goog:chromeOptions: {debuggerAddress: localhost:32774}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: ec540f3b48cad6480e2361b24b5b008dd7bb3ede92c911c321b3c8a7eef02d61

	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:583)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.defaultContent(RemoteWebDriver.java:1042)
	at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:165)
	at com.codeborne.selenide.SelenideTargetLocator.defaultContent(SelenideTargetLocator.java:118)
	at EXACT_LINE_THAT_DOES_THE_SWITCH_TO_DEFAULT_CONTENT
    ...
Caused by: java.lang.NullPointerException
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:47)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	... 114 more
```
## Code To Reproduce Issue [ Good To Have ]
```
    @Test
    public void iframeTest() {

        final Map<String, Object> options = new HashMap<>();
        options.put("sessionTimeout", "30s");
        options.put("name", "test iframe");
        final DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("selenoid:options", options);

        Configuration.browserCapabilities = capabilities;
        Configuration.remote = "http://HOST:4444/wd/hub";
        Configuration.browser = "firefox";
        Configuration.browserVersion = "94";

        open("https://www.w3schools.com/html/html_iframe.asp");

        SelenideElement intro = $(byClassName("intro"));
        intro.shouldHave(text("An HTML iframe is used to display a web page within a web page."));

        webdriver().object().switchTo().frame(0);

        SelenideElement frameTitle = $(byTagName("h1"));
        frameTitle.shouldHave(text("HTML Tutorial"));

        webdriver().object().switchTo().defaultContent();

        SelenideElement mainTitle = $(byTagName("h1"));
        mainTitle.shouldHave(text("HTML Iframes"));
    }
}
```

**Comment by BorisOsipov** [comment]
Hi @dacloutier-logmein!

It is regression in Selenium 4.1.0. See issue https://github.com/SeleniumHQ/selenium/issues/10080

Workaround rollback Selenide to 6.0.3\5.25.0

**Comment by dacloutier-logmein** [comment]
thanks for the investigation!
