### ISSUE TITLE
Error using selenide-testng 6.0.3 with maven-surefire-plugin 3.0.0-M5

### ISSUE THREAD

**Issue by alexshebanov** [selenide/selenide#1644]
As `selenide-testng:6.0.3` is built with `org.testng:testng:7.4.0` I'm getting next exception trying to run test via maven:

`There was an error in the forked process'void org.testng.xml.XmlSuite.setParallel(java.lang.String)'
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process'void org.testng.xml.XmlSuite.setParallel(java.lang.String)'`

[Here](https://stackoverflow.com/questions/68143219/maven-surefire-failsafe-testng-7-4-0-parallel-error-void-org-testng-xml-xmlsuit) is a discussion which explains that `maven-surefire-plugin 3.0.0-M5` is incompatible with `org.testng:testng:7.4.0` and it can be used only with older versions of TestNG. This issue should be fixed in `maven-surefire-plugin 3.0.0-M6` but it's still not released yet.

I also tried to define TestNG maven dependency explicitly, with Selenide:
![image](https://user-images.githubusercontent.com/23504650/143288449-3045c7bf-321f-447e-a2b5-641284c564e0.png)

But in this case I'm getting next exception trying to run test via maven:

`Exception in thread "TestNG-test=Surefire test-1" java.lang.IllegalStateException: No webdriver is bound to current thread: 15. You need to call open(url) first.
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getWebDriver(WebDriverThreadLocalContainer.java:138)
	at com.codeborne.selenide.WebDriverRunner.getWebDriver(WebDriverRunner.java:112)
	at common.InitBaseReporter.makeScreenshot(InitBaseReporter.java:66)
	at common.InitBaseReporter.onTestFailure(InitBaseReporter.java:24)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:96)
	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:220)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:832)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)` 

* **Selenide Version**: 6.0.3
* **TestNG Version**: 7.3.0
* **Maven surefire plugin version**: 3.0.0-M5

**Comment by asolntsev** [comment]
@alexshebanov Thank you for sharing the information, but _what can we do with that_?

P.S. You problem `IllegalStateException: No webdriver is bound to current thread` is not caused by TestNG or surefire version. It's a logical error in your code. 

##### Problem:
Your method `common.InitBaseReporter.makeScreenshot` tries to take a screenshot even if browser is not opened. 

##### Solution:
You can add `if (WebDriverRunner.hasWebDriverStarted())` before taking a screenshot.

**Comment by alexshebanov** [comment]
@asolntsev Hello again Andrei! Thanks for your answer!

I've made an investigation and found out that this error is not related to the code. Because when I use `selenide-testng:6.1.1` the driver somehow can't be initialized. Logs:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
Dec 29, 2021 6:38:30 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer getAndCheckWebDriver
INFO: No webdriver is bound to current thread: 1 - let's create a new webdriver
[ERROR] No webdriver is bound to current thread: 1. You need to call open(url) first.
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
```
But if I change the selenide dependency version to `selenide:5.20.0` (and uncomment TestNG dependency) in my pom.xml everything will be fine:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
Dec 29, 2021 6:51:38 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer getAndCheckWebDriver
INFO: No webdriver is bound to current thread: 1 - let's create a new webdriver
Dec 29, 2021 6:51:38 PM com.codeborne.selenide.impl.FileHelper ensureFolderExists
INFO: Creating folder: C:\Work\tests\target\downloads\1640796698354_14440_1
Dec 29, 2021 6:51:38 PM io.github.bonigarcia.wdm.WebDriverManager resolveDriverVersion
INFO: Using chromedriver 96.0.4664.45 (resolved driver for Chrome 96)
Dec 29, 2021 6:51:38 PM io.github.bonigarcia.wdm.WebDriverManager exportDriver
INFO: Exporting webdriver.chrome.driver as C:\Users\ashebanov\.cache\selenium\chromedriver\win32\96.0.4664.45\chromedriver.exe
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 25444
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Dec 29, 2021 6:51:41 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Dec 29, 2021 6:51:41 PM com.codeborne.selenide.webdriver.BrowserResizer adjustBrowserSize
INFO: Set browser size to 1980x960
Dec 29, 2021 6:51:41 PM com.codeborne.selenide.webdriver.WebDriverFactory logBrowserVersion
INFO: BrowserName=chrome Version=96.0.4664.110 Platform=WINDOWS
Dec 29, 2021 6:51:41 PM com.codeborne.selenide.webdriver.WebDriverFactory createWebDriver
INFO: Selenide v. 5.20.0
Dec 29, 2021 6:51:41 PM com.codeborne.selenide.webdriver.WebDriverFactory logSeleniumInfo
INFO: Selenium WebDriver v. 3.141.59 build time: 2018-11-14T08:17:03
Dec 29, 2021 6:51:41 PM com.codeborne.selenide.drivercommands.CreateDriverCommand createDriver
INFO: Create webdriver in current thread 1: ChromeDriver -> ChromeDriver: chrome on WINDOWS (00abbfa6216e27288569969e80cd8cb6)
```
Maybe are there any libraries that can conflict with Selenide 6.x? 

Here is pom.xml I use:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.web.test</groupId>
    <artifactId>test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>bin-test</name>
    <properties>
        <browser>chrome</browser>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven-surefire-plugin.version>3.0.0-M4</maven-surefire-plugin.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <allure.version>2.17.2</allure.version>
        <allure-selenide.version>2.13.6</allure-selenide.version>
        <aspectj.version>1.9.6</aspectj.version>
        <testng.version>7.4.0</testng.version>
        <thread.count>1</thread.count>
        <rerun>true</rerun>
        <selenide-version>6.1.1</selenide-version>
        <rest-assured.version>4.4.0</rest-assured.version>
        <lombok.version>1.18.16</lombok.version>
        <jackson-annotations.version>2.12.0</jackson-annotations.version>
        <env>avm.prod</env>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
            <version>${aspectj.version}</version>
        </dependency>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide-testng</artifactId>
            <version>${selenide-version}</version>
            <scope>compile</scope>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.testng</groupId>-->
<!--            <artifactId>testng</artifactId>-->
<!--            <version>${testng.version}</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>${allure.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-selenide</artifactId>
            <version>${allure-selenide.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>1.7.30</version>
        </dependency>
        <dependency>
            <groupId>com.opencsv</groupId>
            <artifactId>opencsv</artifactId>
            <version>3.7</version>
        </dependency>
        <dependency>
            <scope>compile</scope>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${rest-assured.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.xml.bind</groupId>
                    <artifactId>jaxb-osgi</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-rest-assured</artifactId>
            <version>${allure.version}</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.xml.bind</groupId>
                    <artifactId>jaxb-osgi</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <scope>compile</scope>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>2.10.2</version>
        </dependency>
        <dependency>
            <scope>compile</scope>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson-annotations.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson-annotations.version}</version>
        </dependency>
        <dependency>
            <scope>compile</scope>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson-annotations.version}</version>
        </dependency>
        <dependency>
            <scope>compile</scope>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <version>1.11.792</version>
        </dependency>
        <dependency>
            <groupId>com.browserup</groupId>
            <artifactId>browserup-proxy-core</artifactId>
            <version>2.1.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>regions</artifactId>
            <version>2.16.18</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>sns</artifactId>
            <version>2.16.18</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>5.0.1</version>
        </dependency>

    </dependencies>

    <profiles>
        <profile>
            <id>selenide</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <testResources>
                    <testResource>
                        <directory>src/test/resources</directory>
                    </testResource>
                    <testResource>
                        <directory>src/test/config/${env}</directory>
                        <filtering>true</filtering>
                    </testResource>
                </testResources>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>3.8.1</version>
                        <configuration>
                            <source>${maven.compiler.source}</source>
                            <target>${maven.compiler.target}</target>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>io.qameta.allure</groupId>
                        <artifactId>allure-maven</artifactId>
                        <version>2.10.0</version>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin.version}</version>
                        <configuration>
                            <trimStackTrace>false</trimStackTrace>
                            <properties>
                                <property>
                                    <name>reporter</name>
                                    <value>common.InitBaseReporter</value>
                                </property>
                            </properties>
                            <threadCount>${thread.count}</threadCount>
                            <argLine>
                                -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                            </argLine>
                        </configuration>
                    </plugin>
                    <plugin>
                        <artifactId>maven-resources-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <id>copy-allure-environment</id>
                                <phase>test-compile</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${basedir}/target/allure-results</outputDirectory>
                                    <resources>
                                        <resource>
                                            <filtering>true</filtering>
                                            <directory>src/test/config/${env}</directory>
                                            <includes>
                                                <include>environment.properties</include>
                                            </includes>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
```

**Comment by asolntsev** [comment]
Did you read my [last comment]( https://github.com/selenide/selenide/issues/1644#issuecomment-978238712)? There was the right answer.

**Comment by alexshebanov** [comment]
Hello again, Andrei.
Yes, I tried it immediately, but it didn't help. Block of code with screenshot creation relates to TestNG failure listener and executes after test case failure already.

**Comment by asolntsev** [comment]
@alexshebanov Sorry, I don't understand. Just look at the stack trace, and you will see where `IllegalStateException: No webdriver is bound to current thread` is thrown from.

**Comment by alexshebanov** [comment]
@asolntsev Sorry for getting you confused. Looks like the root cause of the problem is really related to WebDriver initialization.

I've tried to create a simple test class in the project:
```
import com.codeborne.selenide.Selenide;
import common.BaseTest;
import org.testng.annotations.Test;

public class TestClass extends BaseTest {

    @Test(groups = "test123")
    public void test_test() {
        Selenide.open("https://google.com/");
        Selenide.sleep(10000);
    }
}
```

And attempting to run it I get next stacktrace:

```
Dec 30, 2021 1:21:16 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer getAndCheckWebDriver
INFO: No webdriver is bound to current thread: 1 - let's create a new webdriver
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 4.903 s <<< FAILURE! - in TestSuite
[ERROR] TestClass.test_test  Time elapsed: 0.177 s  <<< FAILURE!
java.lang.NoClassDefFoundError: org/openqa/selenium/net/HostIdentifier
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:56)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:170)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:156)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:206)
	at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:68)
	at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:152)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:66)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:30)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:101)
	at com.codeborne.selenide.Selenide.open(Selenide.java:51)
	at TestClass.test_test(TestClass.java:9)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.net.HostIdentifier
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 46 more
```

I've found [similar](https://github.com/SeleniumHQ/selenium/issues/9784) problem but didn't find a solution.
I also tried to create a simple maven project with TestNG, Selenide dependencies only, and maven surefire plugin - everything worked well.
So I guess the problem is probably caused by some dependency conflicts.

**Comment by asolntsev** [comment]
The problem with ClassNotFoundException was already solved in latest Selenium version. Just use latest Selenide 6.1.2

**Comment by alexshebanov** [comment]
Thanks, Andrei! The issue is resolved.
Updating to Selenide 6.1.2 didn't help me, but I found out that issue appeared because of conflict with `browserup-proxy-core` dependency.
