### ISSUE TITLE
Failed to take onFailure screenshot for TestNG parallel tests

### ISSUE THREAD

**Issue by 7vga** [selenide/selenide#1677]
## The problem
Failed to save page source/screenshot to due to UnreachableBrowserException on TestNG tests failure

## Details
Obvious needs: to report failed tests screenshots
After some tools versions upgrade (hard to say, when exactly) this functionality has been broken

## Tell us about your environment
Selenide: 6.1.2
Selenoid: 1.10.7
Selenium: version: '4.1.1', revision: 'e8fcc2cecf'
TestNG: 7.3.0
Os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '15.0.2'
browserVersion: 96.0.4664.45, chrome: chromedriverVersion: 96.0.4664.45

## Code To Reproduce Issue [ Good To Have ]
```

public class BaseTest {
 @BeforeMethod(alwaysRun = true)
    public void browserSetup() throws MalformedURLException {
        Configuration.browser = Config.getBrowserName();
        browserVersion = Config.getBrowserVersion();
        Configuration.browserSize = values.browserResolution();
        Configuration.screenshots = true;
        Configuration.reportsFolder = Config.getScreenshotsPath().toString();
        Configuration.webdriverLogsEnabled = false;
        if (isRunningOnSelenoid) {
            Configuration.remote = "http://localhost:4444/wd/hub";
            Configuration.browserPosition = "0x0";
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("browserName", Config.getBrowserName());
            capabilities.setCapability("browserVersion", browserVersion);
            capabilities.setCapability("acceptInsecureCerts", true);
            capabilities.setCapability("selenoid:options", Map.<String, Object>of(
                    "enableVNC", true,
                    "enableVideo", true,
                    "screenResolution", values.browserResolution() + "x24",
                    "sessionTimeout", "5m"
            ));
        }    
    }
 }

public class TestTest extends BaseTest {
    @Test
    public void check() {
        openMainPage(); // opens some URL
        waitSeconds(2);
        var name = WebDriverRunner.driver().getSessionId();
        var screenshot = Selenide.screenshot(OutputType.BASE64);
        LoggingUtils.logBase64(screenshot, name); // Successfully taken and sent to ReportPortal
        waitSeconds(1);
        Assert.fail("fail"); //<--- Should take another screenshot as com.codeborne.selenide.testng.ScreenShooter listener plugged on TestNG suite level
    }
 }
 
 public class TestTest2 extends BaseTest {
     @Test
     public void check2() {
         openMainPage(); // opens some URL
         waitSeconds(2);
         var name = WebDriverRunner.driver().getSessionId();
         var screenshot = Selenide.screenshot(OutputType.BASE64);
         LoggingUtils.logBase64(screenshot, name); // Successfully taken and sent to ReportPortal
         waitSeconds(1);
         Assert.fail("fail"); //<--- Should take another screenshot as com.codeborne.selenide.testng.ScreenShooter listener plugged on TestNG suite level
     }
  }
```
 
 When running these tests in parallel, they getting following errors:

```
ERROR c.c.s.i.ScreenShotLaboratory - TestNG-test=Debug-1 - Failed to take screenshot to some/path/ui/TestTest/check2/1641283114869.2
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: ..., ip: ..., os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '15.0.2'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [75fbf1f6770d3ea66656532fd0e0c1a6, screenshot {}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 96.0.4664.45, chrome: {chromedriverVersion: 96.0.4664.45 (76e4c1bb2ab46..., userDataDir: /tmp/.com.google.Chrome.TYcCob}, goog:chromeOptions: {debuggerAddress: localhost:41579}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 75fbf1f6770d3ea66656532fd0e0c1a6
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:598)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:333)
	at com.codeborne.selenide.impl.WebdriverPhotographer.takeScreenshot(WebdriverPhotographer.java:13)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.savePageImageToFile(ScreenShotLaboratory.java:268)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.takeScreenShot(ScreenShotLaboratory.java:131)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.lambda$null$10(ScreenShotLaboratory.java:369)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.ifReportsFolderNotNull(ScreenShotLaboratory.java:459)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.lambda$takeScreenshot$11(ScreenShotLaboratory.java:368)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.ifWebDriverStarted(ScreenShotLaboratory.java:449)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.takeScreenshot(ScreenShotLaboratory.java:367)
	at com.codeborne.selenide.Screenshots.saveScreenshotAndPageSource(Screenshots.java:26)
	at com.codeborne.selenide.testng.ScreenShooter.onTestFailure(ScreenShooter.java:34)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:96)
	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:220)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:657)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: net.jodah.failsafe.FailsafeException: java.lang.InterruptedException: sleep interrupted
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:86)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:83)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:110)
	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	... 25 common frames omitted
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:81)
	... 38 common frames omitted
```

**Comment by asolntsev** [comment]
@7vga What exactly means "listener plugged on TestNG suite level"? Can you share a full project sample?

P.S. Most probably listener is called in another thread, or when the browser had been already closed.

**Comment by 7vga** [comment]
Sorry, unable to share all project.
I'm using own runner and it looks like:

private final static List<String> LISTENERS = List.of(
            "com.codeborne.selenide.testng.ScreenShooter",
           .. some others
           );
XmlSuite multiThreadSuite = new XmlSuite();
 multiThreadSuite.setListeners(LISTENERS);
...
TestNG tng = new TestNG();
... then add suites and run

**Comment by 7vga** [comment]
> Most probably listener is called in another thread, or when the browser had been already closed.
Looks exactly like that, but testNG should invoke it for all threads individually (I hope so)

**Comment by asolntsev** [comment]
@7vga I don't need your original project. I need just a sample project I could run.

**Comment by 7vga** [comment]
Got it, will try attach as soon as I could

**Comment by iRaunchy** [comment]
Have the same issue, feels like with TestNG update to 7.5 

`public class ScreenShotListener extends ScreenShooter {

    @Override
    public void onTestFailure(ITestResult result) {
        super.onTestFailure(result);
        try {
            Allure.getLifecycle().addAttachment("Failure", "image/png", "png", Selenide.screenshot(OutputType.BYTES));
        } catch (Throwable ignored) {
            System.out.println("Failed to attach screenshot to report");
        }
    }

}
`
The try block is never executed anymore.

**Comment by iRaunchy** [comment]
https://github.com/allure-framework/allure-java/issues/707
related to this probably, solved my issue by switching to allure test cycly
