### ISSUE TITLE
problem getting webdriver in 6.3.0

### ISSUE THREAD

**Issue by dironel** [selenide/selenide#1726]
```java
com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap.of(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'', error-message=''com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap.of(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'': java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap.of(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'
	at org.openqa.selenium.chrome.AddHasCasting.getAdditionalCommands(AddHasCasting.java:38)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.getExtraCommands(ChromeDriver.java:123)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.<init>(ChromeDriver.java:118)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:106)
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:44)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:109)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:69)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$1(CreateDriverCommand.java:80)
	at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:165)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:53)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:170)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:156)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
```

**Comment by asolntsev** [comment]
@dironel Apparently, you are using an older version of guava dependency.
Please run `gradle dependencies` or `mvn dependency:tree` and you will find what version of guava you are using and where it comes from. 

(the proper version used by Selenide is `31.0.1-jre`)

**Comment by dironel** [comment]
but when i return to selenide 6.2.1 it works well

**Comment by asolntsev** [comment]
@dironel Please fix formatting of your previous comment and put there the **full dependency tree**. 
As far as I see, both Selenide and Selenium depend on `guava 31.0.1-jre`, and the older guava `30.1.1-jre` comes from somewhere else.

**Comment by dironel** [comment]
i see proper dependency in selenide-6.3.0
<dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>31.0.1-jre</version>
      <scope>runtime</scope>
    </dependency>

but after i reload maven project in my dependency tree there is version older
meanwhile i tried to add guava dependecy directly in my own pom and it works with , but if dependency is in selenide pom it is not inherited.

**Comment by dironel** [comment]
i'll ask other team members if anyone knows what can cause trouble

**Comment by asolntsev** [comment]
@dironel It's not always necessary to upload your project. You can just create another simple project that reproduces your problem.

**Comment by dironel** [comment]
hello i found quarkus as a problem, it have guava in its dependencies
