### ISSUE TITLE
Issue with open() when having browserupproxy added

### ISSUE THREAD

**Issue by asdf1988** [selenide/selenide#1745]
## The problem
We have just added browserup-proxy-core to our project. Since then when we execute open() we get an error message.

The hint 

> 	Suppressed: java.lang.IllegalStateException: No webdriver is bound to current thread: 1. You need to call open(url) first.

is not helpful, as we only do open() and already get the issue.

```java
java.lang.NoClassDefFoundError: org/openqa/selenium/net/HostIdentifier
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$1(CreateDriverCommand.java:60)
	at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:165)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:53)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:170)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:156)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
        ...
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:101)
	at com.codeborne.selenide.Selenide.open(Selenide.java:51)
	at AbstractTestWithProxy.login(AbstractTestWithProxy.java:52)
        ...
	Suppressed: java.lang.IllegalStateException: No webdriver is bound to current thread: 1. You need to call open(url) first.
		at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getWebDriver(WebDriverThreadLocalContainer.java:138)
		at com.codeborne.selenide.WebDriverRunner.getWebDriver(WebDriverRunner.java:112)
		at com.codeborne.selenide.impl.StaticDriver.getWebDriver(StaticDriver.java:51)
		at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:40)
		at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:33)
		at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:102)
		at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:106)
		at com.codeborne.selenide.commands.Should.execute(Should.java:30)
		at com.codeborne.selenide.commands.Should.execute(Should.java:14)
		at com.codeborne.selenide.commands.Commands.execute(Commands.java:154)
		at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:131)
		at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:83)
		at jdk.proxy2/jdk.proxy2.$Proxy13.shouldBe(Unknown Source)
		at pageObjects.mavi.MainViewPage.<init>(MainViewPage.java:15)
		at AbstractTestWithProxy.logout(AbstractTestWithProxy.java:67)
```

Dependencies from POM:

```xml
 <dependencies>
        <dependency>
            <groupId>com.github.valfirst.browserup-proxy</groupId>
            <artifactId>browserup-proxy-core</artifactId>
            <version>2.1.4</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>6.3.3</version>
            <scope>compile</scope>
        </dependency>
        <!--<dependency>
            <groupId>com.idera.xray</groupId>
            <artifactId>xray-junit-extensions</artifactId>
            <version>0.4.0</version>
            <scope>test</scope>
        </dependency>-->
    </dependencies>
```

Code from our `AbstractTestWithProxy.java`:

```java
import com.browserup.bup.BrowserUpProxy;
import com.browserup.bup.proxy.CaptureType;
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.Selenide;
import com.codeborne.selenide.WebDriverRunner;
import helpers.SelenideFrameworkConfig;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import pageObjects.LoginPage;
import pageObjects.MainViewPage;
import pageObjects.WelcomeSearchPage;
import static com.codeborne.selenide.Selenide.closeWebDriver;
import static com.codeborne.selenide.Selenide.open;

public abstract class AbstractTestWithProxy {

    public static WelcomeSearchPage welcomeSearchPage;
    public static BrowserUpProxy browserUpProxy;

    public final static SelenideFrameworkConfig config = new SelenideFrameworkConfig()
            .setHost("http://www.google.com")
            .setUserName("<censored>")
            .setPassword("<censored>")
            .setProxyHost("<censored>.de")
            .setProxyPort(8080)
            .setHeadless(false)
            .setSelenideProxyEnabled(true);
            
    @BeforeAll
    public static void setUp() {
        closeWebDriver();
        Configuration.baseUrl = config.getHost();
        Configuration.headless = config.getHeadless();
        Configuration.webdriverLogsEnabled = true;
        Configuration.reportsFolder = "C:/dev/selenideWebDriverLogs/";
        Configuration.proxyEnabled = config.getSelenideProxyEnabled();

        System.setProperty("wdm.proxy", config.getProxyHost().contains("http://") ? config.getProxyHost() : "http://" + config.getProxyHost() + ":" + config.getProxyPort());
    }

    @BeforeEach
    public void login() {
        open("/");
        //welcomeSearchPage = loginPage.setUsername(config.getUserName()).setPassword(config.getPassword()).clickLogin();
    }

    @AfterEach
    public void logout() {
        new MainViewPage().logout().loginButtonShouldBeVisible();
        //List<HarEntry> requests = browserUpProxy.getHar().getLog().getEntries();
    }

    @AfterAll
    public static void tearDown() {
        closeWebDriver();
    }
}
```

## Tell us about your environment
* **Selenide Version**: 6.3.3
* **Chrome**: Version 98.0.4758.102 (Offizieller Build) (64-Bit)
* **OS Version**: Win 10 Enterprise 19042.1466

![image](https://user-images.githubusercontent.com/97292480/156538202-48651780-5c4c-4903-bcbf-386d3e29b2a6.png)

**Comment by asolntsev** [comment]
@asdf1988 Hi, did you try to fix the dependencies? Did it help?

**Comment by rthaku** [comment]
Hi, I had the same issue and it surely did help. Thank you !!
