### ISSUE TITLE
Driver context is not passed to awaitility lib, No webdriver is bound to current thread

### ISSUE THREAD

**Issue by sobolewska** [selenide/selenide#1747]
## The problem

Appium + Selenide + Allure + JUnit

I need to wait for last sync date to change. 
It's a 'XCUIElementTypeStaticText' (Ipad, Appium) type element, and it's value, name and label are just the date in format "M/d/yyyy, h:m a" (e.g. "2/23/2022, 4:23 PM").

I save current timestamp, click to sync, and then I want to wait for current timestamp to be after the previous one.

I wanted to use await() from awaitility lib. But seems that awaitility is not compliant with selenide.
I'm also open to alternative solutions to my problem.

This is the code (simplified):

```
private final SelenideElement lastSync = $(By.xpath("//XCUIElementTypeStaticText[@name='Last Sync']/../XCUIElementTypeStaticText[2]"));

private LocalDateTime getLastSyncTimestamp() {
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("M/d/yyyy, h:m a");
    return LocalDateTime.from(formatter.parse(lastSync.getValue().toString()));
}

public void sync() {
    LocalDateTime beforeSync = getLastSyncTimestamp();
    syncButton.click();
    await().atMost(5, SECONDS).until(() -> getLastSyncTimestamp().isAfter(beforeSync));
}
```

But using await here throws:

```
No webdriver is bound to current thread: 35. You need to call open(url) first.
java.lang.IllegalStateException: No webdriver is bound to current thread: 35. You need to call open(url) first.
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getWebDriver(WebDriverThreadLocalContainer.java:138)
	at com.codeborne.selenide.WebDriverRunner.getWebDriver(WebDriverRunner.java:112)
	at com.codeborne.selenide.impl.StaticDriver.getWebDriver(StaticDriver.java:51)
	at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:40)
	at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:33)
	at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:102)
	at com.codeborne.selenide.commands.GetValue.execute(GetValue.java:17)
	at com.codeborne.selenide.commands.GetValue.execute(GetValue.java:11)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:154)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:131)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:83)
	at jdk.proxy3/jdk.proxy3.$Proxy20.getValue(Unknown Source)
	at com.gsk.firstsfa.components.ipad.HomeOverviewPage.getLastSyncTimestamp(HomeOverviewPage.java:42)
	at com.gsk.firstsfa.components.ipad.HomeOverviewPage.lambda$sync$0(HomeOverviewPage.java:55)
	at org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:99)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:232)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:219)
```

my build.gradle

```
dependencies {
    implementation 'org.slf4j:slf4j-simple:1.7.36'
    implementation 'org.apache.logging.log4j:log4j-api:2.17.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.17.1'
    implementation 'com.codeborne:selenide:6.3.3'
    implementation 'org.apache.commons:commons-lang3:3.12.0'
    implementation 'io.qameta.allure:allure-selenide:2.17.2'
    implementation 'io.qameta.allure:allure-junit5:2.17.2'
    implementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    implementation 'org.junit.jupiter:junit-jupiter-params:5.8.2'
    implementation 'org.aspectj:aspectjweaver:1.9.8' // needed to use @Step annotation
    implementation 'org.apache.httpcomponents:httpclient:4.5.13'
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
    implementation 'com.google.code.gson:gson:2.9.0'
    implementation 'io.appium:java-client:8.0.0-beta2'
    implementation 'org.awaitility:awaitility:4.1.1'
    implementation 'org.awaitility:awaitility-proxy:3.1.6'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
}
```

**Comment by sobolewska** [comment]
I solved it with a workaround for now, but I still want to know how to use awaitility with selenide.

the code:

```
private LocalDateTime getTimestamp(String value) {
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("M/d/yyyy, h:m a");
    return LocalDateTime.from(formatter.parse(value));
}

public void sync() {
    String beforeSync = lastSync.getValue().toString();
    syncButton.click();
    lastSync.shouldNotHave(value(beforeSync));
    assert getTimestamp(lastSync.getValue().toString()).isAfter(getTimestamp(beforeSync));
}
```

**Comment by BorisOsipov** [comment]
@sobolewska Selenide bounds driver instance to thread. Awatility could spawn additional threads to execute condition predicate.

You can use `with().pollInSameThread().await().atMost(1000, MILLISECONDS).until(...);` - it works correctly with selenide.


Better solution will be custom selenide condition.

**Comment by sobolewska** [comment]
@BorisOsipov thanks, that solves my problem.
