### ISSUE TITLE
SessionNotCreatedException  for native app in simulator

### ISSUE THREAD

**Issue by getloud** [selenide/selenide#1776]
## The problem
When I run automation tests in Bitrise I get exception "org.openqa.selenium.SessionNotCreatedException"

## Env
device: simulator iOS 15.4
 machine: Xcode 13.3.x on macOS 12.2
 java: 17 
selenide 6.4.0
 appium 1.22.3
 gradle 7.4 
Node.js: 12.22.11
 NPM: 6.14.16

`[WD Proxy] connect ECONNREFUSED 127.0.0.1:8228
    [debug] [WD Proxy] Matched '/status' to command name 'getStatus'
    [debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8228/status] with no body
    [WD Proxy] connect ECONNREFUSED 127.0.0.1:8228
    [debug] [WD Proxy] Matched '/status' to command name 'getStatus'
    [debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8228/status] with no body
    [WD Proxy] connect ECONNREFUSED 127.0.0.1:8228
com.tunein.mobile.tests.ios.IosBooksAroundFirstTest.beforeTest FAILED
    org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
        at app//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:585)
        at app//io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:225)
        at app//org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
        at app//io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:79)
        at app//io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:87)
        at app//io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:105)
        at app//com.tunein.mobile.appium.driverprovider.IosDriverProvider.createDriver(IosDriverProvider.java:72)
        at app//com.codeborne.selenide.webdriver.DefaultDriverFactory.createInstanceOf(DefaultDriverFactory.java:40)
        at app//com.codeborne.selenide.webdriver.DefaultDriverFactory.create(DefaultDriverFactory.java:29)
        at app//com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:109)
        at app//com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:69)
        at app//com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$1(CreateDriverCommand.java:80)
        at app//com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:165)
        at app//com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:53)
        at app//com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:170)
        at app//com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:156)
        at app//com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
        at app//com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
        at app//com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:206)
        at app//com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:152)
        at app//com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:86)
        at app//com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:97)
        at app//com.codeborne.selenide.Selenide.open(Selenide.java:127)
        at app//com.tunein.mobile.appium.driverprovider.AppiumDriverProvider.getAppiumDriver(AppiumDriverProvider.java:17)
        at app//com.tunein.mobile.tests.BaseTest.beforeTest(BaseTest.java:47)
        at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base@17.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@17.0.2/java.lang.reflect.Method.invoke(Method.java:568)
        at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
        at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
        at app//org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
        at app//org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
        at app//org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:645)
        at app//org.testng.TestRunner.beforeRun(TestRunner.java:634)
        at app//org.testng.TestRunner.run(TestRunner.java:596)
        at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
        at app//org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
        at app//org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
        at app//org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
        at java.base@17.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
        Caused by:
        org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
        Build info: version: '4.1.3', revision: '7b1ebf28ef'
        System info: host: 'vm-osx-xcode-13.3.x-g2.4core-f1bebf53-09bf-4f33-adbf-5726b7ae3a75.local', ip: 'fe80:0:0:0:1807:af7c:e23f:7704%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.2.1', java.version: '17.0.2'
        Driver info: driver.version: SelenideDriver
            at app//io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:130)
            at app//io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
            at app//io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:146)
            at app//io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:180)
            at app//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
            ... 43 more
            Caused by:
            java.lang.reflect.InvocationTargetException
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:126)
                ... 47 more
                Caused by:
                org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
                Build info: version: '4.1.3', revision: '7b1ebf28ef'
                System info: host: 'vm-osx-xcode-13.3.x-g2.4core-f1bebf53-09bf-4f33-adbf-5726b7ae3a75.local', ip: 'fe80:0:0:0:1807:af7c:e23f:7704%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.2.1', java.version: '17.0.2'
                Driver info: driver.version: SelenideDriver
                    at app//org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:72)
                    at app//org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
                    at app//io.appium.java_client.remote.AppiumCommandExecutor.lambda$createSession$0(AppiumCommandExecutor.java:149)
                    at app//org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
                    at app//org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
                    at app//org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
                    at app//io.appium.java_client.remote.AppiumCommandExecutor.lambda$createSession$0(AppiumCommandExecutor.java:149)
                    at app//org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
                    at app//org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:124)
                    at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
                    ... 52 more
                    Caused by:
                    java.util.concurrent.TimeoutException
                        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
                        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
                        at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
                        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:66)
                        ... 61 more`

**Comment by rosolko** [comment]
@getloud It looks like it's wrong project related issue. Here a correct one https://github.com/selenide/selenide-appium/
