### ISSUE TITLE
NoClassDefFoundError when calling open() after adding a WebDriverListener via WebDriverRunner.addListener()

### ISSUE THREAD

**Issue by flange-ipb** [selenide/selenide#1850]
## The problem
After calling `Selenide.open()` I get the following exception:
```
java.lang.NoClassDefFoundError: net/bytebuddy/matcher/ElementMatcher
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.addWebDriverListeners(CreateDriverCommand.java:129)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.addListeners(CreateDriverCommand.java:103)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$1(CreateDriverCommand.java:85)
	at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:165)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:53)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:170)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:156)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:206)
	at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:72)
	at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:152)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:70)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:40)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:109)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:139)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:124)
	at com.codeborne.selenide.Selenide.open(Selenide.java:163)
	at de.ipb_halle.integrationtests.login.LoginTest.before(LoginTest.java:57)
... blabla from JUnit ...
	Suppressed: com.codeborne.selenide.ex.SoftAssertionError: Test If inputs are empty, some validation errors should appear. failed (3 failures)
	java.lang.NoClassDefFoundError: net/bytebuddy/matcher/ElementMatcher
	java.lang.NoClassDefFoundError: net/bytebuddy/matcher/ElementMatcher
	java.lang.NoClassDefFoundError: net/bytebuddy/matcher/ElementMatcher
		at com.codeborne.selenide.logevents.ErrorsCollector.cleanAndGetAssertionError(ErrorsCollector.java:64)
		at com.codeborne.selenide.logevents.ErrorsCollector.cleanAndThrowAssertionError(ErrorsCollector.java:70)
		at com.codeborne.selenide.junit5.SoftAssertsExtension.lambda$afterEach$3(SoftAssertsExtension.java:62)
		at java.util.Optional.ifPresent(Optional.java:159)
		at com.codeborne.selenide.junit5.SoftAssertsExtension.afterEach(SoftAssertsExtension.java:61)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$12(TestMethodTestDescriptor.java:257)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:273)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:273)
		at java.util.ArrayList.forEach(ArrayList.java:1259)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:272)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:256)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:141)
		... 47 more
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.matcher.ElementMatcher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 92 more
```
My LoginTest class can be found [here](https://github.com/ipb-halle/CRIMSy/blob/Integration_Tests/integration-tests/src/test/java/de/ipb_halle/integrationtests/login/LoginTest.java). The error goes away when I include Byte Buddy in the project.

## Details
I nailed the problem down to the addition of a WebDriverListener in my [WebDriverConfig](https://github.com/ipb-halle/CRIMSy/blob/4a6551955ee55013cd1f4881f29c523d09e33eb1/integration-tests/src/test/java/de/ipb_halle/test/WebDriverConfig.java#L62) class, which is executed via the custom JUnit extension SelenideAllExtension. The error goes away when commenting out the line.

## Tell us about your environment
* **Selenide Version**: 6.6.0, the issue persists since version 6.3.0
* **Chrome\Firefox\IE Version**: Chrome 101.0, Firefox 100.0 (browser type/version does not seem to be the matter)
* **Selenoid Docker Image Version**: 1.10.7

## Code To Reproduce Issue [ Good To Have ]
Let me know if you need a minimal reproducer.

**Comment by asolntsev** [comment]
@flange-ipb It was an unexpected finding :) 

I personally never experienced this problem because occasionally I use AssertJ library in all my projects. And AssertJ fetches transitively `byte-buddy` dependency. But your project doesn't use AssertJ, that's why you were getting `NoClassDefFoundError`.

I have released Selenide 6.6.1 with a fix.
