### ISSUE TITLE
Cannot call `Selenide.open()` if `Configuration.reopenBrowserOnFail=false`

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1880]
## The problem
In my mobile test, I set `reopenBrowserOnFail` to `false`. 
Then I want to start the mobile app on simulator, but receive `IllegalStateException`:

```java
Configuration.reopenBrowserOnFail = false;
Selenide.open();  // raises IllegalStateException
```

Initially, the idea of `reopenBrowserOnFail=false` was to avoid **RE-** opening the webdriver. But when `open()` is called for the **first time**, it still has to start the webdriver. 

## Tell us about your environment
* **Selenide Version**: 6.6.5
* **OS Version**: iOS, Android

## Stack trace:

```java
java.lang.IllegalStateException: No webdriver is bound to current thread: 1, and cannot create a new webdriver because reopenBrowserOnFail=false

	at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$1(CreateDriverCommand.java:55)
	at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:165)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:53)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:170)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:156)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:206)
	at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:152)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:89)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:97)
	at com.codeborne.selenide.Selenide.open(Selenide.java:128)
	at com.codeborne.selenide.appium.ios_test_app.CalculatorTest.addNumbers(CalculatorTest.java:24)
```

**Comment by asolntsev** [comment]
done in https://github.com/selenide/selenide/pull/1881
