### ISSUE TITLE
Exception in thread "Dead threads watchdog"

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1942]
## The problem
Sometimes I see the exception in logs (while Selenide tries to close the browser).

## Tell us about your environment
* **Selenide Version**: 6.7.3

```java
Exception in thread "Dead threads watchdog" java.lang.IllegalStateException: Shutdown in progress
	at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:245)
	at com.codeborne.selenide.drivercommands.DisposablesRegistry.cancel(DisposablesRegistry.java:49)
	at com.codeborne.selenide.drivercommands.DisposablesRegistry.unregister(DisposablesRegistry.java:42)
	at com.codeborne.selenide.drivercommands.WebdriversRegistry.unregister(WebdriversRegistry.java:13)
	at com.codeborne.selenide.impl.DeadThreadsWatchdog.closeWebDriver(DeadThreadsWatchdog.java:57)
	at com.codeborne.selenide.impl.DeadThreadsWatchdog.closeUnusedWebdrivers(DeadThreadsWatchdog.java:41)
	at com.codeborne.selenide.impl.DeadThreadsWatchdog.run(DeadThreadsWatchdog.java:27)
```

**Comment by asolntsev** [comment]
fixed in https://github.com/selenide/selenide/pull/1943
