### ISSUE TITLE
Selenide 6.8.1 with Selenium 4.4.0 has NosuchMethod Exception

### ISSUE THREAD

**Issue by peterwkc85** [selenide/selenide#1973]
## The problem
There is no method called `setHeadless` in selenium 4.5. It is renamed to chromium. 

```java
java.lang.NoSuchMethodError: 'org.openqa.selenium.chromium.ChromiumOptions org.openqa.selenium.chrome.ChromeOptions.setHeadless(boolean)'
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.createCapabilities(ChromeDriverFactory.java:59)
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:40)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:109)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:69)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$0(CreateDriverCommand.java:76)
	at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:166)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:52)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:180)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:149)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:220)
	at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:72)
	at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:153)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:70)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:101)
	at com.codeborne.selenide.Selenide.open(Selenide.java:52)
	at com.nicholas.manager.ChromeTestManager.openPage(ChromeTestManager.java:27)
```

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**:  6.8.1
* **Chrome\Firefox\IE Version**:  Chrome
* **Browser Driver Version**:  
* **Selenium Version**:  4.4.0
* **OS Version**:  Window 10

Using TestNG 
## Code To Reproduce Issue [ Good To Have ]

```java
 @BeforeMethod
    public void openPage() {
        open("https:///www.phptravels.net");
    }

@Test
    public void testLogin() {        
    }
```

**Comment by asolntsev** [comment]
@peterwkc85 I don't understand, are you using selenium 4.4.0 or selenium 4.5?

Anyway, the problem is in your dependencies. Please execute `mvn dependency:tree` or `gradle dependencies`, and you will see some conflicts with dependencies versions.

See for more information:
* https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html
* https://selenide.org/2020/11/17/why-proxy-does-not-work-in-selenoid/
