### ISSUE TITLE
How to handle StaleElementReferenceException in Selenide

### ISSUE THREAD

**Issue by shastrisubramaniam** [selenide/selenide#1976]
## The problem

```java
Caused by: StaleElementReferenceException: stale element reference: element is not attached to the page document
```

## Details
using try catch for `StaleElementReferenceException` does not work. Basically I have overlapping polygons and I am trying to filter the polygons so that I can click on them. So obviously the DOM changes.

## Tell us about your environment
Selenide 6.4.0
Chrome Version 105.0.5195.125 (Official Build) (arm64)
chromedriver 105.0.5195.52
Selenium 4.1.3
MacOS Monterey 12.5.1

```java
package tests.admin;

import apex.helpers.table.ApexTable;
import apex.helpers.table.ApexTableHelper;
import com.codeborne.selenide.*;
import datamodels.Customers;
import helpers.YamlHelper;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.admin.AuditLogPageLocators;
import pages.common.HomePage;
import tests.TestBase;
import utils.WaitHelper;
import zephyr.annotations.TestCase;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;

public class AuditLogTest extends TestBase {

    private static final Customers testData = YamlHelper.loadFromYaml("./customers.yaml", Customers.class);
    private ApexTable table;
    String testUser1 = "GPAS Automation";
    String testUser2 = "GPAS StageAuto";

    @BeforeMethod
    public void before() {
        open(tconf.gpasadminAccountSignIn());
    }
 @Test
    @TestCase(id = "HCGPAS-1929")
    public void validateChartDrillDown() {
        final List<String> tableNames = new ArrayList<>();
        step("Login and Navigate to Audit Chart", () -> {
            loginFlow.selectWorkSpace(testData.customers.get(0).login, testData.customers.get(0).password);
            loginFlow.completeLogin("Administrator Portal");
            homePage.openPageByName(HomePage.PageName.AUDITLOG);
            auditPage.auditLogTitle.shouldHave(exactText("Audit Log"), Duration.ofSeconds(60));
            auditPage.searchField.sendKeys(Keys.ARROW_DOWN);
            WaitHelper.waitForAjaxReady();
            auditPage.tableMenu.click();
            WaitHelper.waitForAjaxReady();
            ElementsCollection tableCollection = $$(AuditLogPageLocators.TABLE_NAMES);
            for (int i=0;i < tableCollection.size();i++) {
                tableNames.add("Series: insert; Group: " + tableCollection.get(i).getValue().replaceAll("_"," ") + ";");
            }
            WaitHelper.waitForAjaxReady(60000,200);
            auditPage.chartsTab.click();
        });
        step("Validate Drilldown of Audit Log Chart by Table for Insert", () -> {
            int tableCounter =0;
            WaitHelper.waitForAjaxReady(60000,200);
            while (tableCounter < tableNames.size()) {
                ElementsCollection rectCollection = $$(AuditLogPageLocators.ACTION_BEFORE_HOVER);
                for (SelenideElement e : rectCollection) {
                    e.hover();
                    sleep(1500);
                }
                auditPage.updateAction.click(ClickOptions.usingJavaScript());
                WaitHelper.waitForAjaxReady(60000,200);
                auditPage.deleteAction.click(ClickOptions.usingJavaScript());
                WaitHelper.waitForAjaxReady();
                ElementsCollection polygonCollection = $$(AuditLogPageLocators.POLYGON_BY_TABLE_BEFORE_HOVER);
                WaitHelper.waitForAjaxReady();
                for (SelenideElement e : polygonCollection) {
                    e.hover();
                    sleep(500);
                }
                WaitHelper.waitForAjaxReady();
                SelenideElement polygon = $(By.xpath(String.format(AuditLogPageLocators.POLYGON_BY_TABLE_AFTER_HOVER,tableNames.get(tableCounter))));
                if (polygon.exists() && polygon.getAttribute("aria-label").contains("Value: 0")==false) {
                    int numberOfRecords = Integer.parseInt(polygon.getAttribute("aria-label")
                            .substring(polygon.getAttribute("aria-label").lastIndexOf(":")+1)
                            .replaceAll(";","").replaceAll(" ","")
                            .replaceAll(",","").replaceAll(".Drillable",""));
                    polygon.scrollIntoView("{block: \"end\"}").click();
                    WaitHelper.waitForAjaxReady();
                    uiSoftAssertions.assertThat(Integer.parseInt(auditPage.auditLogResults.text()
                            .replaceAll(",",""))).isEqualTo(numberOfRecords);
                    auditPage.chartsTab.click();
                }
                tableCounter++;
            }
        });
    }
}
```

**Comment by asolntsev** [comment]
@shastrisubramaniam You are complaining that try/catch doesn't work, but I don't see `try` and `catch` in your code. 

P.S. Of course, try/catch works, but apparently you are catching the wrong exception. The word `Caused by:` means that it was not the original exception.

**Comment by shastrisubramaniam** [comment]
After adding try catch like below 

@Test
    @TestCase(id = "HCGPAS-1929")
    public void validateChartDrillDown() {
        final List<String> tableNames = new ArrayList<>();
        step("Login and Navigate to Audit Chart", () -> {
            loginFlow.selectWorkSpace(testData.customers.get(0).login, testData.customers.get(0).password);
            loginFlow.completeLogin("Administrator Portal");
            homePage.openPageByName(HomePage.PageName.AUDITLOG);
            auditPage.auditLogTitle.shouldHave(exactText("Audit Log"), Duration.ofSeconds(60));
            auditPage.searchField.sendKeys(Keys.ARROW_DOWN);
            WaitHelper.waitForAjaxReady();
            auditPage.tableMenu.click();
            WaitHelper.waitForAjaxReady();
            ElementsCollection tableCollection = $$(AuditLogPageLocators.TABLE_NAMES);
            for (int i=0;i < tableCollection.size();i++) {
                tableNames.add("Series: insert; Group: " + tableCollection.get(i).getValue().replaceAll("_"," ") + ";");
            }
            WaitHelper.waitForAjaxReady(60000,200);
            auditPage.chartsTab.click();
        });
        step("Validate Drilldown of Audit Log Chart by Table for Insert", () -> {
            int tableCounter =0;
            WaitHelper.waitForAjaxReady(60000,200);
            while (tableCounter < tableNames.size()) {
                ElementsCollection rectCollection = $$(AuditLogPageLocators.ACTION_BEFORE_HOVER);
                for (SelenideElement e : rectCollection) {
                    e.hover();
                    sleep(1500);
                }
                auditPage.updateAction.click(ClickOptions.usingJavaScript());
                WaitHelper.waitForAjaxReady(60000,200);
                auditPage.deleteAction.click(ClickOptions.usingJavaScript());
                WaitHelper.waitForAjaxReady();
                    ElementsCollection polygonCollection = $$(AuditLogPageLocators.POLYGON_BY_TABLE_BEFORE_HOVER);
                    WaitHelper.waitForAjaxReady();
                    for (SelenideElement e : polygonCollection) {
                        try {
                            e.hover();
                        }
                        catch (StaleElementReferenceException exception) {
                            ElementsCollection polygonCollection1 = $$(AuditLogPageLocators.POLYGON_BY_TABLE_BEFORE_HOVER);
                            WaitHelper.waitForAjaxReady();
                            for (SelenideElement e1 : polygonCollection1) {
                                e1.hover();
                                sleep(500);
                            }
                        }
                        sleep(500);
                    }
                WaitHelper.waitForAjaxReady();
                SelenideElement polygon = $(By.xpath(String.format(AuditLogPageLocators.POLYGON_BY_TABLE_AFTER_HOVER,tableNames.get(tableCounter))));
                if (polygon.exists() && polygon.getAttribute("aria-label").contains("Value: 0")==false) {
                    int numberOfRecords = Integer.parseInt(polygon.getAttribute("aria-label")
                            .substring(polygon.getAttribute("aria-label").lastIndexOf(":")+1)
                            .replaceAll(";","").replaceAll(" ","")
                            .replaceAll(",","").replaceAll(".Drillable",""));
                    polygon.scrollIntoView("{block: \"end\"}").click();
                    WaitHelper.waitForAjaxReady();
                    uiSoftAssertions.assertThat(Integer.parseInt(auditPage.auditLogResults.text()
                            .replaceAll(",",""))).isEqualTo(numberOfRecords);
                    auditPage.chartsTab.click();
                }
                tableCounter++;
            }
        });
    }
}

I still get the below error 

Element not found {By.xpath: //*[local-name()='polygon'][following::span[contains(text(),'Audit Log Chart by Operation')]].snapshot(18 elements)[9]}
Expected: exist
Screenshot: file:/Users/sushastr/IdeaProjects/gpas-portal-ui-test/build/reports/tests/1664641004695.0.png
Page source: file:/Users/sushastr/IdeaProjects/gpas-portal-ui-test/build/reports/tests/1664641004695.0.html
Timeout: 4 s.
Caused by: StaleElementReferenceException: stale element reference: element is not attached to the page document

	at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:89)
	at com.codeborne.selenide.impl.CollectionElement.createElementNotFoundError(CollectionElement.java:63)
	at com.codeborne.selenide.impl.ExceptionWrapper.wrap(ExceptionWrapper.java:32)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:153)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:83)
	at com.sun.proxy.$Proxy33.hover(Unknown Source)
	at tests.admin.AuditLogTest.lambda$validateChartDrillDown$10(AuditLogTest.java:209)
	at io.qameta.allure.Allure.lambda$step$0(Allure.java:113)
	at io.qameta.allure.Allure.lambda$step$1(Allure.java:127)
	at io.qameta.allure.Allure.step(Allure.java:181)
	at io.qameta.allure.Allure.step(Allure.java:125)
	at io.qameta.allure.Allure.step(Allure.java:112)
	at tests.admin.AuditLogTest.validateChartDrillDown(AuditLogTest.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:239)
	at assertions.SoftAssertJListener.run(SoftAssertJListener.java:18)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:253)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:594)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=106.0.5249.91)
For documentation on this error, please visit: https://selenium.dev/exceptions/#stale_element_reference
Build info: version: '4.1.3', revision: '7b1ebf28ef'
System info: host: 'sushastr-mac', ip: '2600:1700:3d90:7050:0:0:0:43%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.5.1', java.version: '11.0.15.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [5781db22453fa6f2eeffcf12e8b73a3e, actions {actions=[org.openqa.selenium.interactions.Sequence@287cd9b2]}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 106.0.5249.91, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: /var/folders/pq/j43ss5tx45v...}, goog:chromeOptions: {debuggerAddress: localhost:61574}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), se:cdp: ws://localhost:61574/devtoo..., se:cdpVersion: 106.0.5249.91, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 5781db22453fa6f2eeffcf12e8b73a3e
	at jdk.internal.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:635)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:656)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:612)
	at com.codeborne.selenide.commands.Hover.execute(Hover.java:32)
	at com.codeborne.selenide.commands.Hover.execute(Hover.java:16)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:154)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:131)
	... 39 more

**Comment by asolntsev** [comment]
@shastrisubramaniam Sorry, but this is a long code that is very-very hard to read and maintain. 
I highly recommend to read [book "Clean Code"](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882) and invest time in refactoring code. 

But my answer remain the same: you are catching a wrong exception.
More details here:
https://selenide.org/2019/12/02/advent-calendar-how-to-abuse-selenide/
