### ISSUE TITLE
Method `Selenide.download()` doesn't work if URL contains credentials

### ISSUE THREAD

**Issue by fuezl** [selenide/selenide#2037]
## The problem
Начиная с selenide 6.10.0 и выше не работает функция Selenide.download().

## Details
В функцию Selenide.download() передаются параметры:
```
url = "http://{selenoid_url}:4444/download/{session_id}/download"
timeoutMs = 60000
```

Трейс ошибки:
```java
org.apache.hc.client5.http.ClientProtocolException: Request URI authority contains deprecated userinfo component
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:173)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at com.codeborne.selenide.impl.DownloadFileWithHttpRequest.executeHttpRequest(DownloadFileWithHttpRequest.java:127)
	at com.codeborne.selenide.impl.DownloadFileWithHttpRequest.download(DownloadFileWithHttpRequest.java:92)
	at com.codeborne.selenide.impl.DownloadFileWithHttpRequest.download(DownloadFileWithHttpRequest.java:85)
	at com.codeborne.selenide.SelenideDriver.download(SelenideDriver.java:459)
	at com.codeborne.selenide.Selenide.download(Selenide.java:919)
```

## Tell us about your environment
* **Selenide Version**: 6.10.1
* **Chrome**: 107
* **Selenoid**: 1.10.9
* **OS Version**: Windows11/Ubuntu 18.04.6

## Code To Reproduce Issue [ Good To Have ]

```kotlin
fun downloadFiles(maxWait: Int = 60000, pingInterval: Int = 1000): Set<File> {
    val sessionId = (getWebDriver() as RemoteWebDriver).sessionId
    val remote = Configuration.remote.replace("/wd/hub","")
    val downloadList = "$remote/download/$sessionId"
    //Открываем список загруженных браузером файлов в новой вкладке и считываем ссылки на файлы
    executeJavaScript<Any>("window.open(arguments[0],true);",downloadList)
    switchToLastTab()
    val fileLinks = `$$`("a").filter(visible)
    //ждем пока появится хоть 1 файл в списке загруженных
    var timer = 0
    while (fileLinks.size == 0 && timer < maxWait) {
        logger.info("ЖДЕМ ЗАГРУЗКУ ФАЙЛОВ $timer/1000 сек.")
        wait(pingInterval)
        timer += pingInterval
        refresh()
    }
    if(fileLinks.size == 0)
        fail("НЕ УДАЛОСЬ ДОЖДАТЬСЯ ЗАГРУЗКИ ФАЙЛА ЗА ${timer/1000} сек.")
    val files: MutableSet<File> = mutableSetOf()
    fileLinks.forEach {
        val name = it.text()
        val downloadLink = "$remote/download/$sessionId/$name"
        logger.info("СКАЧИВАЕТСЯ ФАЙЛ С SELENOID $downloadLink")
        val file = Selenide.download(downloadLink, maxWait.toLong())
        files.add(file)
    }
    switchToFirstTab()
    return files
}
```

**Comment by asolntsev** [comment]
@fuezl While we still need to investigate the exception, I want to mention that you don't really need that `downloadFiles` method. You can remove the whole `downloadFiles` method, and just use Selenide built-in method:

```java
File report = $("#report").download();
```

To make it work, just add dependency `org.selenide:selenide-selenoid:2.3.2` to your project and set `Configuration.fileDownload = FOLDER;`.

See https://github.com/selenide/selenide-selenoid for details.

**Comment by BorisOsipov** [comment]
@asolntsev I am not sure that [selenide-selenoid](https://github.com/selenide/selenide-selenoid) is not affected with this issue. I've added basic auth support to selenide-selenoid, but I am not sure if it will work with a new apache http client

**Comment by asolntsev** [comment]
@fuezl @BorisOsipov Can someone explain how to reproduce the problem? Otherwise, I would close the issue.

**Comment by BorisOsipov** [comment]
@asolntsev 

`Selenide.download("https://admin:admin@the-internet.herokuapp.com/basic_auth");`
