### ISSUE TITLE
Flaky test in Selenide when downloading file on Windows

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#2038]
## The problem
e.g. https://github.com/selenide/selenide/actions/runs/3573568542/jobs/6007775272

```java
FileDownloadToFolderTest > downloadEmptyFile() FAILED
    java.lang.IllegalStateException: Failed to cleanup folder D:\a\selenide\selenide\statics\build\downloads\1669720935384_1000_1
        at com.codeborne.selenide.BrowserDownloadsFolder.cleanupBeforeDownload(BrowserDownloadsFolder.java:31)
        at com.codeborne.selenide.impl.DownloadFileToFolder.clickAndWaitForNewFilesInDownloadsFolder(DownloadFileToFolder.java:77)
        at com.codeborne.selenide.impl.DownloadFileToFolder.lambda$download$0(DownloadFileToFolder.java:58)
        at com.codeborne.selenide.impl.WindowsCloser.runAndCloseArisedWindows(WindowsCloser.java:25)
        at com.codeborne.selenide.impl.DownloadFileToFolder.download(DownloadFileToFolder.java:57)
        at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:67)
        at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:29)
        at com.codeborne.selenide.commands.Commands.execute(Commands.java:157)
        at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:130)
        at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:82)
        at jdk.proxy3/jdk.proxy3.$Proxy37.download(Unknown Source)
        at integration.FileDownloadToFolderTest.downloadEmptyFile(FileDownloadToFolderTest.java:188)

        Caused by:
        org.apache.commons.io.IOExceptionList: D:\a\selenide\selenide\statics\build\downloads\1669720935384_1000_1
            at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:331)
            at com.codeborne.selenide.BrowserDownloadsFolder.cleanupBeforeDownload(BrowserDownloadsFolder.java:27)
            ... 11 more

            Caused by:
            java.io.IOException: Cannot delete file: D:\a\selenide\selenide\statics\build\downloads\1669720935384_1000_1\hello_world.txt.crdownload
                at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1344)
                at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:324)
                ... 12 more

                Caused by:
                java.nio.file.FileSystemException: D:\a\selenide\selenide\statics\build\downloads\1669720935384_1000_1\hello_world.txt.crdownload: The process cannot access the file because it is being used by another process
                    at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
                    at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
                    at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
                    at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
                    at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
                    at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
                    at org.apache.commons.io.file.PathUtils.deleteFile(PathUtils.java:487)
                    at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:392)
                    at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1341)
                    ... 13 more
```

## Tell us about your environment
* **Selenide Version**: 6.10.1

**Comment by BorisOsipov** [comment]
addressed in https://github.com/selenide/selenide/pull/2076
