### ISSUE TITLE
Users should be able to use Java 11+ HttpClient instead of NettyClient

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#2215]
## The problem
Users might want to start using Java 11+ HttpClient provided by Selenium.
But Selenide overrides system property `webdriver.http.factory`, this forcing users to always use NettyClient.

We need to make Selenide a bit smarter: if system property `webdriver.http.factory` is already set, then Selenide should NOT rewrite it.

## Tell us about your environment
* **Selenide Version**: 6.12.3

## Code To Reproduce Issue

See https://github.com/selenide/selenide/pull/1972/files:

```groovy
implementation("org.seleniumhq.selenium:selenium-http-jdk-client:$seleniumVersion")
```

```java
System.setProperty("webdriver.http.factory", "jdk-http-client");
```

**Comment by plagov** [comment]
@asolntsev, our test setup is to run UI tests in a docker image with Testcontainers. After enabling this feature (JDK HTTP client), it fails to create a screenshot with the below stack trace. I'm using the `com.codeborne:selenide-full-screenshot` plugin for screenshots. Without the JDK HTTP client, it works again (but fails to make the full-page screenshot).

I'm not sure if it's the Selenide issue or Selenium or JDK HTTP client. But I will leave it here, just for records.

```
10:39:27.155 WARN  main [o.o.s.devtools.CdpVersionFinder] - Unable to find an exact match for CDP version 111, so returning the closest version found: 110
10:39:37.181 ERROR main [s.i.b.BrowserConfigurationSteps] - Failed to perform post-failure tasks
java.util.concurrent.CompletionException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:512)
	at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:459)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:386)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	... 6 more
Caused by: java.net.ConnectException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:513)
	... 10 more
```

**Comment by plagov** [comment]
I made it work in the end **with** JDK HTTP client and **without** the `com.codeborne:selenide-full-screenshot` plugin. Replaced it with https://github.com/assertthat/selenium-shutterbug
