### ISSUE TITLE
Wrong error message if using annotations for elements

### ISSUE THREAD

**Issue by rosolko** [selenide/selenide#2293]
Trying to search element using annotation with some invalid locator:
```java
public class Page extend BasePage {
    @AndroidFindBy(id = "search_button")
    private SelenideElement searchButton;
}
```
And trying to access element in test using getter:
```java
public class ClassWithTests {
    private final Page page = new Page();
    
    @Test
    public void someTest() {
        page.getSearchButton().click();
    }
}
```

Got an error:
```java
Element should be visible {NoSuchElementException: Can't locate an element by this strategy: Locator map:}
Element: 'NoSuchElementException: Can't locate an element by this strategy: Locator map:'
Screenshot: file:/.../build/reports/tests/1499844311539.1.png
Timeout: 4 s.
Caused by: NoSuchElementException: Can't locate an element by this strategy: Locator map:
    at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:66)
    at com.codeborne.selenide.commands.Should.should(Should.java:35)
    at com.codeborne.selenide.commands.Should.execute(Should.java:29)
    at com.codeborne.selenide.commands.Should.execute(Should.java:12)
    at com.codeborne.selenide.commands.Commands.execute(Commands.java:143)
    at ...
```

But some there ina a logs I can find need message:
```java
Caused by: org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: Locator map: 
- native content: "By.chained({By.id: formula1})" 
- html content: "by id or name "result"
```

**Comment by asolntsev** [comment]
@rosolko Is this problem still actual? I could not reproduce it...
