### ISSUE TITLE
docker deploy  springboot + selenide ,  start-up failure

### ISSUE THREAD

**Issue by huangwenyi10** [selenide/selenide#2321]
hello ,

I use docker deploy my project (springboot + selenide) , and have some exception: 

```java

2023-06-02 11:28:18.285 ERROR 1 --- [nio-8000-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Host info: host: 'ebi-rpa-78d8586f45-g2cvx', ip: '10.42.6.201'] with root cause

.....

org.openqa.selenium.WebDriverException: Timed out waiting for driver process to start.
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.6.1.el7.x86_64', java.version: '1.8.0_212'
Driver info: driver.version: SelenideDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:208) ~[selenium-remote-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:114) ~[selenium-remote-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543) ~[selenium-remote-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229) ~[selenium-remote-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157) ~[selenium-remote-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101) ~[selenium-chromium-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88) ~[selenium-chrome-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84) ~[selenium-chrome-driver-4.9.0.jar!/:na]
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:42) ~[selenide-core-

	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
```

### Tell us about your environment

Selenide Version: 6.13.1
Deploy Env: Docker
Selenium Version: 4.9.0
JDK: 1.8

**Comment by asolntsev** [comment]
@huangwenyi10 Can you provide some reproducible example? 
The best solution if you can create a sample github project that others can run and reproduce the problem.

**Comment by huangwenyi10** [comment]
> @huangwenyi10 Can you provide some reproducible example? The best solution if you can create a sample github project that others can run and reproduce the problem.

I would like to ask a question, my Docker image does not have any Google drivers installed. Can the program execute normally?

My project is very simple, just a springboot project and adding Selenium dependencies ， I used dockerfile to package the project into an image and started it. I did not install any Google drivers or call remote Google browsers

pom.xml 如下
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.12</version>
        <relativePath/> 
    </parent>
    <groupId>com.example</groupId>
    <artifactId>ebi-rpa</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>ebi-rpa</name>
    <description>ebi-rpa</description>
    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.target>8</maven.compiler.target>
        <maven.compiler.source>8</maven.compiler.source>
        <junit.version>5.9.3</junit.version>
        <selenium.version>4.9.0</selenium.version>
        <httpclient5.version>5.2.1</httpclient5.version>

    </properties>
    <dependencies>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <version>3.6.1</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.8.19</version>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>7.0.0.jre8</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>6.13.1</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>3.3.2</version>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.7</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>prod</id>
            <properties>
                <build.profile.id>prod</build.profile.id>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

`

Controller code：

`

package com.anta.data.rpa.demo.controller;

import com.alibaba.excel.EasyExcel;
import com.anta.data.rpa.demo.dto.DemoData;
import com.anta.data.rpa.demo.entity.VrpaTbToken;
import com.anta.data.rpa.demo.listener.DemoDataListener;
import com.anta.data.rpa.demo.mapper.SysUserRoleMapper;
import com.anta.data.rpa.demo.mapper.VrpaTbTokenMapper;
import com.baomidou.dynamic.datasource.annotation.DS;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.codeborne.selenide.SelenideElement;
import com.codeborne.selenide.WebDriverRunner;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.annotation.Resource;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;

import static com.codeborne.selenide.Selenide.*;


@RestController
public class DemoController {

    public SelenideElement baiduInput = $x("//*[@id=\"kw\"]");
    public SelenideElement searchInput = $x("//*[@id=\"su\"]");



    @GetMapping("/test")
    public void test() {
        open("https://baidu.com");
        baiduInput.setValue("hwy");
        searchInput.click();
        sleep(5000);
        System.out.println("hello selenide!!!");
        open("");
    }

}

`

When I use a browser to access the address: http://localhost:8080/test ， and log：

`
2023-07-13 18:19:33.715  INFO 1 --- [nio-8000-exec-7] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-07-13 18:19:33.716  INFO 1 --- [nio-8000-exec-7] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-07-13 18:19:33.718  INFO 1 --- [nio-8000-exec-7] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2023-07-13 18:19:39.149  INFO 1 --- [nio-8000-exec-8] c.c.s.i.WebDriverThreadLocalContainer    : No webdriver is bound to current thread: 40 - let's create a new webdriver
2023-07-13 18:19:39.180  INFO 1 --- [nio-8000-exec-8] com.codeborne.selenide.impl.FileHelper   : Creating folder: /root/build/downloads/1689243579178_1_40
2023-07-13 18:19:45.088  INFO 1 --- [nio-8000-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x000xfc0x010x000x000xf80x030x030xdf|0xd10x940x1a0x970x85]0xcc0xd40xee0xbeN0xbd0xada0xd60xa4|0x940xdf0xbf0xd30xd1G0xb8E&h0xe60xfeS ]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.75.jar!/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
2023-07-13 18:20:10.511  INFO 1 --- [nio-8000-exec-8] i.g.bonigarcia.wdm.WebDriverManager      : Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
2023-07-13 18:20:11.132  INFO 1 --- [nio-8000-exec-8] i.g.bonigarcia.wdm.online.Downloader     : Downloading https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
2023-07-13 18:20:11.680  INFO 1 --- [nio-8000-exec-8] i.g.bonigarcia.wdm.online.Downloader     : Extracting driver from compressed file chromedriver_linux64.zip
2023-07-13 18:20:11.808  INFO 1 --- [nio-8000-exec-8] i.g.bonigarcia.wdm.WebDriverManager      : Exporting webdriver.chrome.driver as /root/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver
2023-07-13 18:20:12.094  INFO 1 --- [nio-8000-exec-8] c.c.s.w.SelenideNettyClientFactory       : Changed readTimeout from PT3M to PT1M30S
2023-07-13 18:20:32.789 ERROR 1 --- [nio-8000-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Host info: host: 'ebi-rpa-7fdd7968bd-ptzdw', ip: '10.42.10.240'] with root cause
org.openqa.selenium.WebDriverException: Timed out waiting for driver process to start.
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.6.1.el7.x86_64', java.version: '1.8.0_212'
Driver info: driver.version: SelenideDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:208) ~[selenium-remote-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:114) ~[selenium-remote-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543) ~[selenium-remote-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229) ~[selenium-remote-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157) ~[selenium-remote-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101) ~[selenium-chromium-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88) ~[selenium-chrome-driver-4.9.0.jar!/:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84) ~[selenium-chrome-driver-4.9.0.jar!/:na]
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:42) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:123) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:67) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$0(CreateDriverCommand.java:76) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:118) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:52) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:202) ~[selenide-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createAndRegisterDriver(WebDriverThreadLocalContainer.java:186) ~[selenide-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:155) ~[selenide-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130) ~[selenide-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65) ~[selenide-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:220) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:72) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:105) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:70) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:101) ~[selenide-core-6.13.1.jar!/:6.13.1]
	at com.codeborne.selenide.Selenide.open(Selenide.java:53) ~[selenide-6.13.1.jar!/:6.13.1]
	at com.anta.data.rpa.demo.controller.DemoController.test$original$SV4uPOMA(DemoController.java:43) ~[classes!/:0.0.1-SNAPSHOT]
	at com.anta.data.rpa.demo.controller.DemoController.test$original$SV4uPOMA$accessor$ayvqHaaj(DemoController.java) ~[classes!/:0.0.1-SNAPSHOT]
	at com.anta.data.rpa.demo.controller.DemoController$auxiliary$tjzOvb1M.call(Unknown Source) ~[classes!/:0.0.1-SNAPSHOT]
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86) [skywalking-agent.jar:8.1.0]
	at com.anta.data.rpa.demo.controller.DemoController.test(DemoController.java) ~[classes!/:0.0.1-SNAPSHOT]
	at com.anta.data.rpa.demo.controller.DemoController$$FastClassBySpringCGLIB$$5cc44d2e.invoke(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at com.anta.data.rpa.demo.controller.DemoController$$EnhancerBySpringCGLIB$$dc7c06dc.test(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.27.jar!/:5.3.27]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.27.jar!/:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.27.jar!/:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.27.jar!/:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.27.jar!/:5.3.27]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.27.jar!/:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.27.jar!/:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.27.jar!/:5.3.27]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.27.jar!/:5.3.27]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.27.jar!/:5.3.27]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.27.jar!/:5.3.27]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-9.0.75.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.27.jar!/:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar!/:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.27.jar!/:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar!/:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.27.jar!/:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar!/:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.StandardHostValve.invoke$original$HlRHYIyh(StandardHostValve.java:130) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.StandardHostValve.invoke$original$HlRHYIyh$accessor$dM59dUhs(StandardHostValve.java) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.StandardHostValve$auxiliary$eg60IOgB.call(Unknown Source) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86) [skywalking-agent.jar:8.1.0]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:768) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.75.jar!/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.75.jar!/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
`

**Comment by asolntsev** [comment]
@huangwenyi10 Can you please create a project on github, so we could just `git clone` and `mvn test`?
If you want other to help you - make reproducing the problem really easy.

P.S. The problem might be caused by confict between dependency versions. Execute `mvn dependency:tree` and check versions of `selenium-*jar` files.

**Comment by asolntsev** [comment]
@huangwenyi10 Anyway, why are you trying to run test from controller?
It's not a normal way. People write tests in `*Test.java` files and run them with `mvn test` or `gradle test`. People don't usually run tests from controllers.

**Comment by fengli-cn** [comment]
问题解决了嘛，我也有同样的问题，可以加下我wx:  17378191593
