### ISSUE TITLE
SoftAsserts stack trace on every error

### ISSUE THREAD

**Issue by Sourcekot** [selenide/selenide#2350]
## The problem
I'm not seeing a stack trace for each error using SoftAsserts. I know that this should already be implemented (#1543, #1545) but I can't get it to work. When using SoftAsserts I'm only seeing one stack trace at the end after all error messages and that stack trace is quite useless.

## Details
Here is an example of how the error message is currently looking:

```
com.codeborne.selenide.ex.SoftAssertionError: Test TestName failed (2 failures)
	com.codeborne.selenide.ex.ElementNotFound: Element not found {someXPath}
Expected: exist
Screenshot: file:/path/to/project/build/reports/tests/1687188619895.0.png
Page source: file:/path/to/project/build/reports/tests/1687188619895.0.html
Timeout: 4 s.
Caused by: NoSuchElementException: Unable to locate element: someXPath]
	com.codeborne.selenide.ex.ElementNotFound: Element not found {By.id: someId/By.xpath: someXPath}
Expected: exist
Screenshot: file:/path/to/project/build/reports/tests/1687188650562.1.png
Page source: file:/path/to/project/build/reports/tests/1687188650562.1.html
Timeout: 4 s.
Caused by: NoSuchElementException: Unable to locate element: someXPath]

	at com.codeborne.selenide.logevents.ErrorsCollector.cleanAndGetAssertionError(ErrorsCollector.java:64)
	at com.codeborne.selenide.testng.SoftAsserts.failIfErrors(SoftAsserts.java:91)
	at com.codeborne.selenide.testng.SoftAsserts.onTestFailure(SoftAsserts.java:31)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:96)
	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:656)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

What I want to have is a stack trace after the "Caused by: ..." line of each error.
I am using Selenide with TestNG and I've added the `@Listeners({SoftAsserts.class})` listener to my test class and set `Configuration.assertionMode = AssertionMode.SOFT` in the `@BeforeClass` method.
Additionally I'm doing some checks that can't be done through Selenide using TestNGs SoftAssertion (org.testng.asserts.SoftAssert). I'm setting this object up in the `@BeforeMethod` and checking for errors at the end of the `@Test` method using .assertAll(). But this TestNG SoftAssertion can be ignored as the problem is also present if I remove these checks.

## Tell us about your environment
* **Selenide Version**:  6.15.0
* **Chrome\Firefox\IE Version**: Firefox 114.0.1
* **OS Version**: Microsoft Windows 10 Pro, 10.0.19044 Build 19044

**Comment by asolntsev** [comment]
@Sourcekot I am not sure it's a good idea. It will generate too long stack traces that are hard to read. 
But anyway, I found an easy way to do it. Will do in next release.
