### ISSUE TITLE
`$$.shouldHave(texts)` method doesn't support `tspans` in SVG

### ISSUE THREAD

**Issue by ben-nc2** [selenide/selenide#2377]
## The problem
After upgrading from 6.15.0 to 6.16.0 to benefit from the speedup of collection assertions we have encountered an issue with our existing tests that use a tspan element.

## Details
When calling `.shouldHave(CollectionCondition.exactTextsCaseSensitive(texts)` against a collection of svg `tspan` elements we now get errors as tspan doesn't have an innerText attribute. Using the one by one method calling `element.getText()` in the past handled this fine. This appears to be due to a tspan webelement being a XML node rather than an HTML node.

This is the error thrown
```
Step failed
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
	at com.codeborne.selenide.impl.Html.reduceSpaces(Html.java:39)
	at com.codeborne.selenide.impl.Html.equalsCaseSensitive(Html.java:35)
	at com.codeborne.selenide.collections.ExactTextsCaseSensitive.check(ExactTextsCaseSensitive.java:22)
	at com.codeborne.selenide.collections.ExactTexts.check(ExactTexts.java:53)
	at com.codeborne.selenide.CollectionCondition.check(CollectionCondition.java:63)
	at com.codeborne.selenide.ElementsCollection.waitUntil(ElementsCollection.java:172)
	at com.codeborne.selenide.ElementsCollection.should(ElementsCollection.java:145)
	at com.codeborne.selenide.ElementsCollection.shouldHave(ElementsCollection.java:119)
```

## Tell us about your environment
* **Selenide Version**: 6.16.0
* **Chrome\Firefox\IE Version**:  114.0.5735.199
* **Browser Driver Version**:
* **Selenide-Appium Version**:
* **IOS\Android\WEB version**:
* **Selenium Version**: 
* **OS Version**: Windows 10

## Code To Reproduce Issue
```java
Selenide.$$(".n2_top-distributor-chart svg .c3-axis-x tspan").shouldHave(CollectionCondition.exactTextsCaseSensitive(texts));
```

I also tested this by calling the following against all the tspans in my page in the Chrome dev console

Calling
```js
Array.from(document.getElementsByTagName('tspan')).map(el => el.innerText)
```
results in an array full of undefined elements

Calling
```js
Array.from(document.getElementsByTagName('tspan')).map(el => el.textContent)
```
results in an array of text values for the tspans.

**Comment by asolntsev** [comment]
@ben-nc2 Thank you for reporting, will fix it asap. Can you bring some example of such a site?

**Comment by ben-nc2** [comment]
@asolntsev This site should enable you to run the javascript code samples I provided against it in chrome console https://vanseodesign.com/web-design/svg-text-tspan-element/

**Comment by ben-nc2** [comment]
Have upgraded and all working smoothly and has brought our overall runtimes down as well which is great, thanks!

**Comment by asolntsev** [comment]
@ben-nc2 glad to read it. Thank you for the feedback @
