### ISSUE TITLE
[Chrome-115]-Failing to open chrome browser

### ISSUE THREAD

**Issue by natraj04** [selenide/selenide#2402]
## The problem
On chrome version 115, open(url) is failing

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment

* **Chrome**: 115.0.5790.114
* **Browser Driver Version**:
* **OS Version**: mac m1 13.2.1

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

## Console log:

[TestNG-test=Web test-1] INFO com.codeborne.selenide.impl.Plugins - Using implementation of com.codeborne.selenide.impl.PageSourceExtractor: com.codeborne.selenide.appium.AppiumScreenSourceExtractor
[TestNG-test=Web test-1] INFO com.codeborne.selenide.impl.Plugins - Using implementation of com.codeborne.selenide.impl.PageObjectFactory: com.codeborne.selenide.appium.SelenideAppiumPageFactory
[TestNG-test=Web test-1] INFO com.codeborne.selenide.impl.WebDriverThreadLocalContainer - No webdriver is bound to current thread: 24 - let's create a new webdriver
[TestNG-test=Web test-1] INFO com.codeborne.selenide.impl.FileHelper - Creating folder: /Users/nn/Documents/Automation/rewaa/rewaatech-test-automation/build/downloads/1690968369571_44071_24
[TestNG-test=Web test-1] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Error reading commands.properties, using local instead
[TestNG-test=Web test-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 115.0.5790.102 (resolved driver for Chrome 115)
[TestNG-test=Web test-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[TestNG-test=Web test-1] INFO io.github.bonigarcia.wdm.online.Downloader - Downloading https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/mac-arm64/chromedriver-mac-arm64.zip
[TestNG-test=Web test-1] INFO io.github.bonigarcia.wdm.online.Downloader - Extracting driver from compressed file chromedriver-mac-arm64.zip
[TestNG-test=Web test-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /Users/nn/.cache/selenium/chromedriver/mac-arm64/115.0.5790.102/chromedriver
[TestNG-test=Web test-1] INFO org.testng.internal.Utils - Failed to invoke configuration method com.rewaatech.utility.library.BaseTest.setUp:Receiver class org.openqa.selenium.chrome.ChromeDriverService$Builder does not define or inherit an implementation of the resolved method 'abstract java.io.File findDefaultExecutable()' of abstract class org.openqa.selenium.remote.service.DriverService$Builder.

java.lang.AbstractMethodError: Receiver class org.openqa.selenium.chrome.ChromeDriverService$Builder does not define or inherit an implementation of the resolved method 'abstract java.io.File findDefaultExecutable()' of abstract class org.openqa.selenium.remote.service.DriverService$Builder.

	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:456)
	at com.codeborne.selenide.webdriver.AbstractDriverFactory.withLog(AbstractDriverFactory.java:52)
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.buildService(ChromeDriverFactory.java:48)
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:42)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:123)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:67)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$0(CreateDriverCommand.java:76)
	at com.codeborne.selenide.logevents.SelenideLogger.wrap(SelenideLogger.java:133)
	at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:113)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:52)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:202)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createAndRegisterDriver(WebDriverThreadLocalContainer.java:186)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:155)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:220)
	at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:71)
	at com.codeborne.selenide.logevents.SelenideLogger.lambda$run$0(SelenideLogger.java:105)
	at com.codeborne.selenide.logevents.SelenideLogger.wrap(SelenideLogger.java:133)
	at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:104)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:69)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:101)
	at com.codeborne.selenide.Selenide.open(Selenide.java:53)
	at com.rewaatech.utility.library.BaseTest.launchApplication(BaseTest.java:286)
	
## Probable cause
I think this issue is with chrome 115 and selenium latest release has a fix for this

**Comment by natraj04** [comment]
Bumping the selenium version to 4.11 or changing the chrome driver download path might fixed
