### ISSUE TITLE
After updating to Selenide 6.17.0 all SoftAsserts in TestNG have stopped working

### ISSUE THREAD

**Issue by art1988** [selenide/selenide#2412]
Hi,

I have the following xml suite file:

```
<suite name = "Suite #1" configfailurepolicy="continue">
    <test name = "Know my IP test">
        <classes>
            <class name="tests.KnowMyIP"/>
        </classes>
    </test>

    <test name="Check PDF content">
        <classes>
            <class name="tests.PDFContentTest"/>
        </classes>
    </test>
</suite>
```

And I have GeneralTest class with SoftAsserts annotation

```
@Listeners({SoftAsserts.class})
public class GeneralTest
{
...
```

And my KnowMyIP  looks like this:
```
public class KnowMyIP extends GeneralTest
{
...
```

After running my suite I got:
```
java.lang.NoSuchMethodError: 'java.lang.AssertionError com.codeborne.selenide.logevents.ErrorsCollector.cleanAndGetAssertionError(java.lang.String, java.lang.Throwable)'

	at com.codeborne.selenide.testng.SoftAsserts.failIfErrors(SoftAsserts.java:91)
	at com.codeborne.selenide.testng.SoftAsserts.onTestSuccess(SoftAsserts.java:41)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1690)
	.....
```

Selenide 6.15.0 didn't have such problem.

I use Java v.8
TestNG v.6.9.8

**Comment by art1988** [comment]
@asolntsev

**Comment by art1988** [comment]
@asolntsev

**Comment by asolntsev** [comment]
Seems like problem with versions.
Please run "man dependency:tree" or "Gradle dependencies".

**Comment by art1988** [comment]
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< org.example:GeoIPExample >----------------------
[INFO] Building GeoIPExample 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ GeoIPExample ---
[INFO] org.example:GeoIPExample:jar:1.0-SNAPSHOT
[INFO] +- org.testng:testng:jar:6.9.8:compile
[INFO] |  +- org.beanshell:bsh:jar:2.0b4:compile
[INFO] |  \- com.beust:jcommander:jar:1.48:compile
[INFO] +- com.codeborne:selenide:jar:6.15.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-java:jar:4.9.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-api:jar:4.9.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:4.9.1:compile
[INFO] |  |  |  +- com.google.auto.service:auto-service-annotations:jar:1.0.1:compile
[INFO] |  |  |  +- com.google.auto.service:auto-service:jar:1.0.1:compile
[INFO] |  |  |  |  \- com.google.auto:auto-common:jar:1.2:compile
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-chromium-driver:jar:4.9.1:compile
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-json:jar:4.9.1:compile
[INFO] |  |  |  \- org.seleniumhq.selenium:selenium-manager:jar:4.9.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v111:jar:4.9.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v112:jar:4.9.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v113:jar:4.9.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v85:jar:4.9.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:4.9.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:4.9.1:compile
[INFO] |  |  |  \- org.seleniumhq.selenium:selenium-http:jar:4.9.1:compile
[INFO] |  |  |     \- dev.failsafe:failsafe:jar:3.3.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:4.9.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:4.9.1:compile
[INFO] |  |  |  +- io.netty:netty-buffer:jar:4.1.91.Final:compile
[INFO] |  |  |  +- io.netty:netty-codec-http:jar:4.1.91.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-codec:jar:4.1.91.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-handler:jar:4.1.91.Final:compile
[INFO] |  |  |  +- io.netty:netty-common:jar:4.1.91.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-classes-epoll:jar:4.1.91.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-classes-kqueue:jar:4.1.91.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-native-epoll:jar:4.1.91.Final:linux-x86_64
[INFO] |  |  |  +- io.netty:netty-transport-native-kqueue:jar:4.1.91.Final:osx-x86_64
[INFO] |  |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.91.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport:jar:4.1.91.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-resolver:jar:4.1.91.Final:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-api:jar:1.25.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-context:jar:1.25.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-exporter-logging:jar:1.25.0:compile
[INFO] |  |  |  |  +- io.opentelemetry:opentelemetry-sdk-metrics:jar:1.25.0:compile
[INFO] |  |  |  |  \- io.opentelemetry:opentelemetry-sdk-logs:jar:1.25.0-alpha:compile
[INFO] |  |  |  |     +- io.opentelemetry:opentelemetry-api-logs:jar:1.25.0-alpha:compile
[INFO] |  |  |  |     \- io.opentelemetry:opentelemetry-api-events:jar:1.25.0-alpha:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-common:jar:1.25.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:jar:1.25.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:jar:1.25.0-alpha:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-trace:jar:1.25.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk:jar:1.25.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-semconv:jar:1.25.0-alpha:compile
[INFO] |  |  |  +- io.ous:jtoml:jar:2.0.0:compile
[INFO] |  |  |  +- net.bytebuddy:byte-buddy:jar:1.14.4:compile
[INFO] |  |  |  +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  |  |  \- org.asynchttpclient:async-http-client:jar:2.12.3:compile
[INFO] |  |  |     +- org.asynchttpclient:async-http-client-netty-utils:jar:2.12.3:compile
[INFO] |  |  |     +- io.netty:netty-codec-socks:jar:4.1.60.Final:compile
[INFO] |  |  |     +- io.netty:netty-handler-proxy:jar:4.1.60.Final:compile
[INFO] |  |  |     +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.60.Final:compile
[INFO] |  |  |     +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.60.Final:compile
[INFO] |  |  |     +- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  |     +- com.typesafe.netty:netty-reactive-streams:jar:2.0.4:compile
[INFO] |  |  |     \- com.sun.activation:jakarta.activation:jar:1.2.2:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:4.9.1:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-support:jar:4.9.1:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:2.0.7:compile
[INFO] |  +- com.codeborne:selenide-core:jar:6.15.0:compile
[INFO] |  |  +- org.opentest4j:opentest4j:jar:1.2.0:compile
[INFO] |  |  +- io.github.bonigarcia:webdrivermanager:jar:5.3.3:compile
[INFO] |  |  |  +- com.google.code.gson:gson:jar:2.10.1:compile
[INFO] |  |  |  \- org.brotli:dec:jar:0.1.2:compile
[INFO] |  |  +- org.apache.commons:commons-compress:jar:1.23.0:runtime
[INFO] |  |  \- org.apache.httpcomponents.client5:httpclient5:jar:5.2.1:runtime
[INFO] |  |     +- org.apache.httpcomponents.core5:httpcore5:jar:5.2:runtime
[INFO] |  |     \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2:runtime
[INFO] |  +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.11.0:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] |  \- commons-io:commons-io:jar:2.12.0:runtime
[INFO] +- com.codeborne:geoip:jar:1.4:compile
[INFO] +- io.qameta.allure:allure-selenide:jar:2.22.1:compile
[INFO] |  \- io.qameta.allure:allure-java-commons:jar:2.22.1:compile
[INFO] |     \- io.qameta.allure:allure-model:jar:2.22.1:compile
[INFO] +- io.qameta.allure:allure-testng:jar:2.22.1:compile
[INFO] |  \- io.qameta.allure:allure-test-filter:jar:2.22.1:runtime
[INFO] +- com.codeborne:pdf-test:jar:1.8.1:compile
[INFO] |  +- org.apache.pdfbox:pdfbox:jar:2.0.27:runtime
[INFO] |  |  +- org.apache.pdfbox:fontbox:jar:2.0.27:runtime
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:runtime
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:runtime
[INFO] |  \- org.assertj:assertj-core:jar:3.23.1:runtime
[INFO] +- com.codeborne:selenide-testng:jar:6.15.0:compile
[INFO] \- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.870 s
[INFO] Finished at: 2023-08-12T15:50:29-04:00
[INFO] ------------------------------------------------------------------------

```

**Comment by art1988** [comment]
Please, have a look:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< org.example:GeoIPExample >----------------------
[INFO] Building GeoIPExample 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ GeoIPExample ---
[INFO] org.example:GeoIPExample:jar:1.0-SNAPSHOT
[INFO] +- org.testng:testng:jar:6.9.8:compile
[INFO] |  +- org.beanshell:bsh:jar:2.0b4:compile
[INFO] |  \- com.beust:jcommander:jar:1.48:compile
[INFO] +- com.codeborne:selenide:jar:6.17.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-java:jar:4.11.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-api:jar:4.11.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:4.11.0:compile
[INFO] |  |  |  +- com.google.auto.service:auto-service-annotations:jar:1.0.1:compile
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-chromium-driver:jar:4.11.0:compile
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-json:jar:4.11.0:compile
[INFO] |  |  |  \- org.seleniumhq.selenium:selenium-manager:jar:4.11.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v113:jar:4.11.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v114:jar:4.11.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v115:jar:4.11.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v85:jar:4.11.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:4.11.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:4.11.0:compile
[INFO] |  |  |  \- org.seleniumhq.selenium:selenium-http:jar:4.11.0:compile
[INFO] |  |  |     \- dev.failsafe:failsafe:jar:3.3.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:4.11.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:4.11.0:compile
[INFO] |  |  |  +- io.netty:netty-buffer:jar:4.1.92.Final:compile
[INFO] |  |  |  +- io.netty:netty-codec-http:jar:4.1.92.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-codec:jar:4.1.92.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-handler:jar:4.1.92.Final:compile
[INFO] |  |  |  +- io.netty:netty-common:jar:4.1.92.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-classes-epoll:jar:4.1.92.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-classes-kqueue:jar:4.1.92.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-native-epoll:jar:4.1.92.Final:linux-x86_64
[INFO] |  |  |  +- io.netty:netty-transport-native-kqueue:jar:4.1.92.Final:osx-x86_64
[INFO] |  |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.92.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport:jar:4.1.92.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-resolver:jar:4.1.92.Final:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-api:jar:1.26.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-context:jar:1.26.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-exporter-logging:jar:1.26.0:compile
[INFO] |  |  |  |  +- io.opentelemetry:opentelemetry-sdk-metrics:jar:1.26.0:compile
[INFO] |  |  |  |  |  \- io.opentelemetry:opentelemetry-extension-incubator:jar:1.26.0-alpha:runtime
[INFO] |  |  |  |  \- io.opentelemetry:opentelemetry-sdk-logs:jar:1.26.0-alpha:compile
[INFO] |  |  |  |     +- io.opentelemetry:opentelemetry-api-logs:jar:1.26.0-alpha:compile
[INFO] |  |  |  |     \- io.opentelemetry:opentelemetry-api-events:jar:1.26.0-alpha:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-common:jar:1.26.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:jar:1.26.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:jar:1.26.0-alpha:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-trace:jar:1.26.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk:jar:1.26.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-semconv:jar:1.26.0-alpha:compile
[INFO] |  |  |  +- net.bytebuddy:byte-buddy:jar:1.14.4:compile
[INFO] |  |  |  +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  |  |  \- org.asynchttpclient:async-http-client:jar:2.12.3:compile
[INFO] |  |  |     +- org.asynchttpclient:async-http-client-netty-utils:jar:2.12.3:compile
[INFO] |  |  |     +- io.netty:netty-codec-socks:jar:4.1.60.Final:compile
[INFO] |  |  |     +- io.netty:netty-handler-proxy:jar:4.1.60.Final:compile
[INFO] |  |  |     +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.60.Final:compile
[INFO] |  |  |     +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.60.Final:compile
[INFO] |  |  |     +- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  |     +- com.typesafe.netty:netty-reactive-streams:jar:2.0.4:compile
[INFO] |  |  |     \- com.sun.activation:jakarta.activation:jar:1.2.2:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:4.11.0:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-support:jar:4.11.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:2.0.7:compile
[INFO] |  +- com.codeborne:selenide-core:jar:6.17.0:compile
[INFO] |  |  +- org.opentest4j:opentest4j:jar:1.3.0:compile
[INFO] |  |  +- org.apache.commons:commons-compress:jar:1.23.0:runtime
[INFO] |  |  \- org.apache.httpcomponents.client5:httpclient5:jar:5.2.1:runtime
[INFO] |  |     +- org.apache.httpcomponents.core5:httpcore5:jar:5.2:runtime
[INFO] |  |     \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2:runtime
[INFO] |  +- com.google.guava:guava:jar:32.1.2-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.33.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.18.0:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:2.8:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.13.0:runtime
[INFO] |  \- commons-io:commons-io:jar:2.13.0:runtime
[INFO] +- com.codeborne:geoip:jar:1.4:compile
[INFO] +- io.qameta.allure:allure-selenide:jar:2.22.1:compile
[INFO] |  \- io.qameta.allure:allure-java-commons:jar:2.22.1:compile
[INFO] |     \- io.qameta.allure:allure-model:jar:2.22.1:compile
[INFO] +- io.qameta.allure:allure-testng:jar:2.22.1:compile
[INFO] |  \- io.qameta.allure:allure-test-filter:jar:2.22.1:runtime
[INFO] +- com.codeborne:pdf-test:jar:1.8.1:compile
[INFO] |  +- org.apache.pdfbox:pdfbox:jar:2.0.27:runtime
[INFO] |  |  +- org.apache.pdfbox:fontbox:jar:2.0.27:runtime
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:runtime
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:runtime
[INFO] |  \- org.assertj:assertj-core:jar:3.23.1:runtime
[INFO] +- com.codeborne:selenide-testng:jar:6.15.0:compile
[INFO] \- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.927 s
[INFO] Finished at: 2023-08-12T15:55:40-04:00
[INFO] ------------------------------------------------------------------------

```

**Comment by BorisOsipov** [comment]
@art1988 

>com.codeborne:selenide-testng:jar:6.15.0:compile

is the culprit. Please don't use different versions of `selenide` and `selenide-testng`.

You can only add `selenide-testng`(remove ` com.codeborne:selenide`) and you will always get the same `selenide` and `selenide-testng`.

**Comment by art1988** [comment]
Indeed,
thanks !
