### ISSUE TITLE
Flaky test `AndroidClickOptionsTest > androidDoubleTap()`

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#2416]
## The problem
Selenide project contains a flaky test that causes build failures quite often.

I guess the problem is that this test calls `$.click(doubleTap());` on a simple checkbox that doesn't really expect double tap, but expects usual tap. The test expects that `$.doubleTap` will check and un-check the checkbox, but sometimes only one of two taps takes effect. Apparently, it depends on the speed of the tap.

I guess we need to fix this test: find some other element in the mobile app that really expects double tap. @amuthan-sakthivel  @amuthansakthivel 

## Tell us about your environment
* **Selenide Version**: 6.17.0

## Failing test example

```java
AndroidClickOptionsTest > androidDoubleTap() FAILED
    Element should have attribute checked="false" {By.xpath: .//android.widget.CheckBox}
    Element: '<CheckBox resource-id="android:id/checkbox" checked="true" enabled="true" focused="false" package="io.appium.android.apis" name="" className="android.widget.CheckBox" bounds="[1272,477][1384,589]" displayed="true"></CheckBox>'
    Actual value: checked="true"
    Screenshot: file:/Users/runner/work/selenide/selenide/modules/appium/build/reports/tests/android/1692083435927.0.png
    Page source: file:/Users/runner/work/selenide/selenide/modules/appium/build/reports/tests/android/1692083435927.0.xml
    Timeout: 10 s.
        at app//com.codeborne.selenide.impl.WebElementSource.handleError(WebElementSource.java:149)
        at app//com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:104)
        at app//com.codeborne.selenide.commands.Should.execute(Should.java:30)
        at app//com.codeborne.selenide.commands.Commands.execute(Commands.java:163)
        at app//it.mobile.android.AndroidClickOptionsTest.androidDoubleTap(AndroidClickOptionsTest.java:54)
```

**Comment by asolntsev** [comment]
fixed by https://github.com/selenide/selenide/pull/2417 and https://github.com/selenide/selenide/commit/7e8b03a81da32b8e9064f7712c325d6e4e7e6cd0
