### ISSUE TITLE
`$.type()` doesn't support `Keys` as arguments

### ISSUE THREAD

**Issue by bereg2k** [selenide/selenide#2422]
## The problem
The new method `$.type()` doesn't support `org.openqa.selenium.Keys` as arguments

## Details

```java
@Test
public void testTypeKeys() {
    open("https://duckduckgo.com/");
    //  ok
    $("[name='q']").type("Duck Duck!");
    //  exception
    $("[name='q']").type(Keys.BACK_SPACE);
}
```

Here's a stack trace for the exception:

```
java.lang.ClassCastException: class org.openqa.selenium.Keys cannot be cast to class java.lang.String (org.openqa.selenium.Keys is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

	at com.codeborne.selenide.commands.Type.extractOptions(Type.java:45)
	at com.codeborne.selenide.commands.Type.execute(Type.java:33)
	at com.codeborne.selenide.commands.Type.execute(Type.java:18)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:163)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:132)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:84)
	at jdk.proxy2/jdk.proxy2.$Proxy14.type(Unknown Source)
	at web.SeleniumTest.testTypeKeys(SeleniumTest.java:181)
```

## Tell us about your environment
* **Selenide Version**: 6.17.0
* **Chrome\Firefox\IE Version**: Version 115.0.5790.170 (Official Build) (arm64)
* **Browser Driver Version**: 115.0
* **Selenium Version**: 4.11
* **OS Version**: OS X 12.1 Monterey

**Comment by BorisOsipov** [comment]
Thanks for reporting this! It seems to be fixed in the https://github.com/selenide/selenide/pull/2421 right?

**Comment by bereg2k** [comment]
@BorisOsipov yes, I suppose. 
However, I'd add at least one check to the unit tests of this feature.

**Comment by asolntsev** [comment]
@bereg2k Yes, sure, I had to add a test. 

Done: https://github.com/selenide/selenide/pull/2428/commits/83d1a3ef0f1e66ed2c6f133ff8f9a99411cbb910
