### ISSUE TITLE
Unable to launch chrome in linux after upgrading to selenide 6.17.0

### ISSUE THREAD

**Issue by infa-vpatil** [selenide/selenide#2425]
## The problem
Unable to launch chrome in linux after upgrading to selenide 6.17.0
facing below error

|_   _| | __| / __| |_   _|   / __| |_   _|   /_\   | _ \ |_   _| | __| |   \ 
       | |   | _|  \__ \   | |     \__ \   | |    / _ \  |   /   | |   | _|  | |) |
       |_|   |___| |___/   |_|     |___/   |_|   /_/ \_\ |_|_\   |_|   |___| |___/ 

    creates custom sourceSystem assets(create-all-assets-which-are-needed-in-business-entity-model;creates-custom-sourcesystem-assets)
    --------------------------------------------------------------------------------
    2023-08-18 17:48:48.479  INFO 15312 --- [    Test worker] c.i.c.u.FileUtils                        : Successfully wrote to the file.
    2023-08-18 17:48:48.479  INFO 15312 --- [    Test worker] c.i.m.s.Hook                             : Before hook logs
    2023-08-18 17:48:48.503  INFO 15312 --- [    Test worker] .b.t.c.SpringBootTestContextBootstrapper : Neither @ContextConfiguration nor @ContextHierarchy found for test class [com.informatica.mdm.step.ui.platformui.LoginStep], using SpringBootContextLoader
    2023-08-18 17:48:48.504  INFO 15312 --- [    Test worker] o.s.t.c.s.AbstractContextLoader          : Could not detect default resource locations for test class [com.informatica.mdm.step.ui.platformui.LoginStep]: no resource found for suffixes {-context.xml, Context.groovy}.
    2023-08-18 17:48:48.504  INFO 15312 --- [    Test worker] t.c.s.AnnotationConfigContextLoaderUtils : Could not detect default configuration classes for test class [com.informatica.mdm.step.ui.platformui.LoginStep]: LoginStep does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
    2023-08-18 17:48:48.510  INFO 15312 --- [    Test worker] .b.t.c.SpringBootTestContextBootstrapper : Found @SpringBootConfiguration com.informatica.mdm.MdmC360Application for test class com.informatica.mdm.step.ui.platformui.LoginStep
    2023-08-18 17:48:48.511  INFO 15312 --- [    Test worker] .b.t.c.SpringBootTestContextBootstrapper : Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.event.ApplicationEventsTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener]
    2023-08-18 17:48:48.512  INFO 15312 --- [    Test worker] .b.t.c.SpringBootTestContextBootstrapper : Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@ab85d63, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@7ad29d4b, org.springframework.test.context.event.ApplicationEventsTestExecutionListener@7270ff5d, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@5451d7a0, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@1ccacb0c, org.springframework.test.context.support.DirtiesContextTestExecutionListener@729c251b, org.springframework.test.context.transaction.TransactionalTestExecutionListener@763a602, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@5d558d99, org.springframework.test.context.event.EventPublishingTestExecutionListener@170dbf94, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@4aae493, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@1e6311b2, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@6fab6ea2, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@15a09ddc, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener@46fd6d87, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@40151a6b]
    2023-08-18 17:48:48.539  INFO 15312 --- [    Test worker] c.c.s.i.WebDriverThreadLocalContainer    : No webdriver is bound to current thread: 1 - let's create a new webdriver
    2023-08-18 17:48:48.546  INFO 15312 --- [    Test worker] c.c.s.i.FileHelper                       : Creating folder: /root/workspace/1_Usecase_1_E2E/mdmtest/build/downloads/1692361128545_15312_1
    2023-08-18 17:48:48.758  INFO 15312 --- [    Test worker] c.c.s.w.SelenideNettyClientFactory       : Changed readTimeout from PT3M to PT1M30S

2023-08-18 17:48:49.478 ERROR 15312 --- [    Test worker]                                          :     Test failed at step: Given "customDesignerUser" opens browser and logs in to mdm ui
    2023-08-18 17:48:49.479 ERROR 15312 --- [    Test worker]                                          :     Could not start a new session. Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.

com.informatica.mdm.Runner > Create all assets which are needed in Business Entity Model.creates custom sourceSystem assets FAILED
    org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.
      (unknown error: DevToolsActivePort file doesn't exist)
      (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
    Host info: host: 'invimpactauto01', ip: '10.65.142.42'
    Build info: version: '4.11.0', revision: '040bc5406b'
    System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.81.1.el7.x86_64', java.version: '16.0.2'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --headless=new, --proxy-bypass-list=<-loopb..., --disable-dev-shm-usage, --disable-background-networ..., --enable-features=NetworkSe..., --disable-background-timer-..., --disable-backgrounding-occ..., --disable-breakpad, --disable-client-side-phish..., --disable-component-extensi..., --disable-default-apps, --disable-features=TranslateUI, --disable-hang-monitor, --disable-ipc-flooding-prot..., --disable-popup-blocking, --disable-prompt-on-repost, --disable-renderer-backgrou..., --disable-sync, --force-color-profile=srgb, --metrics-recording-only, --no-first-run, --password-store=basic, --use-mock-keychain, --hide-scrollbars, --mute-audio, --window-size=1366,768], binary: /opt/google/chrome/google-c..., excludeSwitches: [enable-automation, load-extension], extensions: [], prefs: {credentials_enable_service: false, download.default_directory: /root/workspace/1_Usecase_1..., intl.accept_languages: en, plugins.always_open_pdf_externally: true, profile.default_content_setting_values.automatic_downloads: 1, safebrowsing.enabled: true}}, pageLoadStrategy: none, unhandledPromptBehavior: accept}]}]
    selenide.url: https://qa-ma.mrel.infaqa.com/identity-service/home
    selenide.baseUrl: http://localhost:8080/
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:232)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:159)
        at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
        at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:34)
        at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:120)
        at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:67)
        at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$0(CreateDriverCommand.java:76)
        at com.codeborne.selenide.logevents.SelenideLogger.wrap(SelenideLogger.java:133)
        at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:113)
        at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:52)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:202)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createAndRegisterDriver(WebDriverThreadLocalContainer.java:186)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:155)
        at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
        at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
        at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:220)
        at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:71)
        at com.codeborne.selenide.logevents.SelenideLogger.lambda$run$0(SelenideLogger.java:105)
        at com.codeborne.selenide.logevents.SelenideLogger.wrap(SelenideLogger.java:133)
        at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:104)
        at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:69)
        at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
        at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:101)
        at com.codeborne.selenide.Selenide.open(Selenide.java:53)

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version - 6.17.0**: 
* **Chrome - 116**: 
* **Browser Driver Version**:
* **Selenide-Appium Version**:
* **IOS\Android\WEB version**:
* **Selenium Version 4.11.0**: 
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by ccea-dev-team** [comment]
I got the same kind of issue (https://github.com/selenide/selenide/issues/2423) and I think others have logged issues on the selenium github.  I thought with upgrading to 6,17.0 which uses the selenium-manager to update chrome driver, maybe our corporate firewall was blocking it but not sure.

**Comment by asolntsev** [comment]
@infa-vpatil I also think it's a problem in your browser or Selenium, not in Selenide. 
At least Selenide own tests run nicely on github actions (on Linux and Windows).
