### ISSUE TITLE
issue - Selenide 6.16.0+ CollectionCondition - doesn't show Collections in results, only size of

### ISSUE THREAD

**Issue by antonpimnev** [selenide/selenide#2434]
## The problem
Selenide 6.16.0+ doesn't show Collections in result logs, only size of.

The test checks the composition of the collection by the `$$.shouldHave(textsInAnyOrder("Item1", "Item2", "Item3")` method.

The result in the logs and also in Allure Report displays only the size of the current and expected collection, without displaying the collection itself.

## Details
Without this functionality, debugging work with collections becomes more difficult.

Stack trace:
```java
List size mismatch: expected: = 21, actual: 23, collection: .dynamic-box-html/label
Screenshot: ...
Page source: ...
Timeout: 15 s.
	at com.codeborne.selenide.collections.ExactTexts.fail(ExactTexts.java:76)
	at com.codeborne.selenide.ElementsCollection.waitUntil(ElementsCollection.java:200)
	at com.codeborne.selenide.ElementsCollection.should(ElementsCollection.java:145)
	at com.codeborne.selenide.ElementsCollection.shouldHave(ElementsCollection.java:119)
	at tests._21300._21300_w21302_tab_tests.lambda$moduleTableItemMenuEditClickTest$66(_21300_w21302_tab_tests.java:399)
```

## Tell us about your environment
* **Selenide Version**: 6.17.1
* **Chrome\Firefox\IE Version**: Chromium 115.0
* **IOS\Android\WEB version**:  WEB version
* **OS Version**: Windows 10 64-bit build 19044.3086

## Code To Reproduce Issue
```java
$(".element").$$("label")shouldHave(textsInAnyOrder("Item1", "Item2", "Item3");
```

**Comment by antonpimnev** [comment]
> @antonpimnev But maybe I was wrong. When a test fail, it takes 4+ seconds anyway.

Sometimes the pursuit of optimization can break the user experience. It's familiar :)
