### ISSUE TITLE
selenide-6.19.1 does not work with the selenium-java-4.14.x 

### ISSUE THREAD

**Issue by kazurayam** [selenide/selenide#2525]
## The problem
selenide-6.19.1 does not work with the selenide-java-4.14.x due to "java.lang.ClassNotFoundException: org.openqa.selenium.remote.http.netty.NettyClient$Factory"

## Details

See my report in detail at https://github.com/kazurayam/SelenideTutorialBaeldung/issues/1 
I will quote the essence here for reference.

----

I have the `master` branch. It is fine. I can successfully run a JUnit test with selenide, as follows:
```
$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
:~/github/SelenideTutorialBaeldung (master)
$ gradle test
[Thread-7] INFO com.codeborne.selenide.drivercommands.DisposablesRegistry - Run cleanup: size=1
[Thread-7] INFO com.codeborne.selenide.impl.FileHelper - Deleted empty folder: /Users/kazuakiurayama/github/SelenideTutorialBaeldung/build/downloads/1698052182603_10299_1
[Thread-7] INFO com.codeborne.selenide.drivercommands.CloseDriverCommand - Close webdriver: 37 -> ChromeDriver: chrome on mac (4435af17b79f30c4b81061f4ea5fa3d4)...
[Thread-7] INFO com.codeborne.selenide.drivercommands.CloseDriverCommand - Closed webdriver 37 in 116 ms
[Thread-7] INFO com.codeborne.selenide.drivercommands.DisposablesRegistry - Finished cleanup

BUILD SUCCESSFUL in 33s
2 actionable tasks: 2 executed
```

Then I created a branch `kazurayam1`．　Ｉｎ　ｔｈｅ　ｂｒａｃｈ　Ｉ　ｍｏｄｉｆｅｄ　ｔｈｅ　`build.gradle` so that it explicitly specify `selenium-java4.14.1`.

- https://github.com/kazurayam/SelenideTutorialBaeldung/blob/kazurayam1/build.gradle
```
dependencies {
    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.14.1'

    // https://mvnrepository.com/artifact/com.codeborne/selenide
    testImplementation 'com.codeborne:selenide:6.19.1'
...
```

Check out the `kazurayam1` branch and run

```
$ ./gradlew test
```

Then you will see an error

```
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/http/netty/NettyClient$Factory" type="java.lang.NoClassDefFoundError">java.lang.NoClassDefFoundError: org/openqa/selenium/remote/http/netty/NettyClient$Factory
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1217)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at java.base/java.util.Spliterators$IteratorSpliterator.trySplit(Spliterators.java:1820)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:308)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.openqa.selenium.remote.http.HttpClient$Factory.create(HttpClient.java:55)
	at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor$DefaultClientFactoryHolder.&lt;clinit&gt;(HttpCommandExecutor.java:57)
	at org.openqa.selenium.remote.HttpCommandExecutor.getDefaultClientFactory(HttpCommandExecutor.java:61)
	at org.openqa.selenium.remote.HttpCommandExecutor.&lt;init&gt;(HttpCommandExecutor.java:95)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.&lt;init&gt;(DriverCommandExecutor.java:89)
	at org.openqa.selenium.chromium.ChromiumDriverCommandExecutor.&lt;init&gt;(ChromiumDriverCommandExecutor.java:43)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.&lt;init&gt;(ChromeDriver.java:115)
	at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:105)
	at org.openqa.selenium.chrome.ChromeDriver.&lt;init&gt;(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.&lt;init&gt;(ChromeDriver.java:83)
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:34)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:120)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:67)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$0(CreateDriverCommand.java:76)
	at com.codeborne.selenide.logevents.SelenideLogger.wrap(SelenideLogger.java:133)
	at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:113)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:52)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:205)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createAndRegisterDriver(WebDriverThreadLocalContainer.java:190)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:152)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:223)
	at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:71)
	at com.codeborne.selenide.logevents.SelenideLogger.lambda$run$0(SelenideLogger.java:105)
	at com.codeborne.selenide.logevents.SelenideLogger.wrap(SelenideLogger.java:133)
	at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:104)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:69)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:102)
	at com.codeborne.selenide.Selenide.open(Selenide.java:53)
	at com.baeldung.selenide.SearchLiveTest.searchBaeldung(SearchLiveTest.java:13)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.http.netty.NettyClient$Factory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 60 more
```

## Tell us about your environment
* **Selenide version: ** 6.19.1 
* **Chrome\Firefox\IE Version**: Not applicable 
* **Browser Driver Version**: N/A
* **Selenide-Appium Version**: N/A
* **IOS\Android\WEB version**: N/A
* **Selenium Version : **: 4.14.1
* **OS Version**: macOS 12.7

## Code To Reproduce Issue [ Good To Have ]

You can checkout a Gradle project that would let you reproduce the issue easily:

- https://github.com/kazurayam/SelenideTutorialBaeldung/tree/kazurayam1

Just run the following test:

https://github.com/kazurayam/SelenideTutorialBaeldung/blob/kazurayam1/src/test/java/com/baeldung/selenide/SearchLiveTest.java

## My proposal

The selenide-6.19.1 can not work with the selenide-java-4.14.x because the selenide-java-4.14.x stopped using Netty HTTP Client. Instead the selenide-java-4.14.x uses JDK-bundled HTTP Client.

Hopefully Selenide project should plan a migration from Netty HTTP Client to JDK HTTP Client.

**Comment by rosolko** [comment]
This release shouldn't work with selenium 4.14.1 required java 11, because selenide 6.19.1 target java 8. Please wait until selenide 7.0.0 release, it will target java 17 and will bundled and work with latest selenium release.
