### ISSUE TITLE
java.lang.NullPointerException for $$x.shouldHave(CollectionCondition.exactTexts(List<String>)) in Safari

### ISSUE THREAD

**Issue by Leonid-Abakumov** [selenide/selenide#2551]
[ovelay.html](https://github.com/selenide/selenide/files/13307233/ovelay.txt)

## The problem
`java.lang.NullPointerException` for `$$x.shouldHave(CollectionCondition.exactTexts(List<String>))`

## Details
full log is:

```java
java.lang.NullPointerException
    at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
    at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
    at java.base/java.util.regex.Matcher.(Matcher.java:253)
    at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
    at com.codeborne.selenide.impl.Html.reduceSpaces(Html.java:39)
    at com.codeborne.selenide.impl.Html.equals(Html.java:31)
    at com.codeborne.selenide.collections.ExactTexts.check(ExactTexts.java:63)
    at com.codeborne.selenide.collections.ExactTexts.check(ExactTexts.java:53)
    at com.codeborne.selenide.CollectionCondition.check(CollectionCondition.java:63)
    at com.codeborne.selenide.ElementsCollection.waitUntil(ElementsCollection.java:172)
    at com.codeborne.selenide.ElementsCollection.should(ElementsCollection.java:145)
    at com.codeborne.selenide.ElementsCollection.shouldHave(ElementsCollection.java:119)
```

Caused by this line:
```java
$$x(.//div[@qaid='overlay']//li[contains(@qaid, 'message_')])
    .shouldHave(CollectionCondition.exactTexts(List<String>));
```

For Chrome it works as expected

## Tell us about your environment
* **Selenide Version**: 6.17.0
* **Chrome\Firefox\IE Version**: aerokube-browsers/safari
* **Browser Driver Version**:15.0
* **Selenide-Appium Version**:6.17.0

**Comment by BorisOsipov** [comment]
We can partially fix it, but webkit is buggy. Getting text from element inside svg crashes with `JavascriptException 
$("#banana svg tspan").getText();`

```
JavascriptException: undefined is not an object (evaluating 'element.innerText.replace')
Timeout: 1 ms.
Caused by: JavascriptException: undefined is not an object (evaluating 'element.innerText.replace')
```
There is nothing to do.It is a webkit driver(?) problem.

**Comment by Leonid-Abakumov** [comment]
Thanks for the quick feedback, agree with buggy webkit. But could you explain what partially can be fixed from selenide side?
