### ISSUE TITLE
Can not set ElementsCollection field to SelenideAppiumCollection

### ISSUE THREAD

**Issue by rosolko** [selenide/selenide#2670]
## The problem
Using of ElementsCollection instead of SelenideAppiumCollection inside appium page object class throw and IllegalArgumentException exception. 

## Tell us about your environment
* **Selenide-Appium Version**: 7.2.0

## Code To Reproduce Issue [ Good To Have ]
Page:
```java
class PageWithCollection {
  @AndroidFindBy(xpath = "//android.widget.EditText")
  ElementsCollection editTexts;
}
```

Using:
```java
public class Test {
  @Test
  public void collectionTest() {
    PageWithCollection pageWithCollection = page();
    pageWithCollection.editTexts.shouldHave(sizeGreaterThan(0));
  }
}
```

Throw:
```java
Test > collectionTest() FAILED
    java.lang.IllegalArgumentException: Can not set com.codeborne.selenide.ElementsCollection field it.mobile.android.LoginPageWithCollections.editTexts to com.codeborne.selenide.appium.SelenideAppiumCollection
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
        at java.base/java.lang.reflect.Field.set(Field.java:799)
        at com.codeborne.selenide.impl.SelenidePageFactory.setFieldValue(SelenidePageFactory.java:133)
        at com.codeborne.selenide.impl.SelenidePageFactory.initField(SelenidePageFactory.java:93)
        at com.codeborne.selenide.impl.SelenidePageFactory.initFields(SelenidePageFactory.java:86)
        at com.codeborne.selenide.impl.SelenidePageFactory.initElements(SelenidePageFactory.java:77)
        at com.codeborne.selenide.impl.SelenidePageFactory.page(SelenidePageFactory.java:64)
        at com.codeborne.selenide.impl.SelenidePageFactory.page(SelenidePageFactory.java:52)
        at com.codeborne.selenide.SelenideDriver.page(SelenideDriver.java:159)
        at com.codeborne.selenide.Selenide.page(Selenide.java:758)
```

**Comment by asolntsev** [comment]
will be fixed by https://github.com/selenide/selenide/pull/2677
