### ISSUE TITLE
Selenide-Appium UnsupportedCommandException

### ISSUE THREAD

**Issue by exmike** [selenide/selenide#2722]
Problem:
When using the clear method on SelenideAppiumElement, I get an UnsupportedCommandException: Unhandled endpoint: /session/xxx/element/xxx/css/opacity

Selenide - 7.2.3
Appium - 2.5.4
xcuitest - 7.14.0
ios simulator version - 17.2

## Code To Reproduce Issue [ Good To Have ]
element.clear()

**Comment by asolntsev** [comment]
@exmike Please provide the error message with **full stacktrace**. 
AFAIK error `UnsupportedCommandException` is only possible when you use `selenide` dependency without `selenide-appium`.

**Comment by exmike** [comment]
@asolntsev 
dependencies - 
[INFO] +- com.squareup.okhttp3:okhttp:jar:4.10.0:compile
[INFO] |  +- com.squareup.okio:okio-jvm:jar:3.0.0:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.5.31:compile
[INFO] |  |  |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.5.31:compile
[INFO] |  |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.5.31:compile
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.6.20:compile
[INFO] |     \- org.jetbrains:annotations:jar:13.0:compile
[INFO] +- org.java-websocket:Java-WebSocket:jar:1.5.3:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- org.testng:testng:jar:7.9.0:compile
[INFO] |  +- com.beust:jcommander:jar:1.82:compile
[INFO] |  \- org.webjars:jquery:jar:3.7.1:runtime
[INFO] +- com.codeborne:selenide-appium:jar:7.2.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-java:jar:4.19.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-api:jar:4.19.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:4.19.1:compile
[INFO] |  |  |  +- com.google.auto.service:auto-service-annotations:jar:1.1.1:compile
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-chromium-driver:jar:4.19.1:compile
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-json:jar:4.19.1:compile
[INFO] |  |  |  \- org.seleniumhq.selenium:selenium-manager:jar:4.19.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v121:jar:4.19.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v122:jar:4.19.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v123:jar:4.19.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-devtools-v85:jar:4.19.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:4.19.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:4.19.1:compile
[INFO] |  |  |  \- org.seleniumhq.selenium:selenium-http:jar:4.19.1:compile
[INFO] |  |  |     \- dev.failsafe:failsafe:jar:3.3.2:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:4.19.1:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:4.19.1:compile
[INFO] |  |  |  +- io.opentelemetry.semconv:opentelemetry-semconv:jar:1.23.1-alpha:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-api:jar:1.36.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-context:jar:1.36.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-exporter-logging:jar:1.36.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-common:jar:1.36.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:jar:1.36.0:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:jar:1.36.0:compile
[INFO] |  |  |  |  \- io.opentelemetry:opentelemetry-api-events:jar:1.36.0-alpha:runtime
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-trace:jar:1.36.0:compile
[INFO] |  |  |  |  \- io.opentelemetry:opentelemetry-extension-incubator:jar:1.36.0-alpha:runtime
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk:jar:1.36.0:compile
[INFO] |  |  |  |  +- io.opentelemetry:opentelemetry-sdk-metrics:jar:1.36.0:compile
[INFO] |  |  |  |  \- io.opentelemetry:opentelemetry-sdk-logs:jar:1.36.0:compile
[INFO] |  |  |  \- org.seleniumhq.selenium:selenium-os:jar:4.19.1:compile
[INFO] |  |  |     \- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:4.19.1:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-support:jar:4.19.1:compile
[INFO] |  +- com.codeborne:selenide:jar:7.2.3:compile
[INFO] |  |  \- com.codeborne:selenide-core:jar:7.2.3:compile
[INFO] |  |     \- org.opentest4j:opentest4j:jar:1.3.0:compile
[INFO] |  +- io.appium:java-client:jar:9.2.2:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.10.1:runtime
[INFO] |  +- com.google.guava:guava:jar:33.1.0-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.2:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.42.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.26.1:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:3.0.0:compile
[INFO] |  \- commons-io:commons-io:jar:2.16.0:compile
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.22.1:compile
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.22.1:compile
[INFO] +- org.slf4j:slf4j-reload4j:jar:2.0.11:compile
[INFO] |  \- ch.qos.reload4j:reload4j:jar:1.2.22:compile
[INFO] +- org.wiremock:wiremock:jar:3.3.1:compile
[INFO] |  +- org.eclipse.jetty:jetty-server:jar:11.0.18:compile
[INFO] |  |  +- org.eclipse.jetty.toolchain:jetty-jakarta-servlet-api:jar:5.0.2:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:11.0.18:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-io:jar:11.0.18:compile
[INFO] |  +- org.eclipse.jetty:jetty-servlet:jar:11.0.18:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-security:jar:11.0.18:compile
[INFO] |  +- org.eclipse.jetty:jetty-servlets:jar:11.0.18:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:11.0.18:compile
[INFO] |  +- org.eclipse.jetty:jetty-webapp:jar:11.0.18:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-xml:jar:11.0.18:compile
[INFO] |  +- org.eclipse.jetty:jetty-proxy:jar:11.0.18:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-client:jar:11.0.18:compile
[INFO] |  +- org.eclipse.jetty.http2:http2-server:jar:11.0.18:compile
[INFO] |  |  \- org.eclipse.jetty.http2:http2-common:jar:11.0.18:compile
[INFO] |  |     \- org.eclipse.jetty.http2:http2-hpack:jar:11.0.18:compile
[INFO] |  +- org.eclipse.jetty:jetty-alpn-server:jar:11.0.18:compile
[INFO] |  +- org.eclipse.jetty:jetty-alpn-java-server:jar:11.0.18:compile
[INFO] |  +- org.eclipse.jetty:jetty-alpn-java-client:jar:11.0.18:compile
[INFO] |  +- org.eclipse.jetty:jetty-alpn-client:jar:11.0.18:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.15.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.15.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.15.3:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.15.3:compile
[INFO] |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.2.1:compile
[INFO] |  |  +- org.apache.httpcomponents.core5:httpcore5:jar:5.2:compile
[INFO] |  |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2:compile
[INFO] |  +- org.xmlunit:xmlunit-core:jar:2.9.1:compile
[INFO] |  |  \- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |     \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.xmlunit:xmlunit-legacy:jar:2.9.1:compile
[INFO] |  +- org.xmlunit:xmlunit-placeholders:jar:2.9.1:compile
[INFO] |  +- net.javacrumbs.json-unit:json-unit-core:jar:2.38.0:compile
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:2.2:compile
[INFO] |  +- org.ow2.asm:asm:jar:9.6:compile
[INFO] |  +- net.sf.jopt-simple:jopt-simple:jar:5.0.4:compile
[INFO] |  +- com.github.jknack:handlebars:jar:4.3.1:compile
[INFO] |  +- com.github.jknack:handlebars-helpers:jar:4.3.1:compile
[INFO] |  +- commons-fileupload:commons-fileupload:jar:1.5:compile
[INFO] |  \- com.networknt:json-schema-validator:jar:1.0.87:compile
[INFO] |     +- com.ethlo.time:itu:jar:1.7.0:compile
[INFO] |     \- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.15.2:compile
[INFO] +- com.jayway.jsonpath:json-path:jar:2.9.0:compile
[INFO] |  \- net.minidev:json-smart:jar:2.5.0:runtime
[INFO] |     \- net.minidev:accessors-smart:jar:2.5.0:runtime
[INFO] +- io.qameta.allure:allure-testng:jar:2.25.0:compile
[INFO] |  +- io.qameta.allure:allure-java-commons:jar:2.25.0:compile
[INFO] |  |  \- io.qameta.allure:allure-model:jar:2.25.0:compile
[INFO] |  \- io.qameta.allure:allure-test-filter:jar:2.25.0:runtime
[INFO] +- org.awaitility:awaitility:jar:4.2.0:compile
[INFO] |  \- org.hamcrest:hamcrest:jar:2.1:compile
[INFO] +- org.yaml:snakeyaml:jar:1.33:compile
[INFO] +- org.assertj:assertj-core:jar:3.25.2:compile
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.14.11:compile
[INFO] \- org.aspectj:aspectjweaver:jar:1.9.21:compile

stacktrace -
Caused by: UnsupportedCommandException: Unhandled endpoint: /session/7352CB93-3D80-47A8-86FC-A2F9707C979F/element/13010000-0000-0000-2D2F-010000000000/css/opacity -- http://127.0.0.1:6346/ with parameters {

	at com.codeborne.selenide.impl.WebElementSource.handleError(WebElementSource.java:147)
	at com.codeborne.selenide.impl.WebElementSource.checkConditionAndReturnElement(WebElementSource.java:125)
	at com.codeborne.selenide.impl.WebElementSource.findAndAssertElementIsInteractable(WebElementSource.java:159)
	at com.codeborne.selenide.appium.commands.AppiumClear.execute(AppiumClear.java:21)
	at com.codeborne.selenide.appium.commands.AppiumClear.execute(AppiumClear.java:14)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:162)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:134)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:86)
	at jdk.proxy2/jdk.proxy2.$Proxy51.clear(Unknown Source)
	at ru.uiautotests.app.elements.Input.sendText(Input.java:29)
	at page.generated.CameraWiFiScreen.wiFiInput_sendText(CameraWiFiScreen.java:737)
	at ru.uiautotests.app.steps.CameraSteps.navigateToHelpIOS(CameraSteps.java:129)
	at ru.uiautotests.tests.ios.devices.camera.AddCameraTest.testAddCameraHelpScreenFlashingGreenReturn(AddCameraTest.java:163)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:819)
	at org.testng.TestRunner.run(TestRunner.java:619)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
	at org.testng.TestNG.runSuites(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1101)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: org.openqa.selenium.UnsupportedCommandException: Unhandled endpoint: /session/7352CB93-3D80-47A8-86FC-A2F9707C979F/element/13010000-0000-0000-2D2F-010000000000/css/opacity -- http://127.0.0.1:6346/ with parameters {
    wildcards =     (
        "session/7352CB93-3D80-47A8-86FC-A2F9707C979F/element/13010000-0000-0000-2D2F-010000000000/css/opacity"
    );
}
Build info: version: '4.19.1', revision: 'abe0ee07dc'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.3.1', java.version: '17.0.9'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [d27186bf-5c93-43a7-8443-430074e467f4, getElementValueOfCssProperty {id=13010000-0000-0000-2D2F-010000000000, propertyName=opacity}]
Capabilities {appium:autoLaunch: false, appium:automationName: XCUITest, appium:clearSystemFiles: true, appium:databaseEnabled: false, appium:derivedDataPath: /Users/evilin1/IdeaProjects..., appium:deviceName: iPhone 14 Plus, appium:forceAppLaunch: false, appium:fullReset: false, appium:isHeadless: false, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: false, appium:newCommandTimeout: 60, appium:platformVersion: 15.5, appium:prebuiltWDAPath: src/main/resources/WebDrive..., appium:realDevice: false, appium:showXcodeLog: false, appium:takesScreenshot: true, appium:udid: 547E4BAC-1735-43BC-8C0D-416..., appium:updatedWDABundleId: com.facebook.WebDriverAgent..., appium:useNewWDA: true, appium:usePrebuiltWDA: true, appium:usePreinstalledWDA: true, appium:wdaLocalPort: 6346, appium:webStorageEnabled: false, platformName: IOS}
Element: [[IOSDriver:  on IOS (d27186bf-5c93-43a7-8443-430074e467f4)] -> id: CameraWiFiCredentialsScreen.SSIDTextField.TextFieldCell.TextField]
Session ID: d27186bf-5c93-43a7-8443-430074e467f4
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
	at org.openqa.selenium.remote.RemoteWebElement.getCssValue(RemoteWebElement.java:197)
	at com.codeborne.selenide.conditions.CssValue.check(CssValue.java:30)
	at com.codeborne.selenide.conditions.Or.check(Or.java:57)
	at com.codeborne.selenide.impl.WebElementSource.checkConditionAndReturnElement(WebElementSource.java:115)
	... 38 more
