### ISSUE TITLE
Selenide-appium appears even when it's not used.

### ISSUE THREAD

**Issue by IlyaMaliauka** [selenide/selenide#2797]
Hi team, 
I updated Selenide to 7.4.0 to fix the issue https://github.com/selenide/selenide/pull/2791/files. 
However, for some reason the problem persists for me. 
The only thing I do in my test is call for
$('...').click(), but logs look like this: 

```
2024-07-30 10:28:24 [main] INFO  LoginUtils:37  login - Using selenoid login...
2024-07-30 10:28:27 [main] INFO  Navigation to https://mysite.com/ completed
10:28:27.496 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.impl.WebElementSelector: com.codeborne.selenide.impl.WebElementSelector
10:28:27.499 [main] INFO com.codeborne.selenide.impl.Plugins -- Using implementation of com.codeborne.selenide.impl.ElementDescriber: com.codeborne.selenide.appium.AppiumElementDescriber
10:28:27.534 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.commands.Clear: com.codeborne.selenide.commands.Clear
10:28:27.594 [main] INFO com.codeborne.selenide.impl.Plugins -- Using implementation of com.codeborne.selenide.impl.DownloadFileToFolder: org.selenide.selenoid.DownloadFileInSelenoid
10:28:27.597 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.impl.DownloadFileWithCdp: com.codeborne.selenide.impl.DownloadFileWithCdp
10:28:27.619 [main] INFO com.codeborne.selenide.impl.Plugins -- Using implementation of com.codeborne.selenide.commands.Commands: com.codeborne.selenide.appium.commands.SelenideAppiumCommands
10:28:37.707 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.ex.ErrorFormatter: com.codeborne.selenide.ex.SelenideErrorFormatter

org.openqa.selenium.remote.http.ConnectionFailedException: JdkWebSocket initial request execution error
Build info: version: '4.23.0', revision: '4df0a231af'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.1'
Driver info: driver.version: unknown

	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.openSocket(JdkHttpClient.java:246)
	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:89)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.<init>(SeleniumCdpConnection.java:36)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.lambda$create$3(SeleniumCdpConnection.java:103)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:103)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:49)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:50)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:29)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:207)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:178)
	at com.codeborne.selenide.impl.WebdriverUnwrapper.unwrap(WebdriverUnwrapper.java:57)
	at com.codeborne.selenide.impl.WebdriverUnwrapper.unwrap(WebdriverUnwrapper.java:53)
	at com.codeborne.selenide.impl.WebdriverUnwrapper.cast(WebdriverUnwrapper.java:30)
	at com.codeborne.selenide.impl.WebdriverUnwrapper.instanceOf(WebdriverUnwrapper.java:22)
	at com.codeborne.selenide.appium.AppiumDriverUnwrapper.isMobile(AppiumDriverUnwrapper.java:17)
	at com.codeborne.selenide.appium.AppiumScreenSourceExtractor.createFile(AppiumScreenSourceExtractor.java:20)
	at com.codeborne.selenide.impl.WebPageSourceExtractor.extract(WebPageSourceExtractor.java:35)
	at com.codeborne.selenide.impl.WebPageSourceExtractor.extract(WebPageSourceExtractor.java:31)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.savePageSourceToFile(ScreenShotLaboratory.java:312)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.takeScreenShot(ScreenShotLaboratory.java:133)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.lambda$takeScreenshot$15(ScreenShotLaboratory.java:440)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.ifReportsFolderNotNull(ScreenShotLaboratory.java:530)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.lambda$takeScreenshot$16(ScreenShotLaboratory.java:439)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.ifWebDriverStarted(ScreenShotLaboratory.java:520)
	at com.codeborne.selenide.impl.ScreenShotLaboratory.takeScreenshot(ScreenShotLaboratory.java:438)
	at com.codeborne.selenide.ex.UIAssertionError.wrapThrowable(UIAssertionError.java:123)
	at com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java:108)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:96)
	at jdk.proxy2/jdk.proxy2.$Proxy45.setValue(Unknown Source)
	at autotests.framework.page.AzureAuthenticationPage.passAzureAuthWithCert(AzureAuthenticationPage.java:27)
	at util.BrowserTest.openBrowser(BrowserTest.java:21)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:848)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.net.http.WebSocketHandshakeException
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.resultFrom(OpeningHandshake.java:224)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: jdk.internal.net.http.websocket.CheckFailedException: Unexpected HTTP response status code 502
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.checkFailed(OpeningHandshake.java:341)
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.handleResponse(OpeningHandshake.java:250)
	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.resultFrom(OpeningHandshake.java:220)
```

As far as I can see, the browser tried to download sometings with CDP and therefore fails. But the thing is, I don't download anything in the test :) 
What's even more strange, the error persists only on Edge. I can see that there is definitely some missalignment between selenoid and selenide-appium, but I can't find any leads...

**Comment by asolntsev** [comment]
@IlyaMaliauka Did you read the stacktrace? No, nobody is calling any "download" methods. Nobody is trying to download anything. 
What means "Selenide-appium is not used"? I believe you have `selenide-appium` dependency in classpath, right? 

Again, as I mentioned before, it's rather a bug in Selenium class `Augmenter`. 
But I hope workaround https://github.com/selenide/selenide/pull/2798 fixes the problem in your case.

**Comment by IlyaMaliauka** [comment]
Hi, @asolntsev. I get it know, sorry for confusion. I thought that if SelenideAppium.launchApp() was not called, there should be no signs of appium in the logs at all. Will test when Selenide 7.4.1 is released, thank you very much!

**Comment by asolntsev** [comment]
@IlyaMaliauka  Selenide 7.4.1 is available, please try.

**Comment by IlyaMaliauka** [comment]
@asolntsev Unfortunately it didn't help :( I contacted aerokube supported and they mentioned that the issue is in CDP, which doesn't work in their edge images,  but logs say it's used:

```
at org.openqa.selenium.devtools.SeleniumCdpConnection.<init>(SeleniumCdpConnection.java:36)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.lambda$create$3(SeleniumCdpConnection.java:103)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:103)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:49)
```

Thought I really cannot understand why it is used, because there were absolutely no changes from my side when it stopped working. I'll continue debugging and post the solution when I find one in case someone has the same issue.
Thank you for the effort!

**Comment by asolntsev** [comment]
@IlyaMaliauka Please share the **full stacktrace**.

**Comment by BorisOsipov** [comment]
>I contacted aerokube supported and they mentioned that the issue is in CDP, which doesn't work in their edge images

And what do you want from us?) You've started a session on Selenoid. It returned capabilities that indicates current session has CDP and url to connect to CDP. Internally we use some code that can in some cases connect to CDP session for some reason. Obviously it cannot connect beacause Selenoid lies that current session has CDP.
Maybe it should be fixed on Selenoid side?)

**Comment by IlyaMaliauka** [comment]
@asolntsev @BorisOsipov  You're right, the issue is on selenoid side. Sorry for misleading, it's just that log messages about CDP and appium confused me a little bit. I reported the bug to selenoid. Thank you very much!
