### ISSUE TITLE
Selenide is not working wit Custom Profiles and remote driver.

### ISSUE THREAD

**Issue by i3000** [selenide/selenide#558]
I try to configure the initialization of the WebDriver using https://github.com/codeborne/selenide/wiki/How-Selenide-creates-WebDriver#how-to-run-selenide-with-custom-profile

I configure my firefox profile and when I use local web driver (I'm not using remote system variable) everything work as expected.

When I add the remote Selenium server by setting the remote system property I get this exception:

2017-06-20T14:04:52,532Z INFO  [main] InfoTestReportLogger.logCurrentMethod:367 - org.openqa.selenium.WebDriverException: The best matching driver provider org.openqa.selenium.ie.InternetExplorerDriver can't create a new driver instance for Capabilities [{pageLoadStrategy=normal, browserName=com.vmware.vcac.qe.ui.selenide.CustomWebDriverProvider}]
Build info: version: '2.50.1', revision: 'd7fc91b', time: '2016-01-29 19:08:26'
System info: host: 'sc2-rdops-vm03-dhcp-100-156', ip: '10.192.100.156', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: driver.version: unknown
Command duration or timeout: 980 milliseconds
Build info: version: '2.50.1', revision: 'd7fc91b29de65b790abb01f3ac5f7ea2191c88a7', time: '2016-01-29 11:11:26'
System info: host: 'ivanovi-nb10', ip: '10.27.96.122', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createRemoteDriver(WebDriverFactory.java:74)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:41)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:214)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getWebDriver(WebDriverThreadLocalContainer.java:95)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getCurrentUrl(WebDriverThreadLocalContainer.java:205)
	at com.codeborne.selenide.WebDriverRunner.url(WebDriverRunner.java:247)
	at 
....................................
Caused by: org.openqa.selenium.WebDriverException: The best matching driver provider org.openqa.selenium.ie.InternetExplorerDriver can't create a new driver instance for Capabilities [{pageLoadStrategy=normal, browserName=com.*****.qe.ui.selenide.CustomWebDriverProvider}]
Build info: version: '2.50.1', revision: 'd7fc91b', time: '2016-01-29 19:08:26'
System info: host: 'sc2-rdops-vm03-dhcp-100-156', ip: '10.192.100.156', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: driver.version: unknown
Build info: version: '2.50.1', revision: 'd7fc91b29de65b790abb01f3ac5f7ea2191c88a7', time: '2016-01-29 11:11:26'
System info: host: 'ivanovi-nb10', ip: '10.27.96.122', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:62)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

My createDriver method is not invoked and the com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(Proxy) method is invoked instead.

**Comment by SergeyPirogov** [comment]
Strange. BTW if this PR https://github.com/codeborne/selenide/pull/556 will be merged, there will be no need to create own webdriver

**Comment by BorisOsipov** [comment]
Hi@i3000   
Can you create a sample project that would reproduce your problem and share with us?

Thanks

**Comment by i3000** [comment]
Hi Boris,
I'm sending you the sample project link:
https://drive.google.com/file/d/0B6RKs057mWXQYXB3c3pEZ0pmaHc/view?usp=sharing

You can change the IP to the remote driver in test-config.properties to reproduce the issue.

Thanks,
Ivan

**Comment by BorisOsipov** [comment]
HI @i3000,
I have looked into your project example.

_Cause_
You ran into an internal selenide 'feature'. When you set Configuration#remote property with any value Selenide doesn't invoke your WebDriverProvider implementation and create a RemoteDriver instead. I think It is ok for some cases.

_How to fix your problem:_
Don't set the Configuration#remote property if you use CustomWebDriverProvider.
Also If you use your own WebDriverProvider implementation(CustomWebDriverProvider) **you will be fully responsible** for a wedriver instance creation and you should create  the RemoteWebDriver in CustomWebDriverProvider manually.

I hope I explained clearly ;)

Thanks

**Comment by i3000** [comment]
Yes, thanks.
I just expected that when I set the remote system property my CustomWebDriverProvider will not be skipped. That's why I log this issue.

Maybe it's good to add some info in the documentation for the CustomWebDriverProvider.

Thanks

**Comment by BorisOsipov** [comment]
@i3000 Yeah it makes sense. Would you like to make an pr with corresponding changes?

**Comment by rosolko** [comment]
https://github.com/selenide/selenide/wiki/How-Selenide-creates-WebDriver#how-to-run-selenide-with-custom-profile

**Comment by Ivanello** [comment]
here is an explanation how to run custom browser with selenide in selenoid
https://medium.com/@rosolko/configure-selenide-to-work-with-selenoid-8835cd6dc7d2
