### ISSUE TITLE
ClassCastException on attempt to decorate list of page elements of generic type

### ISSUE THREAD

**Issue by ninja-batman** [selenide/selenide#694]
## The problem
ClassCastException on attempt to decorate list of page elements of generic type

## Details
Let's say I have the following element container class:

```java
public class DummyTypedElement<T> extends ElementsContainer {

    @FindBy(tagName = "a")
    private List<T> list;

}
```

And a page object with field of that type:
```java
public class DummyPage {

    @FindBy(tagName = "div")
    private DummyTypedElement<SelenideElement> element;
}
```

When I tried to initialize that page by `Selenide.page` I got the following exception:
<pre>
Caused by: java.lang.RuntimeException: Failed to create elements container for field element
	at com.codeborne.selenide.impl.SelenideFieldDecorator.createElementsContainer(SelenideFieldDecorator.java:69) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.impl.SelenideFieldDecorator.decorate(SelenideFieldDecorator.java:38) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.SelenidePageFactory.proxyFields(SelenidePageFactory.java:35) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.SelenidePageFactory.initElements(SelenidePageFactory.java:24) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.Selenide.page(Selenide.java:643) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.Selenide.page(Selenide.java:632) ~[selenide-4.9.1.jar:4.9.1]
	... 60 more
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at com.codeborne.selenide.impl.SelenideFieldDecorator.getListGenericType(SelenideFieldDecorator.java:98) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.impl.SelenideFieldDecorator.isDecoratableList(SelenideFieldDecorator.java:88) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.impl.SelenideFieldDecorator.decorate(SelenideFieldDecorator.java:40) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.SelenidePageFactory.proxyFields(SelenidePageFactory.java:35) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.SelenidePageFactory.initElements(SelenidePageFactory.java:24) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.impl.SelenideFieldDecorator.initElementsContainer(SelenideFieldDecorator.java:78) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.impl.SelenideFieldDecorator.createElementsContainer(SelenideFieldDecorator.java:67) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.impl.SelenideFieldDecorator.decorate(SelenideFieldDecorator.java:38) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.SelenidePageFactory.proxyFields(SelenidePageFactory.java:35) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.SelenidePageFactory.initElements(SelenidePageFactory.java:24) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.Selenide.page(Selenide.java:643) ~[selenide-4.9.1.jar:4.9.1]
	at com.codeborne.selenide.Selenide.page(Selenide.java:632) ~[selenide-4.9.1.jar:4.9.1]
</pre>

## Tell us about your environment
* **Selenide Version:** 4.9.1
* **Chrome\Firefox\IE Version:**
* **Browser Driver Version:**
* **Selenium Version:**
* **OS Version:**

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
@ninja-batman Can you explain why it's needed to have `ElementsContainer` of generic type?
I started implementing this feature and realized that it's quite hard to do. And I cannot imagine why it could be useful.
