### ISSUE TITLE
Screenshots no longer available

### ISSUE THREAD

**Issue by afamee** [selenide/selenide#814]
## The problem
I no longer get the screenshots upon failure ever since I upgraded from Selenide 2.17 to Selenide 4.12.
For the longest time, I had a very old Selenide code for reasons that are isolated to my setup. Finally I found a way to work around the issue hindering my upgrade. So I took a big leap and upgraded from Selenide 2.17 to 4.12. I was really excited considering I have now new api's at my disposal. I must say my expectation has not been met.

- Practically every failure has failed without a screenshot that I am used to which makes it difficult to see what was on the screen upon failure
- I get frequently now **NotFoundElement** Failures. Upon update i noticed quite some deprecated functions which I updated to most suitable apis. Now It seems my tests is a bit unstable which I am currently investigation to find out the root cause. I use a lot of should(Condition.appear, 2500).click() type calls around my code to ensure the elements have enough time to be rendered before the click.

## Tell us about your environment
**Selenide 4.12.2**
**Firefox 61.0.1**
**Selenium-firefox-driver 3.13.0** 
**Selenium 3.13.0**
**Windows 10 Pro**
**Fitnesse-20180127**

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**To reproduce:**
$Open any page of a given site
$Click on a element that is not there

It should throw a ElementNotFoundException and suppose to show a screenshot path to where the page is stored.

**Comment by plagov** [comment]
This is a very basic functionality that works perfectly. And without your code example, it is impossible to see what is the problem you're experiencing.

**Comment by plagov** [comment]
Stacktrace is impossible to read, it is uploaded as a screenshot that doesn't appear in full size. Place it as a plain text here.

Also, `Condition.appear` is deprecated. Better to use `Condition.visible`. And what is the `policy_num`? Do you define this variable?

I tried to reproduce your issue with the following test:

```java
  @Test
  public void scrapePolicyNumber(){
    open("https://www.google.com/");
    $("#PolicySummary_PolicyNumber span").shouldBe(appear).getText();
  }
```
As expected - it failed, I get a `NoSuchElementException` and screenshot was created. You can try the same test on your side and see that the result will be the same.

**Comment by afamee** [comment]
@plagov Thank you for all your efforts. I am not so sure how the stacktrace will be helpful to you but here it is. It should be plainly seen that there is no screenshot shown here. There might be something I am missing but its not yet apparent to me. I assume that you are staging similar environment as I noted above. Thanks again.

org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#PolicySummary_PolicyNumber span"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'WCD00065', ip: '172.19.30.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.41.578737 (49da6702b16031..., userDataDir: C:\Users\AFAMOK~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:62067}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 68.0.3440.106, webStorageEnabled: true}
Session ID: 8bf44916b4dae5a2a81d33ecf1fb6765
*** Element info: {Using=css selector, value=#PolicySummary_PolicyNumber span}
	at sun.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:416)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
	at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:29)
	at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:56)
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:44)
	at com.codeborne.selenide.commands.Should.should(Should.java:35)
	at com.codeborne.selenide.commands.Should.execute(Should.java:29)
	at com.codeborne.selenide.commands.Should.execute(Should.java:12)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:144)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:90)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
	at com.sun.proxy.$Proxy0.shouldBe(Unknown Source)
	at cse.regress.features.BORFixture.scrapePolicyNumber(BORFixture.java:190)
	at cse.regress.features.BORFixture.startBrokerOfRecord(BORFixture.java:46)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fitlibrary.closure.MethodClosure.invoke(MethodClosure.java:49)
	at fitlibrary.closure.MethodClosure.invokeTyped(MethodClosure.java:35)
	at fitlibrary.closure.CalledMethodTarget.invokeTyped(CalledMethodTarget.java:83)
	at fitlibrary.closure.CalledMethodTarget.invokeTyped(CalledMethodTarget.java:103)
	at fitlibrary.traverse.workflow.caller.DoActionCaller.run(DoActionCaller.java:40)
	at fitlibrary.traverse.workflow.DispatchRowInFlow.pickAndRunValidCaller(DispatchRowInFlow.java:98)
	at fitlibrary.traverse.workflow.DispatchRowInFlow.interpretRow(DispatchRowInFlow.java:61)
	at fitlibrary.traverse.workflow.DoTraverse.interpretRowBeforeWrapping(DoTraverse.java:99)
	at fitlibrary.traverse.workflow.DoTraverse.interpretRow(DoTraverse.java:96)
	at fitlibrary.flow.DoFlowOnTable.runTable(DoFlowOnTable.java:80)
	at fitlibrary.flow.DoFlowOnTable.runTable(DoFlowOnTable.java:56)
	at fitlibrary.flow.DoFlow.runTable(DoFlow.java:104)
	at fitlibrary.flow.DoFlow.runSingleTable(DoFlow.java:89)
	at fitlibrary.flow.DoFlowWithExtraTableAddedWhenNeeded.runStorytest(DoFlowWithExtraTableAddedWhenNeeded.java:33)
	at fitlibrary.suite.BatchFitLibrary.doTables(BatchFitLibrary.java:92)
	at fitlibrary.suite.BatchFitLibrary.doStorytest(BatchFitLibrary.java:50)
	at fitlibrary.suite.BatchFitLibrary.doTables(BatchFitLibrary.java:107)
	at fitlibrary.suite.FitLibraryServer.doTables(FitLibraryServer.java:36)
	at fitlibrary.suite.FitLibraryServer.doTables(FitLibraryServer.java:28)
	at fit.FitServerBridge.process(FitServerBridge.java:76)
	at fit.FitServerBridge.run(FitServerBridge.java:60)
	at fitlibrary.suite.FitLibraryServer.main(FitLibraryServer.java:54)

**Comment by plagov** [comment]
Check also your Selenide configurations - class with configurations or command line arguments. If your test spawns Chrome, while Selenide by default uses Firefox, that means that somewhere in your project you define configurations.

**Comment by afamee** [comment]
I have checked my selenide configurations. In no place did I explicitly turn off screenshots. I make few setProperty calls like below:

`System.setProperty("selenide.browser", browser.equalsIgnoreCase("chrome") ? "chrome" : "firefox");`

Before calling the open(url)

Just now, in an entirely different test within the same suite sharing the same setup and codebase, now I see screenshot included. So now am perplexed! 

Element should not visible {By.className: error_content}
Element: '
ATTENTION!
Quote has not been saved. Please select a customer before binding the quote.
'
**Screenshot: file:/C:/workspace2/CSERegression_Projects/build/reports/tests/1538083392498.0.png
Page source: file:/C:/workspace2/CSERegression_Projects/build/reports/tests/1538083392498.0.html**
Timeout: 4 s.
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:63)
	at com.codeborne.selenide.commands.ShouldNot.shouldNot(ShouldNot.java:36)
	at com.codeborne.selenide.commands.ShouldNot.execute(ShouldNot.java:29)
	at com.codeborne.selenide.commands.ShouldNot.execute(ShouldNot.java:12)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:144)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:90)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
	at com.sun.proxy.$Proxy2.shouldNot(Unknown Source)
	at cse.prod.suite.spinn.smoke.base.comm.quote.ca.auto.AutoPolicy.fillOutForm(AutoPolicy.java:375)
	at cse.prod.suite.spinn.smoke.base.comm.quote.ca.auto.AutoPolicyNXG.fillAutoPolicyTabInfo(AutoPolicyNXG.java:128)
	at cse.prod.suite.spinn.smoke.base.LegacyEntry.fillTabInfo(LegacyEntry.java:128)
	at cse.prod.suite.spinn.smoke.fixtures.SpinnFixtures.fillTab(SpinnFixtures.java:347)
	at cse.prod.suite.spinn.smoke.fixtures.SpinnFixtures.userCanFillOutTabInformation(SpinnFixtures.java:322)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fitlibrary.closure.MethodClosure.invoke(MethodClosure.java:49)
	at fitlibrary.closure.MethodClosure.invokeTyped(MethodClosure.java:35)
	at fitlibrary.closure.CalledMethodTarget.invokeTyped(CalledMethodTarget.java:83)
	at fitlibrary.closure.CalledMethodTarget.invokeTyped(CalledMethodTarget.java:103)
	at fitlibrary.traverse.workflow.caller.DoActionCaller.run(DoActionCaller.java:40)
	at fitlibrary.traverse.workflow.DispatchRowInFlow.pickAndRunValidCaller(DispatchRowInFlow.java:98)
	at fitlibrary.traverse.workflow.DispatchRowInFlow.interpretRow(DispatchRowInFlow.java:61)
	at fitlibrary.traverse.workflow.DoTraverse.interpretRowBeforeWrapping(DoTraverse.java:99)
	at fitlibrary.traverse.workflow.DoTraverse.interpretRow(DoTraverse.java:96)
	at fitlibrary.flow.DoFlowOnTable.runTable(DoFlowOnTable.java:80)
	at fitlibrary.flow.DoFlowOnTable.runTable(DoFlowOnTable.java:56)
	at fitlibrary.flow.DoFlow.runTable(DoFlow.java:104)
	at fitlibrary.flow.DoFlow.runSingleTable(DoFlow.java:89)
	at fitlibrary.flow.DoFlowWithExtraTableAddedWhenNeeded.runStorytest(DoFlowWithExtraTableAddedWhenNeeded.java:33)
	at fitlibrary.suite.BatchFitLibrary.doTables(BatchFitLibrary.java:92)
	at fitlibrary.suite.BatchFitLibrary.doStorytest(BatchFitLibrary.java:50)
	at fitlibrary.suite.BatchFitLibrary.doTables(BatchFitLibrary.java:107)
	at fitlibrary.suite.FitLibraryServer.doTables(FitLibraryServer.java:36)
	at fitlibrary.suite.FitLibraryServer.doTables(FitLibraryServer.java:28)
	at fit.FitServerBridge.process(FitServerBridge.java:76)
	at fit.FitServerBridge.run(FitServerBridge.java:60)
	at fitlibrary.suite.FitLibraryServer.main(FitLibraryServer.java:54)

**Comment by afamee** [comment]
Upon a closer observation between the two different stacktraces I have provided thus far, I noticed that the ones that terminate with codeborne code does actually generate screenshots but the ones that terminates either in Selenium library code or Java does not. I don't know if it makes any difference but wanted to call

**Comment by afamee** [comment]
Would there ever going to be an answer to my question?

**Comment by asolntsev** [comment]
@afamee Probably you are not copying the full stack trace. 
I see only `org.openqa.selenium.NoSuchElementException` in your stack trace, but Selenide throws `ElementNotFound` exception which wraps the original `NoSuchElementException` and adds screenshot to it. 

Look, this is how classical Selenide exception looks like. You probably copy only the part below "Caused by" phrase:

```
Element not found {#PolicySummary_PolicyNumber span}
Expected: visible

Screenshot: file:/Users/andrei/projects/selenide/statics/build/reports/tests/1540384401469.1.png
Page source: file:/Users/andrei/projects/selenide/statics/build/reports/tests/1540384401469.1.html
Timeout: 4 s.
Caused by: NoSuchElementException: Unable to locate element: #PolicySummary_PolicyNumber span
	at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:34)
```

**Comment by afamee** [comment]
> 
> 
> @afamee Probably you are not copying the full stack trace.
> I see only `org.openqa.selenium.NoSuchElementException` in your stack trace, but Selenide throws `ElementNotFound` exception which wraps the original `NoSuchElementException` and adds screenshot to it.
> 
> Look, this is how classical Selenide exception looks like. You probably copy only the part below "Caused by" phrase:
> 
> ```
> Element not found {#PolicySummary_PolicyNumber span}
> Expected: visible
> 
> Screenshot: file:/Users/andrei/projects/selenide/statics/build/reports/tests/1540384401469.1.png
> Page source: file:/Users/andrei/projects/selenide/statics/build/reports/tests/1540384401469.1.html
> Timeout: 4 s.
> Caused by: NoSuchElementException: Unable to locate element: #PolicySummary_PolicyNumber span
> 	at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:34)
> ```

@asolntsev Exactly Andrei. That was what I was expecting but not in my case. What I have pasted before and now again below is the entire stacktrace from beginning to end with nothing missing. 

Here is the line of code where it happens: Is this not a selenide call?
```
	public void scrapePolicyNumber(){
		final String POLICY_LOC = "#PolicySummary_PolicyNumber span";
		
		policy_num = $(POLICY_LOC).shouldBe(Condition.appear).getText();
	}
```
So the call to **$(POLICY_LOC).shouldBe(Condition.appear).getTex**t for the given element failed because the page that was expected was not loaded for whatever reason. I expected to see the screenshot of what was on the screen when the NoSuchElementException was thrown but nothing ...

This feature I understand as @plagov noted is basic and has always worked for me in the older selenide build but since I made this upgrade to the recent libraries, it is no longer showing for me.


```
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#PolicySummary_PolicyNumber span"}
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'WCD00065', ip: '172.19.30.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.41.578737 (49da6702b16031..., userDataDir: C:\Users\AFAMOK~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:53137}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 69.0.3497.100, webStorageEnabled: true}
Session ID: 0092607e8af1a84ec48a210dfd48a534
*** Element info: {Using=css selector, value=#PolicySummary_PolicyNumber span}
	at sun.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:416)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
	at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:29)
	at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:56)
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:44)
	at com.codeborne.selenide.commands.Should.should(Should.java:35)
	at com.codeborne.selenide.commands.Should.execute(Should.java:29)
	at com.codeborne.selenide.commands.Should.execute(Should.java:12)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:144)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:90)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
	at com.sun.proxy.$Proxy0.shouldBe(Unknown Source)
	at cse.regress.features.BORFixture.scrapePolicyNumber(BORFixture.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fitlibrary.closure.MethodClosure.invoke(MethodClosure.java:49)
	at fitlibrary.closure.MethodClosure.invokeTyped(MethodClosure.java:35)
	at fitlibrary.closure.CalledMethodTarget.invokeTyped(CalledMethodTarget.java:83)
	at fitlibrary.closure.CalledMethodTarget.invokeTyped(CalledMethodTarget.java:103)
	at fitlibrary.traverse.workflow.caller.DoActionCaller.run(DoActionCaller.java:40)
	at fitlibrary.traverse.workflow.DispatchRowInFlow.pickAndRunValidCaller(DispatchRowInFlow.java:98)
	at fitlibrary.traverse.workflow.DispatchRowInFlow.interpretRow(DispatchRowInFlow.java:53)
	at fitlibrary.traverse.workflow.DoTraverse.interpretRowBeforeWrapping(DoTraverse.java:99)
	at fitlibrary.traverse.workflow.DoTraverse.interpretRow(DoTraverse.java:96)
	at fitlibrary.flow.DoFlowOnTable.runTable(DoFlowOnTable.java:80)
	at fitlibrary.flow.DoFlowOnTable.runTable(DoFlowOnTable.java:56)
	at fitlibrary.flow.DoFlow.runTable(DoFlow.java:104)
	at fitlibrary.flow.DoFlow.runSingleTable(DoFlow.java:89)
	at fitlibrary.flow.DoFlowWithExtraTableAddedWhenNeeded.runStorytest(DoFlowWithExtraTableAddedWhenNeeded.java:33)
	at fitlibrary.suite.BatchFitLibrary.doTables(BatchFitLibrary.java:92)
	at fitlibrary.suite.BatchFitLibrary.doStorytest(BatchFitLibrary.java:50)
	at fitlibrary.suite.BatchFitLibrary.doTables(BatchFitLibrary.java:107)
	at fitlibrary.suite.FitLibraryServer.doTables(FitLibraryServer.java:36)
	at fitlibrary.suite.FitLibraryServer.doTables(FitLibraryServer.java:28)
	at fit.FitServerBridge.process(FitServerBridge.java:76)
	at fit.FitServerBridge.run(FitServerBridge.java:60)
	at fitlibrary.suite.FitLibraryServer.main(FitLibraryServer.java:54)
```

**Comment by BorisOsipov** [comment]
@afamee Also, as I see you use Fitness and this code runs in fuxture. Maybe this fixture somehow handle errors additianaly and print only e.g. `error.getCause()`? Can you check?

**Comment by asolntsev** [comment]
@afamee I cannot reproduce your issue. :( Without it, I am afraid we cannot fix it.

Did you try the previous suggestion by BorisOsipov?

**Comment by afamee** [comment]
@asolntsev Thank you Andrei. I tried tracing the code.. I found out that at this line below, 

> Error wrappedError = UIAssertionError.wrap(error, timeoutMs);

the stacktrace contains the **screenshot** but somewhere along the line, it gets truncated. So it could be as @BorisOsipov guessed that Fitnesse swallowing the original error.

@Override
  public Object invoke(Object proxy, Method method, Object... args) throws Throwable {
    if (methodsToSkipLogging.contains(method.getName()))
      return Commands.getInstance().execute(proxy, webElementSource, method.getName(), args);

    validateAssertionMode();

    long timeoutMs = getTimeoutMs(method, args);
    long pollingIntervalMs = getPollingIntervalMs(method, args);
    SelenideLog log = SelenideLogger.beginStep(webElementSource.getSearchCriteria(), method.getName(), args);
    try {
      Object result = dispatchAndRetry(timeoutMs, pollingIntervalMs, proxy, method, args);
      SelenideLogger.commitStep(log, PASS);
      return result;
    }
    catch (Error error) {
      Error wrappedError = UIAssertionError.wrap(error, timeoutMs);
      SelenideLogger.commitStep(log, wrappedError);
      if (assertionMode == SOFT && methodsForSoftAssertion.contains(method.getName()))
        return proxy;
      else
        throw wrappedError;
    }
    catch (RuntimeException error) {
      SelenideLogger.commitStep(log, error);
      throw error;
    }
  }

I am still digging through but you can close the ticket if you need to. thank you for your time and great work on this tool. Makes everything simple. Since I started using it, I have not gone back.

**Comment by darklynx** [comment]
Interesting, we also have experienced similar issue with a major switch from Selenide ver `3.7` to `5.0.1` - the screenshot for failed tests have disappeared. Still trying to figure out the true cause.

@afamee have you found anything?

**Comment by darklynx** [comment]
Partially our problems are related to the issue #880
But I still do not see some screenshots for failed tests that in past were properly generated.
