### ISSUE TITLE
Got java.lang.NoClassDefFoundError: org/openqa/selenium/InvalidArgumentException on simple test

### ISSUE THREAD

**Issue by EreminD** [selenide/selenide#842]
Hello team

I've got pretty simple test (kotlin or java - it doesn't matter)

`   
@Test 
fun test() {
open("http://ya.ru")
}
`
When I start, it throws me thus exception:
`
java.lang.NoClassDefFoundError: org/openqa/selenium/InvalidArgumentException

	at com.codeborne.selenide.webdriver.WebDriverFactory.<init>(WebDriverFactory.java:21)
	at com.codeborne.selenide.drivercommands.LazyDriver.<init>(LazyDriver.java:33)
	at com.codeborne.selenide.SelenideDriver.<init>(SelenideDriver.java:38)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.lambda$getSelenideDriver$0(WebDriverThreadLocalContainer.java:58)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getSelenideDriver(WebDriverThreadLocalContainer.java:57)
	at com.codeborne.selenide.WebDriverRunner.getSelenideDriver(WebDriverRunner.java:96)
	at com.codeborne.selenide.Selenide.open(Selenide.java:38)
	at com.rencap.fxmm.webback.single.uat.ui.FirstTest.test(FirstTest.kt:15)
`

I tried to set path to chrome driver:
`
    @Before
    fun setUp() {
        System.setProperty("selenide.browser", "chrome")
        System.setProperty("webdriver.chrome.driver", "path to chromedriver.exe")
    }
`

But it didn't help

If I'm right, the problem is in com.codeborne.selenide.impl.WebDriverThreadLocalContainer#getSelenideDriver because 
`new SelenideDriver(new StaticConfig(), userProvidedProxy, listeners)` throws 'java.lang.NoClassDefFoundError' exception.

## Tell us about your environment
* **Selenide Version: 5.0.0**

Thank you

**Comment by BorisOsipov** [comment]
@EreminD show us `mvn dependency:tree` output

**Comment by BorisOsipov** [comment]
Discussed here https://automated-testing.info/t/c-selenide-ochen-legko-nachat-avtomatizaiyu-testirovaniya/21728

Spring boot adds old selenium versions. You need to check and fix your selenium dependencies.
