### ISSUE TITLE
No webdriver is bound to current thread: 14. You need to call open(url) first when I try to run tests in parallel(TestNG)

### ISSUE THREAD

**Issue by ganzolik1234** [selenide/selenide#863]
## The problem
When I try to run tests in parallel (testng xml suite) I receive error: com.codeborne.selenide.ex.SoftAssertionError: java.lang.IllegalStateException: No webdriver is bound to current thread: 14. You need to call open(url) first. 

But If I run tests in one thread this problem doesn't reproduce.

## Details

Steps to reproduce;
1. Run testng suite xml file (src->test->resources->Parallel.xml). (I use parallelization by tests tags in xml-file) 

If you run all test classes in one thread you'll see that tests will run normally.

In Selenide version 4.12.3 there aren't this problem.

## Tell us about your environment
* **Selenide Version: 5.0.1**
* **TestNG version: 6.11**

## Code To Reproduce Issue [ Good To Have ]
Link to github repository to reproduce this situation:
https://github.com/ganzolik1234/TestNGSelenideParallel2;

**Comment by BorisOsipov** [comment]
It is testng issue - it runs @BeforeClass and @Test in differend threads.
See https://github.com/cbeust/testng/issues/1335

I've updated your deps to `compile 'org.testng:testng:6.14.3'` and it help.

**Comment by BorisOsipov** [comment]
Problem appears when uses softasserts
```
com.codeborne.selenide.ex.SoftAssertionError: java.lang.IllegalStateException: No webdriver is bound to current thread: 13. You need to call open(url) first.

	at com.codeborne.selenide.logevents.ErrorsCollector.failIfErrors(ErrorsCollector.java:30)
	at com.codeborne.selenide.testng.SoftAsserts.failIfErrors(SoftAsserts.java:83)
	at com.codeborne.selenide.testng.SoftAsserts.onTestFailure(SoftAsserts.java:27)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:63)
	at org.testng.internal.Invoker.runTestResultListener(Invoker.java:1516)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:708)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:589)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:437)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:70)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by BorisOsipov** [comment]
It is not softasserts. In your example your your `Test` class extends `PageObject` class. So when testng runs test it instantiates `Test` instance in thread №1, so all your page object elements bounded to thread №1.

To fix it just get rid of such inheritance.

**Comment by plagov** [comment]
@ganzolik1234 see description in 5.0.0 release notes under _Selenide doesn’t open a browser automatically_ header: https://selenide.org/2018/10/10/selenide-5.0.0/

In short, define an instance of page object class and instantiate it in `@BeforeMethod`, like:

```java
private HomePage homePage;

@BeforeMethod
public void setUp() {
  homePage = new HomePage();
}
```

I had the same issue and this solution helped me.

**Comment by RashmiPrashant** [comment]
> @ganzolik1234 see description in 5.0.0 release notes under _Selenide doesn’t open a browser automatically_ header: https://selenide.org/2018/10/10/selenide-5.0.0/
> 
> In short, define an instance of page object class and instantiate it in `@BeforeMethod`, like:
> 
> ```java
> private HomePage homePage;
> 
> @BeforeMethod
> public void setUp() {
>   homePage = new HomePage();
> }
> ```
> 
> I had the same issue and this solution helped me.
