### ISSUE TITLE
selenide has issues for intellij 2018.3 users

### ISSUE THREAD

**Issue by symonk** [selenide/selenide#875]
Hi, I use 2018.3 intellij ultimate and running tests from a fresh clone was a real headache.  After some investigating (I'm not very familiar with gradle) we should consider adding the following:

```
  testRuntime("org.junit.platform:junit-platform-launcher:$platformVersion")
  testRuntime("org.junit.vintage:junit-vintage-engine:$junitVersion")
```

I also had problems around $junitVersion 5.3.2 and had to use 5.0.1.

```win 7 ultimate x64
IntelliJ IDEA 2018.3 (Ultimate Edition)
Build #IU-183.4284.148, built on November 21, 2018
Licensed to IntelliJ IDEA Evaluator
Expiration date: January 4, 2019
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```

Maybe I am doing something wrong with gradle? but it is impossible to work effectively because I cannot run my integration tests singularly without adding/changing these values for me.

**Comment by vinogradoff** [comment]
What’s setup once again you have problems with?


5.0.1 and JUnit 5.3.2 with gradle?


does it work from CLI: gradle test?

does it work when you start in IDE?

Viele Grüße

Alexei Vinogradov

On 5. December 2018 at 21:40:34, Sy (notifications@github.com) wrote:

Hi, I use 2018.3 intellij ultimate and running tests from a fresh clone was
a real headache. After some investigating (I'm not very familiar with
gradle) we should consider adding the following:

  testRuntime("org.junit.platform:junit-platform-launcher:$platformVersion")
  testRuntime("org.junit.vintage:junit-vintage-engine:$junitVersion")

I also had problems around $junitVersion 5.3.2 and had to use 5.0.1.

IntelliJ IDEA 2018.3 (Ultimate Edition)
Build #IU-183.4284.148, built on November 21, 2018
Licensed to IntelliJ IDEA Evaluator
Expiration date: January 4, 2019
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1```

Maybe I am doing something wrong with gradle? but it is impossible to
run tests without adding/changing these values for me.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/selenide/selenide/issues/875>, or mute the thread

**Comment by symonk** [comment]
@vinogradoff thanks I will confirm the setup tomorrow, I have changed a lot of things to focus on some PR work for now and I can't fully recall, but I will reset and document the problems and report here later.

**Comment by vinogradoff** [comment]
on a side note, as I've upgraded from 2018.2 to 2018.3 recently, the project could not be built from IDEA. It looks like a bug of IDEA, and one-time restart helped. I've built selenide several times since that.

**Comment by symonk** [comment]
ok I will put up some info on my lunchbreak today, I think the problem I had was around junit5 and Optional.  will put exact errors and how I fixed it later today.

**Comment by symonk** [comment]
with a default import of selenide into IDEA 2018.3 we see the following:

```
Test ignored.
java.lang.NoSuchMethodError: org.junit.jupiter.api.extension.ExtensionContext.getTestInstanceLifecycle()Ljava/util/Optional;
Process finished with exit code -1
```

**Comment by vinogradoff** [comment]
Do you mean reproduction:

1. install 2018.3
2. git clone selenide
3. standard import
4. build from idea...? Or what?

Viele Grüße

Alexei Vinogradov

**Comment by symonk** [comment]
1. `git clone <selenide-fork>`
2. import gradle project into IDEA 2018.2.2 / 2018.3
3. select ok on gradle with auto-import option
5. gradle build
6. weird issue here like you say, reboot required for imports to work
6. choose 1 integration test, right click test method and run it (canTakeSnapshotOfCollection())
7. Failure:

```ava.lang.NoSuchMethodError: org.junit.jupiter.api.extension.ExtensionContext.getTestInstanceLifecycle()Ljava/util/Optional;

	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:186)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:74)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Test ignored.
```


Again, I don't really have experience with gradle, am I doing something incorrect here?

**Comment by symonk** [comment]
here is the problem:

```testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitVersion")``` 

should be something like: 

```compile("org.junit.jupiter:junit-jupiter-engine:$junitVersion")```

?

**Comment by rosolko** [comment]
@symonk 
Can confirm issue, but it's going not from Idea 2018.3 incompatibility - it's going from gradle 5 version. Looks like they tune dependency resolution a little bit.
In result we should move out `junit-jupiter-engine` from `testRuntimeOnly` level, and not to `testCompile` but to `testImplementation`.
Test it with this config and if this will works i'll made changes in a master directly

**Comment by symonk** [comment]
sure thing!

**Comment by symonk** [comment]
need your feedback on #891, works nicely for junit engine
