### ISSUE TITLE
NPE on open, when driver set by WebDriverRunner.setWebDriver() and proxy is on

### ISSUE THREAD

**Issue by BorisOsipov** [selenide/selenide#878]
## Code To Reproduce Issue [ Good To Have ]
```
    @Test
    public void test() {
        Configuration.fileDownload = FileDownloadMode.PROXY;
        Configuration.proxyEnabled = true;
        WebDriverRunner.setWebDriver(new ChromeDriver());
        WebDriverRunner.getWebDriver().navigate().to("https://github.com/");
        WebDriverRunner.getWebDriver().manage().window().maximize();
        open("http://admin:admin@the-internet.herokuapp.com/basic_auth");
    }
```

## Details
```
java.lang.NullPointerException
	at com.codeborne.selenide.drivercommands.Navigator.basicAuthRequestFilter(Navigator.java:45)
	at com.codeborne.selenide.drivercommands.Navigator.beforeNavigateToWithProxy(Navigator.java:101)
	at com.codeborne.selenide.drivercommands.Navigator.beforeNavigateTo(Navigator.java:88)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:62)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:24)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:59)
	at com.codeborne.selenide.Selenide.open(Selenide.java:39)
	at FirstTestClass.test1(FirstTestClass.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
```

## Tell us about your environment
* **Selenide Version:*5.0.1*

**Comment by BorisOsipov** [comment]
Selenide mustn't throw ugly NPE

**Comment by symonk** [comment]
what do you prefer in this instance?  issue lies with: https://github.com/selenide/selenide/blob/e5d2d3bf738628f90ba7b0af97c80359b1e3f055/src/main/java/com/codeborne/selenide/drivercommands/Navigator.java#L101

because selenideProxy is null from:

```
  @Override
  public SelenideProxyServer getProxy() {
    return null;
  }```

**Comment by asolntsev** [comment]
@symonk @BorisOsipov I suggest just showing a better error message. For example:

> java.lang.IllegalStateException: config.proxyEnabled == true but proxy server is not started. 


I created a pull request, please take a look: https://github.com/selenide/selenide/pull/888
