### ISSUE TITLE
NPE on opening WebDriver to remote Selenium HUB

### ISSUE THREAD

**Issue by mplushnikov** [selenide/selenide#887]
I'm trying to update our test-project from selenide 4.12.3 to current version.
Unfortunately I'm getting a NullPointerException during initialization:

```
Dez 12, 2018 3:33:00 PM com.codeborne.selenide.drivercommands.LazyDriver getAndCheckWebDriver
INFORMATION: No webdriver is bound to current thread: 1 - let's create a new webdriver

org.openqa.selenium.WebDriverException: Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:42:16'
System info: host: 'XXX-9044', ip: '10.11.16.55', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: SelenideDriver
selenide.url: https://livetest....intern.de/user-service/auth/realms/customer/protocol/openid-connect/forgot-credentials?response_type=none&redirect_uri=https://livetest....intern.de/customer-portal/&client_id=customerPortalBff
selenide.baseUrl: http://localhost:8080
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at com.codeborne.selenide.webdriver.RemoteDriverFactory.createRemoteDriver(RemoteDriverFactory.java:35)
	at com.codeborne.selenide.webdriver.RemoteDriverFactory.create(RemoteDriverFactory.java:29)
	at com.codeborne.selenide.webdriver.WebDriverFactory.lambda$createWebDriver$1(WebDriverFactory.java:55)
	at java.util.Optional.map(Optional.java:215)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:55)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:38)
	at com.codeborne.selenide.drivercommands.LazyDriver.createDriver(LazyDriver.java:93)
	at com.codeborne.selenide.drivercommands.LazyDriver.getAndCheckWebDriver(LazyDriver.java:87)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:143)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:61)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:24)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:59)
	at com.codeborne.selenide.Selenide.open(Selenide.java:39)
	at e2etest.util.ForgotPassword.changePassword(ForgotPassword.java:43)
	at e2etest.CustomerForgotPasswordSteps.customerCreatesNewPassword(CustomerForgotPasswordSteps.java:36)
	at ✽.ein Privatkunde ein neues Passwort vergibt(IdeaProjects/staged-end2end-tests/src/test/resources/features/CustomerForgotPassword.feature:14)
Caused by: java.lang.NullPointerException
```
The same error occured if i try selenide 4.13.0

It works perfect with selenide 4.12.3:
```
Dez 12, 2018 3:28:28 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer getWebDriver
INFORMATION: No webdriver is bound to current thread: 1 - let's create new webdriver
Dez 12, 2018 3:28:31 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFORMATION: Detected dialect: OSS
Dez 12, 2018 3:28:33 PM com.codeborne.selenide.webdriver.WebDriverFactory logBrowserVersion
INFORMATION: BrowserName=chrome Version=69.0.3497.100 Platform=XP
Dez 12, 2018 3:28:33 PM com.codeborne.selenide.webdriver.WebDriverFactory createWebDriver
INFORMATION: Selenide v. 4.12.3
Dez 12, 2018 3:28:33 PM com.codeborne.selenide.impl.WebDriverThreadLocalContainer createDriver
INFORMATION: Create webdriver in current thread 1: RemoteWebDriver -> RemoteWebDriver: chrome on XP (754c57ef-31be-4f05-98ed-6d4baa3af5f8)
.....
```

We use pretty standard Configuration:
Configuration.browser = CHROME;
Configuration.timeout = TimeUnit.SECONDS.toMillis(10);
Configuration.savePageSource = false;
Configuration.remote = "http://jenkins....intern.de:4444/wd/hub";

**Comment by asolntsev** [comment]
@mplushnikov Could you please share the **full stack trace**? The most valuable part is **after** `Caused by: java.lang.NullPointerException`

**Comment by symonk** [comment]
@mplushnikov please post up your test code too.

**Comment by sadsridh** [comment]
I am trying to update Selenide from version 4.8 to 5.2.0
I am getting the below error when running the test on Jenkins running Grid 2 version 2.53
Posting this issue here because I am not sure if the errors I am seeing is due to a Selenium Grid version mismatch or due to https://github.com/selenide/selenide/issues/873 
However I do not have any selenide element being declared before open() and the failure happens in my setupSpec() where I call open(URL)

**STACK TRACE:**

`java.lang.IllegalArgumentException: org.openqa.selenium.WebDriverException: Unable to parse remote response: <html><head><title>Selenium Grid2.0 help</title></head><body>You are using grid 2.53.0<br>Find help on the official selenium wiki : <a href='https://github.com/SeleniumHQ/selenium/wiki/Grid2' >more help here</a><br>default monitoring page : <a href='/grid/console' >console</a></body></html>
	at com.codeborne.selenide.webdriver.AbstractDriverFactory.createInstanceOf(AbstractDriverFactory.java:52)
	at com.codeborne.selenide.webdriver.DefaultDriverFactory.create(DefaultDriverFactory.java:16)
	at com.codeborne.selenide.webdriver.WebDriverFactory.lambda$createWebDriver$2(WebDriverFactory.java:56)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:56)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:38)
	at com.codeborne.selenide.drivercommands.LazyDriver.createDriver(LazyDriver.java:93)
	at com.codeborne.selenide.drivercommands.LazyDriver.getAndCheckWebDriver(LazyDriver.java:87)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:143)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:61)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:24)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:59)
	at com.codeborne.selenide.Selenide.open(Selenide.java:39)
	at atg.cloud.controls.business.Browser.openAdminLoginPage(Browser.java:106)
	at atg.cloud.core.AdminUISpec.setupSpec(AdminUISpec.groovy:47)
Caused by: org.openqa.selenium.WebDriverException: Unable to parse remote response: <html><head><title>Selenium Grid2.0 help</title></head><body>You are using grid 2.53.0<br>Find help on the official selenium wiki : <a href='https://github.com/SeleniumHQ/selenium/wiki/Grid2' >more help here</a><br>default monitoring page : <a href='/grid/console' >console</a></body></html>
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at atg.cloud.core.webdriver.CustomWebDriverProvider.createDriver(CustomWebDriverProvider.java:74)
	at com.codeborne.selenide.webdriver.AbstractDriverFactory.createInstanceOf(AbstractDriverFactory.java:44)
	... 14 more

**THIS PART OF THE ERROR MAKES ME THINK ITS THE GRID VERSION MISMATCH**
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'bus00ceu.us.oracle.com', ip: '10.196.1.69', os.name: 'Linux', os.arch: 'amd64', os.version: '4.1.12-124.19.2.el6uek.x86_64', java.version: '1.8.0_181'
Driver info: driver.version: SelenideDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:122)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:140)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)
	at org.openqa.selenium.json.Json.toType(Json.java:69)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:112)
	... 22 more`

**STANDARD ERROR**
`Feb 22, 2019 10:23:33 PM com.codeborne.selenide.drivercommands.LazyDriver getAndCheckWebDriver
INFO: No webdriver is bound to current thread: 12 - let's create a new webdriver
Feb 22, 2019 10:23:33 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
java.lang.IllegalStateException: No webdriver is bound to current thread: 12. You need to call open(url) first.
java.lang.IllegalStateException: No webdriver is bound to current thread: 12. You need to call open(url) first.
java.lang.IllegalStateException: No webdriver is bound to current thread: 12. You need to call open(url) first.
	at com.codeborne.selenide.drivercommands.LazyDriver.getWebDriver(LazyDriver.java:67)
	at com.codeborne.selenide.SelenideDriver.getWebDriver(SelenideDriver.java:139)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getWebDriver(WebDriverThreadLocalContainer.java:68)
	at com.codeborne.selenide.WebDriverRunner.getWebDriver(WebDriverRunner.java:71)
	at com.codeborne.selenide.WebDriverRunner$getWebDriver.call(Unknown Source)
	at atg.cloud.core.CCBaseTest.cleanupSpec(CCBaseTest.groovy:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:153)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:84)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
	at org.spockframework.runtime.BaseSpecRunner.doRunCleanupSpec(BaseSpecRunner.java:222)
	at org.spockframework.runtime.BaseSpecRunner$4.invoke(BaseSpecRunner.java:207)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
	at org.spockframework.runtime.BaseSpecRunner.runCleanupSpec(BaseSpecRunner.java:200)
	at org.spockframework.runtime.BaseSpecRunner.doRunCleanupSpec(BaseSpecRunner.java:224)
	at org.spockframework.runtime.BaseSpecRunner$4.invoke(BaseSpecRunner.java:207)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
	at org.spockframework.runtime.BaseSpecRunner.runCleanupSpec(BaseSpecRunner.java:200)
	at org.spockframework.runtime.BaseSpecRunner.doRunCleanupSpec(BaseSpecRunner.java:224)
	at org.spockframework.runtime.BaseSpecRunner$4.invoke(BaseSpecRunner.java:207)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
	at org.spockframework.runtime.BaseSpecRunner.runCleanupSpec(BaseSpecRunner.java:200)
	at org.spockframework.runtime.BaseSpecRunner.runCleanupSpec(BaseSpecRunner.java:195)
	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:99)
	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:84)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:76)
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:67)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by asolntsev** [comment]
@mplushnikov Any feedback?
