### ISSUE TITLE
How to specify / freeze web driver binary path and avoid any external api calls

### ISSUE THREAD

**Issue by daggerok** [selenide/selenide#895]
Hello, 

as I can see, during Selenide tests, WebDriverManager is always seeking and downloading web driver during test execution. We are running tests in Docker without cache and previously where wasn't any issues with that:

```bash
# ...skipped
    2018-12-20 16:41:54.521  INFO 329 --- [    Test worker] i.g.bonigarcia.wdm.WebDriverManager      : Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver
    2018-12-20 16:41:55.433  INFO 329 --- [    Test worker] i.g.bonigarcia.wdm.WebDriverManager      : Latest version of geckodriver is 0.23.0
    2018-12-20 16:41:55.438  INFO 329 --- [    Test worker] io.github.bonigarcia.wdm.Downloader      : Downloading https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
    2018-12-20 16:41:58.232  INFO 329 --- [    Test worker] io.github.bonigarcia.wdm.Downloader      : Extracting binary from compressed file geckodriver-v0.23.0-linux64.tar.gz
    2018-12-20 16:41:58.425  INFO 329 --- [    Test worker] i.g.bonigarcia.wdm.WebDriverManager      : Exporting webdriver.gecko.driver as /home/e2e/.m2/repository/webdriver/geckodriver/linux64/0.23.0/geckodriver
    2018-12-20 16:42:01.142  INFO 329 --- [ null to remote] o.o.selenium.remote.ProtocolHandshake    : Detected dialect: W3C
    2018-12-20 16:42:01.171  INFO 329 --- [    Test worker] c.c.selenide.webdriver.BrowserResizer    : Set browser size to 1366x768
    2018-12-20 16:42:01.218  INFO 329 --- [    Test worker] c.c.selenide.webdriver.WebDriverFactory  : BrowserName=firefox Version=64.0 Platform=LINUX
    2018-12-20 16:42:01.218  INFO 329 --- [    Test worker] c.c.selenide.webdriver.WebDriverFactory  : Selenide v. 5.1.0
    2018-12-20 16:42:01.219  INFO 329 --- [    Test worker] c.c.selenide.webdriver.WebDriverFactory  : Selenium WebDriver v. 3.14.0 build time: 2018-08-02T20:19:58.91Z
    2018-12-20 16:42:01.219  INFO 329 --- [    Test worker] c.c.s.d.CreateDriverCommand              : Create webdriver in current thread 12: FirefoxDriver -> FirefoxDriver: firefox on LINUX (8c73e2ec-f309-48ea-805a-ac02964452de)
# skipped...
```

but last time we more often facing with issues like that:

```
myapp.web.Web application E2E search tests > should search users by login() FAILED
    io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:612)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:538)
        at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:609)
        at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:538)
        at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:271)
        at com.codeborne.selenide.webdriver.WebDriverBinaryManager.setupFirefox(WebDriverBinaryManager.java:50)
        at com.codeborne.selenide.webdriver.WebDriverBinaryManager.setupBinaryPath(WebDriverBinaryManager.java:15)
        at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:49)
        at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:38)
        at com.codeborne.selenide.drivercommands.LazyDriver.createDriver(LazyDriver.java:93)
        at com.codeborne.selenide.drivercommands.LazyDriver.getAndCheckWebDriver(LazyDriver.java:87)
        at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:143)
        at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:61)
        at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
        at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:67)
        at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:91)
        at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:80)
        at com.codeborne.selenide.Selenide.open(Selenide.java:123)
        at myapp.TestExtensions.openLoginPage(TestExtensions.kt:18)
        at myapp.web.Web application E2E search tests.should search users by login(Web application E2E search tests.kt:68)

        Caused by:
        io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
            at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:165)
            at io.github.bonigarcia.wdm.WebDriverManager.openGitHubConnection(WebDriverManager.java:960)
            at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:975)
            at io.github.bonigarcia.wdm.FirefoxDriverManager.getDrivers(FirefoxDriverManager.java:45)
            at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:628)
            at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:523)
            ... 18 more
```

I think it's because we a running multiple parallel test jobs and github API is not happy anymore about it..
Anyway, can I setup path to firefox gecko web driver binary installed in my docker image via java system settings to avoid seeking githup api to fix that issue? Or WebDriverManager still will be calling GitHub API?

Thanks in advice

---
Regards,
Maksim

**Comment by rosolko** [comment]
Pass `driverManagerEnabled` configuration with `false` value.

**Comment by BorisOsipov** [comment]
@daggerok yes you can

set `webdriver.gecko.driver` env variable in your docker contaner and selenide won't try download it by itself.

**Comment by daggerok** [comment]
Thank you

**Comment by BorisOsipov** [comment]
@daggerok forgot to mention. `webdriver.gecko.driver` value should be path to gecko driver binary.

**Comment by daggerok** [comment]
OK, I can confirm, that @BorisOsipov solution is working fine: adding to JAVA_OPTS `-Dwebdriver.gecko.driver=/usr/bin/geckodriver` solved my issue.

@rosolko solution wasn't tested, because we not tuning WebDriverManger manually and here https://github.com/bonigarcia/webdrivermanager I didn't found mentioned property in WebDriverManager API

Thanks

**Comment by daggerok** [comment]
Thank you, @rosolko, Good to know

And still I decided use system property, for us it's better solution, then just disable driver manager completely. Developers would like to use that feature, only CI parallel docker builds don't needed.

**Comment by vinogradoff** [comment]
There is also system property -Dselenide.driverManagerEnabled just in case
:)

Viele Grüße

Alexei Vinogradov

On 20. December 2018 at 20:31:30, Maksim Kostromin (notifications@github.com)
wrote:

Thank you, @rosolko <https://github.com/rosolko>, Good to know

And still I decided use system property, for us it's better solution, then
just disable driver manager completely. Developers would like to use that
feature, only CI parallel docker builds don't needed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/selenide/selenide/issues/895#issuecomment-449110788>,
or mute the thread

**Comment by daggerok** [comment]
Maybe someone can point me where can I look at full list available system properties supported by Selenide?

**Comment by rosolko** [comment]
https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/SelenideConfig.java

**Comment by BorisOsipov** [comment]
@daggerok Sure see https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/SelenideConfig.java

**Comment by daggerok** [comment]
Awesome!
Thanks guys

**Comment by vinogradoff** [comment]
https://github.com/selenide/selenide/blob/master/statics/src/main/java/com/codeborne/selenide/Configuration.java



this class has all properties documented

Viele Grüße

Alexei Vinogradov

On 20. December 2018 at 20:39:35, Maksim Kostromin (notifications@github.com)
wrote:

Maybe someone can point me where can I look at full list available system
properties supported by Selenide?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/selenide/selenide/issues/895#issuecomment-449112942>,
or mute the thread
