### ISSUE TITLE
java.lang.NoSuchFieldError: INSTANCE

### ISSUE THREAD

**Issue by Roland4444** [selenide/selenide#898]
java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
	at io.github.bonigarcia.wdm.HttpClient.<init>(HttpClient.java:121)
	at io.github.bonigarcia.wdm.HttpClient.<init>(HttpClient.java:90)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:421)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:229)
	at com.codeborne.selenide.webdriver.WebDriverBinaryManager.setupFirefox(WebDriverBinaryManager.java:55)
	at com.codeborne.selenide.webdriver.WebDriverBinaryManager.setupBinaryPath(WebDriverBinaryManager.java:20)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:55)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:230)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:116)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:134)
	at com.codeborne.selenide.impl.Navigator.navigateTo(Navigator.java:66)
	at com.codeborne.selenide.impl.Navigator.open(Navigator.java:38)
	at com.codeborne.selenide.Selenide.open(Selenide.java:80)
	at com.codeborne.selenide.Selenide.open(Selenide.java:56)
	at playTest.user_can_search_everything_in_google(playTest.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:349)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:314)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:312)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:396)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Tests in error: 
  user_can_search_everything_in_google(playTest): INSTANCE

## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to Selenide).
Tell us what you were trying to do and what happened instead. 

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version:**
* **Chrome\Firefox\IE Version:**
* **Browser Driver Version:**
* **Selenium Version:**
* **OS Version:**

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by Roland4444** [comment]
https://github.com/Roland4444/scala_webdriver/blob/master/pom.xml   pom file

JDK 8

**Comment by rosolko** [comment]
@Roland4444 For first all `org.seleniumhq.selenium` package imports not necessary. For second - issue going from [webdrivermanager](https://github.com/bonigarcia/webdrivermanager) library not from selenide.

**Comment by Roland4444** [comment]
nah. Without selenide all works good

Selenium only

**Comment by rosolko** [comment]
selenide use webdrivermanager library inside, and this  issue well known and it's going from webdrivermanager

**Comment by vinogradoff** [comment]
I don't see any selenide or tests here in the pom
