### ISSUE TITLE
SelenideElement hover() throws NoSuchMethodError: org.openqa.selenium.interactions.internal.Locatable.getCoordinates()Lorg/openqa/selenium/interactions/internal/Coordinates;

### ISSUE THREAD

**Issue by parfyonovavera** [selenide/selenide#909]
## The problem
SelenideElement hover() throws NoSuchMethodError: org.openqa.selenium.interactions.internal.Locatable.getCoordinates()Lorg/openqa/selenium/interactions/internal/Coordinates;

## Details
UIAssertionError NoSuchMethodError: org.openqa.selenium.interactions.internal.Locatable.getCoordinates()Lorg/openqa/selenium/interactions/internal/Coordinates;

Caused by: java.lang.NoSuchMethodError: org.openqa.selenium.interactions.internal.Locatable.getCoordinates()Lorg/openqa/selenium/interactions/internal/Coordinates;
	at com.codeborne.selenide.ex.UIAssertionError.wrapThrowable(UIAssertionError.java:58)
	at com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java:54)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:70)
	at com.sun.proxy.$Proxy16.hover(Unknown Source)

## Tell us about your environment
* **Selenide Version: 5.1.0**
* **Chrome\Firefox\IE Version: doesn't matter**
* **Browser Driver Version: doesn't matter**
* **Selenium Version: 3.13.0**
* **OS Version: os x mojave**

## Code To Reproduce Issue [ Good To Have ]
List<SelenideElement> items = $$x("//div[@id='some_id']//span[@class='some_class']");
    for (SelenideElement item: items) {
      if (item.isDisplayed()) {item.hover();}
    }

**Comment by yuraku** [comment]
Hi. Are there any updates on it? I'm facing the similar issue
`org.openqa.selenium.interactions.internal.Locatable.getCoordinates()Lorg/openqa/selenium/interactions/internal/Coordinates;
java.lang.NoSuchMethodError: org.openqa.selenium.interactions.internal.Locatable.getCoordinates()Lorg/openqa/selenium/interactions/internal/Coordinates;
	at org.openqa.selenium.interactions.internal.MouseAction.getActionLocation(MouseAction.java:65)
	at org.openqa.selenium.interactions.internal.MouseAction.moveToLocation(MouseAction.java:72)
	at org.openqa.selenium.interactions.ClickAndHoldAction.perform(ClickAndHoldAction.java:45)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:36)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:641)`

**Comment by asolntsev** [comment]
@parfyonovavera @yuraku This issue is caused by dependency conflicts in your project. I guess you have different versions of `selenium-api.jar` and some `selenium-foo.jar` in your project. 

If it's still an issue, please provide your `pom.xml`/`build.gradle` or just print your dependency tree (output of `mvn dependency:tree` or `gradle dependencies`).
