### ISSUE TITLE
NPE when checking isDisplayed

### ISSUE THREAD

**Issue by pavelpp** [selenide/selenide#911]
## The problem
Occasionally this error happens. Not sure what's the exact scenario to reproduce. Perhaps there was some problem with RemoteWebdriver, as I'm running chrome in a container.

## Details
See stacktrace:

```
java.lang.NullPointerException
    at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:329)
    at com.codeborne.selenide.Condition$1.apply(Condition.java:23)
    at com.codeborne.selenide.Condition$18.apply(Condition.java:490)
    at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:51)
    at com.codeborne.selenide.commands.ShouldNot.shouldNot(ShouldNot.java:36)
    at com.codeborne.selenide.commands.ShouldNot.execute(ShouldNot.java:29)
    at com.codeborne.selenide.commands.ShouldNot.execute(ShouldNot.java:12)
    at com.codeborne.selenide.commands.Commands.execute(Commands.java:144)
    at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:99)
    at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
    at com.sun.proxy.$Proxy46.shouldNotBe(Unknown Source)
```

## Tell us about your environment
* **Selenide Version:** 5.1.0
* **Chrome\Firefox\IE Version:**  Chrome container selenium/standalone-chrome-debug:3.141.59

## Code To Reproduce Issue [ Good To Have ]
Can't really reproduce reliably. Happened to me once

**Comment by BorisOsipov** [comment]
As I see it is NPE into selenium `RemoteWebElement.java`...

**Comment by asolntsev** [comment]
I don't know how to reproduce the issue. Anyway, it's an issue of RemoteWebElement.java. Closing the issue.
