### ISSUE TITLE
JSONException when trying to upgrade to Selenide 5.2.0 with Selenium Grid 2 version 2.53

### ISSUE THREAD

**Issue by sadsridh** [selenide/selenide#916]
## The problem
I am trying to update Selenide from version 4.8 to 5.2.0 But I am getting the below error when running the tests on Jenkins that is running Selenium Grid 2 version 2.53.

I want to confirm if this due to the older Selenium Grid 2 version 2.53 ? 

As updating the Grid on the jenkins is a larger effort as there are other UI frameworks that still use older version of Selenium.

## Details
The issue doesn't seem its due to #873 or related to #887 as I do not have any selenide element being declared before open() and the failure happens in my setupSpec() where I call open(URL) because the driver cannot be created for some reason and in cleanupSpec() because there is no driver to kill. And there is a JsonException instead of a NPE during driver creation.

## Tell us about your environment
* Selenide Version:*5.2.0*
* Selenium Grid 2 Version:*2.53*

## Error Log

```
java.lang.IllegalArgumentException: org.openqa.selenium.WebDriverException: Unable to parse remote response: <html><head><title>Selenium Grid2.0 help</title></head><body>You are using grid 2.53.0<br>Find help on the official selenium wiki : <a href='https://github.com/SeleniumHQ/selenium/wiki/Grid2' >more help here</a><br>default monitoring page : <a href='/grid/console' >console</a></body></html>
	at com.codeborne.selenide.webdriver.AbstractDriverFactory.createInstanceOf(AbstractDriverFactory.java:52)
	at com.codeborne.selenide.webdriver.DefaultDriverFactory.create(DefaultDriverFactory.java:16)
	at com.codeborne.selenide.webdriver.WebDriverFactory.lambda$createWebDriver$2(WebDriverFactory.java:56)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:56)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:38)
	at com.codeborne.selenide.drivercommands.LazyDriver.createDriver(LazyDriver.java:93)
	at com.codeborne.selenide.drivercommands.LazyDriver.getAndCheckWebDriver(LazyDriver.java:87)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:143)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:61)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:24)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:59)
	at com.codeborne.selenide.Selenide.open(Selenide.java:39)
	at atg.cloud.controls.business.Browser.openAdminLoginPage(Browser.java:106)
	at atg.cloud.core.AdminUISpec.setupSpec(AdminUISpec.groovy:47)
Caused by: org.openqa.selenium.WebDriverException: Unable to parse remote response: <html><head><title>Selenium Grid2.0 help</title></head><body>You are using grid 2.53.0<br>Find help on the official selenium wiki : <a href='https://github.com/SeleniumHQ/selenium/wiki/Grid2' >more help here</a><br>default monitoring page : <a href='/grid/console' >console</a></body></html>
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at atg.cloud.core.webdriver.CustomWebDriverProvider.createDriver(CustomWebDriverProvider.java:74)
	at com.codeborne.selenide.webdriver.AbstractDriverFactory.createInstanceOf(AbstractDriverFactory.java:44)
	... 14 more

**THIS PART OF THE ERROR MAKES ME THINK ITS THE GRID VERSION MISMATCH**
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'bus00ceu.us.oracle.com', ip: '10.196.1.69', os.name: 'Linux', os.arch: 'amd64', os.version: '4.1.12-124.19.2.el6uek.x86_64', java.version: '1.8.0_181'
Driver info: driver.version: SelenideDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:122)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:140)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)
	at org.openqa.selenium.json.Json.toType(Json.java:69)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:112)
	... 22 more`

**STANDARD ERROR**
Feb 22, 2019 10:23:33 PM com.codeborne.selenide.drivercommands.LazyDriver getAndCheckWebDriver
INFO: No webdriver is bound to current thread: 12 - let's create a new webdriver
Feb 22, 2019 10:23:33 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
java.lang.IllegalStateException: No webdriver is bound to current thread: 12. You need to call open(url) first.
java.lang.IllegalStateException: No webdriver is bound to current thread: 12. You need to call open(url) first.
java.lang.IllegalStateException: No webdriver is bound to current thread: 12. You need to call open(url) first.
	at com.codeborne.selenide.drivercommands.LazyDriver.getWebDriver(LazyDriver.java:67)
	at com.codeborne.selenide.SelenideDriver.getWebDriver(SelenideDriver.java:139)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getWebDriver(WebDriverThreadLocalContainer.java:68)
	at com.codeborne.selenide.WebDriverRunner.getWebDriver(WebDriverRunner.java:71)
	at com.codeborne.selenide.WebDriverRunner$getWebDriver.call(Unknown Source)
	at atg.cloud.core.CCBaseTest.cleanupSpec(CCBaseTest.groovy:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:153)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:84)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
	at org.spockframework.runtime.BaseSpecRunner.doRunCleanupSpec(BaseSpecRunner.java:222)
	at org.spockframework.runtime.BaseSpecRunner$4.invoke(BaseSpecRunner.java:207)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
	at org.spockframework.runtime.BaseSpecRunner.runCleanupSpec(BaseSpecRunner.java:200)
	at org.spockframework.runtime.BaseSpecRunner.doRunCleanupSpec(BaseSpecRunner.java:224)
	at org.spockframework.runtime.BaseSpecRunner$4.invoke(BaseSpecRunner.java:207)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
	at org.spockframework.runtime.BaseSpecRunner.runCleanupSpec(BaseSpecRunner.java:200)
	at org.spockframework.runtime.BaseSpecRunner.doRunCleanupSpec(BaseSpecRunner.java:224)
	at org.spockframework.runtime.BaseSpecRunner$4.invoke(BaseSpecRunner.java:207)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
	at org.spockframework.runtime.BaseSpecRunner.runCleanupSpec(BaseSpecRunner.java:200)
	at org.spockframework.runtime.BaseSpecRunner.runCleanupSpec(BaseSpecRunner.java:195)
	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:99)
	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:84)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:76)
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:67)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by asolntsev** [comment]
Hi.
It seems that you have two problems.

1. Caused by the fast that Selenium Grid is too old (2.53). You need to upgrade to the latest version.
2. When tests failed to start Grid, they get another in method `cleanupSpec`.

```
java.lang.IllegalStateException: No webdriver is bound to current thread: 12. You need to call open(url) first.
  ...
  at atg.cloud.core.CCBaseTest.cleanupSpec(CCBaseTest.groovy:109)
```

To fix this, you need to add `if (WebDriverRunner.hasWebDriverStarted())` before calling `WebDriverRunner.getWebDriver()`.

**Comment by sadsridh** [comment]
Thanks @asolntsev  !
