### ISSUE TITLE
getThrowable() unexpectedly returns NPE when running tests in Selenium Grid

### ISSUE THREAD

**Issue by tee-dee** [selenide/selenide#919]
## The problem
Running in SeleniumGrid (Zalenium/docker-selenium) and using AssertionMode = SOFT, the `org.testng.ITestResult` object `getThrowable()` method returns `java.lang.NullPointerException` when failure(s) occur.

Expected: `com.codeborne.selenide.ex.SoftAssertionError` (with the failure message(s)) [NOTE: this is working when running locally/non-grid]

In our project we are using the information from `getThrowable()` to send test execution results (e.g. "FAIL 1: Element should be visible....   FAIL2: Element should not be visible" etc)

## Details
Running in grid 
- triggers both `onTestSuccess()`and `onTestFailure()` in `MyListener`
- `getFailedTests()`ResultMap contains the failed test

Running locally 
- triggers only `onTestFailure()`
- `getFailedtests()`ResultMap is empty

## Environment
* **Selenide Version: 5.1.0**
* **Chrome Version: 72**
* **Browser Driver Version in grid: 72.0.3626.81**
* **Browser Driver Version locally: 72.0.3683.68**
* **Selenium Version: 3.141.59**
* **OS Version in grid: Linux**
* **OS Version locally: Win10**
* **TestNG Version: 6.8.9**

## Code To Reproduce Issue
1) listeners/MyListener.class
```java
package listeners;

import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;
import utilities.*;

public class MyListener implements ITestListener {

  @Override
  public void onTestStart(ITestResult iTestResult) {}

  @Override
  public void onTestSuccess(ITestResult iTestResult) {}

  @Override
  public void onTestFailure(ITestResult iTestResult) {
    System.out.println("#### onTestFailure #####");
    printResult(iTestResult);
  }

  @Override
  public void onTestSkipped(ITestResult iTestResult) {}

  @Override
  public void onTestFailedButWithinSuccessPercentage(ITestResult iTestResult) {}

  @Override
  public void onStart(ITestContext iTestContext) {}

  @Override
  public void onFinish(ITestContext iTestContext) {
    System.out.println(">>>> onFinish > name: " + iTestContext.getName());
    System.out.println(">>>> onFinish > suite name: " + iTestContext.getSuite().getName());
    System.out.println(">>>> onFinish > failed tests: " + iTestContext.getFailedTests());
  }

  private void printResult(ITestResult result) {
    System.out.println(">>>> result name: " + result.getName());
    System.out.println(">>>> result status: " + result.getStatus());
    System.out.println(">>>> result success: " + result.isSuccess());
    System.out.println(">>>> result method name: " + result.getMethod().getMethodName());
    System.out.println(">>>> result method description: " + result.getMethod().getDescription());
    System.out.println(">>>> result attributes: " + result.getAttributeNames());
    System.out.println(">>>> result instance name: " + result.getInstanceName());
    System.out.println(">>>> result test name: " + result.getTestName());
    System.out.println(">>>> result throwable: " + result.getThrowable().toString());
    System.out.println(">>>> result context > name: " + result.getTestContext().getName());
    System.out.println(
        ">>>> result context > suite name: " + result.getTestContext().getSuite().getName());
    System.out.println(
        ">>>> result context > passed tests: " + result.getTestContext().getPassedTests());
    System.out.println(
        ">>>> result context > failed tests: " + result.getTestContext().getFailedTests());
    System.out.println(
        ">>>> result context > skipped tests: " + result.getTestContext().getSkippedTests());
    System.out.println(">>>> result parameters: " + Arrays.toString(result.getParameters()));
  }
}
```
2) tests/MyTest.class
```java
package tests;

import com.codeborne.selenide.testng.SoftAsserts;
import listeners.MyListener;
import org.openqa.selenium.MutableCapabilities;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.safari.SafariOptions;
import org.testng.ITestResult;
import org.testng.annotations.*;
import steps.User;
import utilities.ParametersHelper;

import java.net.MalformedURLException;
import java.net.URL;

import static com.codeborne.selenide.AssertionMode.SOFT;
import static com.codeborne.selenide.AssertionMode.STRICT;
import static com.codeborne.selenide.Configuration.assertionMode;
import static com.codeborne.selenide.WebDriverRunner.*;

@Listeners({SoftAsserts.class, MyListener.class})
public class MyTest {

  private static final String CAPABILITY_PLATFORM = "platform";
  private boolean runningInGrid = false;

  @BeforeTest(alwaysRun = true)
  @Parameters({"platform", "browser"})
  public void testSetup(String platform, @Optional("chrome") String browser) {
    System.out.println("#### BeforeTest: Platform | Browser  ----> " + platform + " | " + browser);
    String ciHost = ParametersHelper.getSeleniumGridHost();
    if (ciHost.length() > 0) {
      runningInGrid = true;
    }

    System.out.println("#### BeforeTest: runningInGrid  ----> " + runningInGrid);

    try {
      if (runningInGrid) {
        setupRemoteWebDriver(platform, browser, ciHost);
      } else {
        setupLocalWebDriver(browser);
      }
    } catch (NullPointerException e) {
      setupLocalWebDriver(browser);
    } catch (MalformedURLException e) {
      setupLocalWebDriver(browser);
    }
  }

  @BeforeMethod(alwaysRun = true)
  public void methodSetup() {
    assertionMode = SOFT;
  }

  @AfterMethod(alwaysRun = true)
  public void methodTearDown(ITestResult result) {
    assertionMode = STRICT;
  }

  @AfterTest(alwaysRun = true)
  public void testTearDown() {
    getWebDriver().quit();
    closeWebDriver();
  }

  private void setupLocalWebDriver(String browser) {
    if (browser.equalsIgnoreCase("firefox")) {
      setWebDriver(new FirefoxDriver());
    } else {
      setWebDriver(new ChromeDriver());
    }
  }

  private void setupRemoteWebDriver(String platform, String browser, String ciHost)
      throws MalformedURLException {

    MutableCapabilities options;

    if (browser.equalsIgnoreCase("firefox")) {
      options = new FirefoxOptions();
      options.setCapability(CAPABILITY_PLATFORM, platform);
    } else if (browser.equalsIgnoreCase("safari")) {
      options = new SafariOptions();
      options.setCapability(CAPABILITY_PLATFORM, platform);
    } else {
      options = new ChromeOptions();
      options.setCapability(CAPABILITY_PLATFORM, platform);
    }
    RemoteWebDriver driver =
        new RemoteWebDriver(new URL("http://" + ciHost + ":4444/wd/hub"), options);
    driver.manage().window().maximize();
    setWebDriver(driver);
  }

  /* ***************************************************** */
  /*                      TESTS                            */
  /* vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv */

  @Test(
      description = "As a user, I should see all html elements when opening the login page",
      groups = {"Login"})
  public void allElementsDisplayedTest() {
    new User().opensLogin().expectsCorrectUI();
  }
}
```
3) steps/User.class
```java
package steps;

import static com.codeborne.selenide.Selenide.open;

public class User {
  public UserOnLoginPage opensLogin() {
    open(<insertURLhere>);
    return new UserOnLoginPage();
  }
}
```
4) steps/UserOnLoginPage.class
```java
package steps;

import pages.LoginPage;

import static com.codeborne.selenide.Condition.*;

public class UserOnLoginPage {

  private final LoginPage loginPage = new LoginPage();

  public UserOnLoginPage expectsCorrectUI() {
    loginPage.verifyUI();
    return this;
  }
```
5) pages/LoginPage.java
```java
package pages;

import com.codeborne.selenide.SelenideElement;
import org.openqa.selenium.By;

import static com.codeborne.selenide.Condition.attribute;
import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.$;

public class LoginPage {
  private final SelenideElement someInputField = $(By.className("someinput"));
  private final SelenideElement someButton = $(By.className("somebutton"));

  public void verifyUI() {
    someInputField.shouldNotBe(visible);   // is really visible
    someButton.shouldNotBe(visible);  // is really visible
  }
}
```

6) utilities/ParametersHelper.java
```java
package utilities;

public class ParametersHelper {
  public static String getSeleniumGridHost() {
    return System.getProperty("gridserver", "");
  }
}
```

7) testng/testng.xml
```xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Login" thread-count="1" parallel="tests" verbose="1">
    <parameter name="platform" value="Linux"/>
    <test name="Chrome">
        <parameter name="browser" value="chrome"/>
        <groups>
            <run>
                <include name="Login"/>
                <exclude name="broken"/>
            </run>
        </groups>
        <classes>
            <class name="tests.MyTest"/>
        </classes>
    </test>
</suite>
```

Output logs running locally (IntelliJ > run `testng/testng.xml` (Note: `Failures: 0`)
```
[TestNG] Running:
  C:\........\project\testng\testng.xml
#### BeforeTest: Platform | Browser  ----> Linux | chrome
#### BeforeTest: runningInGrid  ----> false
Starting ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72) on port 43751
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
mar. 13, 2019 9:59:50 A.M. org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
#### onTestFailure #####
>>>> result name: allElementsDisplayedTest
>>>> result status: 2
>>>> result success: false
>>>> result method name: allElementsDisplayedTest
>>>> result method description: As a user, I should see all html elements when opening the login page
>>>> result attributes: []
>>>> result instance name: tests.MyTest
>>>> result test name: null
>>>> result throwable: com.codeborne.selenide.ex.SoftAssertionError: Test tests.MyTest.allElementsDisplayedTest failed.
2 checks failed

FAIL #1: Element should not be visible {By.className: someinputfield}
Element: '<input aria-required="true" autocapitalize="off" autocomplete="on" autocorrect="off" class="someinputfield"></input>'
Screenshot: file:/C:/Users/........./project/build/reports/tests/1552467595273.0.png
Page source: file:/C:/Users/........./project/build/reports/tests/1552467595273.0.html
Timeout: 4 s.

FAIL #2: Element should not be visible {By.className: somebutton}
Element: '<button aria-disabled="true" class="somebutton" data-element="button" type="submit">ButtonLabel</button>'
Screenshot: file:/C:/Users/........./project/build/reports/tests/1552467599988.1.png
Page source: file:/C:/Users/........./project/build/reports/tests/1552467599988.1.html
Timeout: 4 s.

>>>> result context > name: Chrome
>>>> result context > suite name: Login
>>>> result context > passed tests: [ResultMap map={[TestResult name=allElementsDisplayedTest status=FAILURE method=MyTest.allElementsDisplayedTest()[pri:0, instance:tests.MyTest@50b472aa] output={null}]=MyTest.allElementsDisplayedTest()[pri:0, instance:tests.MyTest@50b472aa]}]
>>>> result context > failed tests: [ResultMap map={}]
>>>> result context > skipped tests: [ResultMap map={}]
>>>> result parameters: []

com.codeborne.selenide.ex.SoftAssertionError: Test tests.MyTest.allElementsDisplayedTest failed.
2 checks failed

FAIL #1: Element should not be visible {By.className: someinputfield}
Element: '<input aria-required="true" autocapitalize="off" autocomplete="on" autocorrect="off" class="someinputfield"></input>'
Screenshot: file:/C:/Users/........./project/build/reports/tests/1552467595273.0.png
Page source: file:/C:/Users/........./project/build/reports/tests/1552467595273.0.html
Timeout: 4 s.

FAIL #2: Element should not be visible {By.className: somebutton}
Element: '<button aria-disabled="true" class="somebutton" data-element="button" type="submit">ButtonLabel</button>'
Screenshot: file:/C:/Users/........./project/build/reports/tests/1552467599988.1.png
Page source: file:/C:/Users/........./project/build/reports/tests/1552467599988.1.html
Timeout: 4 s.


	at com.codeborne.selenide.logevents.ErrorsCollector.failIfErrors(ErrorsCollector.java:42)
	at com.codeborne.selenide.testng.SoftAsserts.failIfErrors(SoftAsserts.java:83)
	at com.codeborne.selenide.testng.SoftAsserts.onTestSuccess(SoftAsserts.java:37)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1690)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1670)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

>>>> onFinish > name: Chrome
>>>> onFinish > suite name: Login
>>>> onFinish > failed tests: [ResultMap map={}]
===============================================
Login
Total tests run: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0
```

Output logs running in grid (`mvn clean test -Dgridserver="theGrid-hostname/ip"`)
```
[INFO] Running TestSuite
#### BeforeTest: Platform | Browser  ----> Linux | chrome
#### BeforeTest: runningInGrid  ----> true
Mar 12, 2019 6:02:17 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
#### onTestSuccess ####
>>>> result name: allElementsDisplayedTest
>>>> result status: 1
>>>> result success: true
>>>> result method name: allElementsDisplayedTest
>>>> result method description: As a user, I should see all html elements when opening the login page
>>>> result attributes: []
>>>> result instance name: tests.MyTest
>>>> result test name: null
#### onTestFailure #####
>>>> result name: allElementsDisplayedTest
>>>> result status: 2
>>>> result success: false
>>>> result method name: allElementsDisplayedTest
>>>> result method description: As a user, I should see all html elements when opening the login page
>>>> result attributes: []
>>>> result instance name: tests.MyTest
>>>> result test name: null
>>>> result throwable: java.lang.NullPointerException
>>>> result context > name: Chrome
>>>> result context > suite name: Login
>>>> result context > passed tests: [ResultMap map={[TestResult name=allElementsDisplayedTest status=SUCCESS method=MyTest.allElementsDisplayedTest()[pri:0, instance:tests.MyTest@2a65fe7c] output={null}]=MyTest.allElementsDisplayedTest()[pri:0, instance:tests.MyTest@2a65fe7c]}]
>>>> result context > failed tests: [ResultMap map={}]
>>>> result context > skipped tests: [ResultMap map={}]
>>>> result parameters: []
>>>> onFinish > name: Chrome
>>>> onFinish > suite name: Login
>>>> onFinish > failed tests: [ResultMap map={[TestResult name=allElementsDisplayedTest status=FAILURE method=MyTest.allElementsDisplayedTest()[pri:0, instance:tests.MyTest@2a65fe7c] output={null}]=MyTest.allElementsDisplayedTest()[pri:0, instance:tests.MyTest@2a65fe7c]}]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.462 s <<< FAILURE! - in TestSuite
[ERROR] allElementsDisplayedTest(tests.MyTest)  Time elapsed: 10.185 s  <<< FAILURE!
com.codeborne.selenide.ex.SoftAssertionError:
Test tests.MyTest.allElementsDisplayedTest failed.
2 checks failed

FAIL #1: Element should not be visible {By.className: someinputfield}
Element: '<input aria-required="true" autocapitalize="off" autocomplete="on" autocorrect="off" class="someinputfield"></input>'
Screenshot: file:/mnt/c/Users/........../project/build/reports/tests/1552413743289.0.png
Page source: file:/mnt/c/Users/........../project/build/reports/tests/1552413743289.0.html
Timeout: 4 s.

FAIL #2: Element should not be visible {By.className: somebutton}
Element: '<button aria-disabled="true" class="somebutton" data-element="button" type="submit">ButtonLabel</button>'
Screenshot: file:/mnt/c/Users/........../project/build/reports/tests/1552413747675.1.png
Page source: file:/mnt/c/Users/........../project/build/reports/tests/1552413747675.1.html
Timeout: 4 s.
```

**Comment by tee-dee** [comment]
I forked the current version (5.2.2-SNAPSHOT) and used it in our project. This problem seems to have been fixed. Is there an issue number where this has been addressed?

**Comment by tee-dee** [comment]
Confirmed it's the webdrivermanager causing this issue. Version 3.3.0 (included in future release 5.2.2 of Selenide) will resolve this issue

**Comment by tee-dee** [comment]
Side note: I had to add the following dependencies to my project to be able to use the selenide jar I built using `./gradlew jar`, to avoid getting ClassNotFound runtime exceptions

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.8.1</version>
        </dependency>

**Comment by tee-dee** [comment]
Another side note: In addition to upgrading Selenide to version 5.2.2, I had to bump TestNG version to 6.9.10.

**Comment by symonk** [comment]
thanks for a very informative post @tee-dee.  I think we might have plans here to remove WDM as a dependency, it looks like rosolko has a repo for a new WDM equivalent

**Comment by asolntsev** [comment]
Closing the issues - it seems it was resolved just by updating dependencies.
