### ISSUE TITLE
NPE in $.shouldHave(text())

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#977]
## The problem
I am not sure how to reproduce it, but I am getting sometimes the following error in my tests:

```java
java.lang.NullPointerException
at com.codeborne.selenide.impl.Html.contains(Html.java:15)
at com.codeborne.selenide.conditions.Text.apply(Text.java:23)
at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:51)
at com.codeborne.selenide.commands.Should.execute(Should.java:24)
at com.codeborne.selenide.commands.Should.execute(Should.java:10)
at com.codeborne.selenide.commands.Commands.execute(Commands.java:145)
at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:99)
at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
at com.sun.proxy.$Proxy13.shouldHave(Unknown Source)
at ui.mobile.MobileTaxlinkSpec.makeTwoTaxPaymentsThroughTaxlink(MobileTaxlinkSpec.java:42)
```

## Tell us about your environment
* **Selenide Version:** 5.3.1
* **Chrome\Firefox\IE Version:** Chrome 77

**Comment by cocorossello** [comment]
Does it happen in a single thread environment? I used to have one similar to that one, it was because I was holding a $() in a static variable and several threads were using it

**Comment by asolntsev** [comment]
Yes, in my case it happens in a single thread.

**Comment by asolntsev** [comment]
it was probably a bug in chromedriver. Cannot reproduce anymore.
